= Best practices for SEO

SEO is more about good habits than strategies. Good SEO outcomes depends on being disciplined. It means:

* Updating content frequently to keep it fresh.
* Manually adding internal links to every new thing you publish.
* Sweating the detail of everything you write.
* Doing thorough research and backing up your content with evidence from reliable sources.
* Crafting headlines that stand out in search.
* Constantly searching for new content opportunities.

Above all, write content that is genuinely useful to your target users. For example, write content that helps to solve real problems that your users have.

Do not spend much effort on trying to optimize content for particular search keywords or particular crawlers. Content must be easily parsable by machines, but beyond this you should focus on writing high quality content that people will find useful and want to share.

"Quality" content means independent, authoritative, and trustworthy content. Avoid producing content that is overly promotional or self-serving, or overly technical or jargon-heavy (unless appropriate for the target audience).

Don't oversell your products. Focus on how your product is different, now why it's better. "Better" is subjective and people will see right through any claims you make. Instead, incentivize people to try your product for themselves, and let them figure out if it's better or not.
