= Web vitals

Google publishes a list of
https://support.google.com/webmasters/answer/9205520[Core Web Vitals], which are
three metrics that Google uses to report on user experience. The metrics are:

* Largest Contentful Paint (LCP)
* Interaction to Next Paint (INP)
* Cumulative Layout Shift (CLS)

These are certainly useful metrics for measuring user experience, but they are
surprisingly unimportant when it comes to search engine ranking (at least in
Google). We know this because in a
https://www.youtube.com/watch?v=Ts7rPPIFhVg[2023 video] a Google dev advocate
said:

[quote]
____
Google Search always seeks to show the most relevant content, even if the page
experience is not the best. So page loading performance and also core web vitals
aren't as important as some people might think they are. They are not
irrelevant, but do not over focus on these things.
____

This has also been reiterated by John Mueller, Google's search relations team
lead, on numerous occasions on various
https://www.linkedin.com/feed/update/urn:li:activity:7254734115789234176/[social
media threads]:

[quote]
____
A perfect score is a fun technical challenge, and you'll learn something along
the way, I know the feeling (I worked on mine too), but it's not going to make
your site's rankings jump up.
____
