= Running multiple processes

In general, there should be one service or application per container. Multiple
containers can be started and connected using user-defined networks and shared
volumes, if necessary. But it is best practice to separate areas of concerns –
such as databases, and services in distributed systems – into separate
containers.

A container has a single main process, which is defined in the `ENTRYPOINT`
and/or `CMD` at the end of the Dockerfile. That service MAY fork into multiple
processes. For example, a web server may spawn multiple worker processes.

The container's main process is responsible for managing all the processes that
it starts. However, sometimes the main process isn't well designed to gracefully
stop child processes when the container exits. If this is the case for your
application, you can pass the `--init` option when you run the container. This
flag inserts a tiny init process into the container as the main process, which
handles "reaping" of all processes when the container exits.

If you really do need more than one service in a container, there are two main
ways to achieve this:

* Use a wrapper script as the main `CMD` process.
* Use a process manager like `supervisord`.

Documentation for both of these approach is available in
https://docs.docker.com/engine/containers/multi-service_container/[dockerdocs].
