= TS-33: Search Engine Optimization (SEO)
:toc: macro
:toc-title: Contents

This technical standard covers some SEO basics.

toc::[]

== Best practices for SEO

SEO is more about good habits than strategies. Good SEO outcomes depends on being disciplined. It means:

* Updating content frequently to keep it fresh.
* Manually adding internal links to every new thing you publish.
* Sweating the detail of everything you write.
* Doing thorough research and backing up your content with evidence from reliable sources.
* Crafting headlines that stand out in search.
* Constantly searching for new content opportunities.

Above all, write content that is genuinely useful to your target users. For example, write content that helps to solve real problems that your users have.

Do not spend much effort on trying to optimize content for particular search keywords or particular crawlers. Content must be easily parsable by machines, but beyond this you should focus on writing high quality content that people will find useful and want to share.

"Quality" content means independent, authoritative, and trustworthy content. Avoid producing content that is overly promotional or self-serving, or overly technical or jargon-heavy (unless appropriate for the target audience).

Don't oversell your products. Focus on how your product is different, now why it's better. "Better" is subjective and people will see right through any claims you make. Instead, incentivize people to try your product for themselves, and let them figure out if it's better or not.

== Defensive SEO

Defensive SEO is a strategy where you aim to rank highly for certain search terms, so your competitors don't. Defensive SEO can be particularly effective for the following types of searches:

* Comparisons between your product and your competitors.
* The best options in your product category.

// TODO: Expand on this.

== Targeting strategies

It’s easier to rank for 100 low-volume searches than a handful of lucrative, popular ones – especially early on, when you do not yet have a long-established web presence.

Consider, for example, the impact of publishing a tutorial on a niche topic. Based on research, you estimate 30 relevant searches per month – tiny! But Ahrefs gives the relevant search terms a score of zero out of 100, which means it is expected to be very easy to get a high ranking for these terms. In the end, the tutorial results in an average of five unique visits per day. That scales to around 1,850 unique users per year.

If you had 100 similar pages, that ~185,000 unique visitors every year, each of whom has a very specific problem that you are offering to solve for them.

Getting good at ranking for low competition keywords will make it easier to rank for high competition ones in the long run, too.

== Web vitals

Google publishes a list of https://support.google.com/webmasters/answer/9205520[Core Web Vitals], which are three metrics that Google uses to report on user experience. The metrics are:

* Largest Contentful Paint (LCP)
* Interaction to Next Paint (INP)
* Cumulative Layout Shift (CLS)

These are certainly useful metrics for measuring user experience, but they are surprisingly unimportant when it comes to search engine ranking (at least in Google). We know this because in a https://www.youtube.com/watch?v=Ts7rPPIFhVg[2023 video] a Google dev advocate said:

[quote]
____
Google Search always seeks to show the most relevant content, even if the page experience is not the best. So page loading performance and also core web vitals aren't as important as some people might think they are. They are not irrelevant, but do not over focus on these things.
____

This has also been reiterated by John Mueller, Google’s search relations team lead, on numerous occasions on various https://www.linkedin.com/feed/update/urn:li:activity:7254734115789234176/[social media threads]:

[quote]
____
A perfect score is a fun technical challenge, and you'll learn something along the way, I know the feeling (I worked on mine too), but it's not going to make your site's rankings jump up.
____

== SEO tools

SEO tools are just _tools_. They might make your life a little easier, but they won’t magically generate growth. An easy way to fail is to spend too much time learning or researching SEO tools, and not enough doing the important bit – the content.

Use a small number of good quality tools, rather than attempt to use lots of different ones.

Choose an all-in-one SEO tool – Ahrefs or SEMrush, for example. These tools cover most bases, such as rank tracking, keyword research, and competitor research.

Google Search Console is useful for finding problems and opportunities, including technical stuff like website performance. It is free to use.

https://keywordseverywhere.com/[Keywords Everywhere] is an inexpensive browser extension that augments Google search, Trends, and Search Console with keyword data.
