= References

* Astral.
  {link-ruff}[_Ruff_].

* Astral.
  {link-uv}[_uv_].

* Cannon, B (2018).
  {link-pep563}[_PEP 563: Postponed Evaluation of Annotations_].

* Goodger, D and Van Rossum, G (2001).
  {link-pep257}[_PEP 257: Docstring Conventions_].

* Google.
  {link-google-pyguide}[_Google Python Style Guide_].

* Levkivskyi, I, Roach, S, Van Rossum, G, and Lehtosalo, J (2017).
  {link-pep526}[_PEP 526: Syntax for Variable Annotations_].

* Moss, A and Elliott, C (2019).
  {link-pep604}[_PEP 604: Allow writing union types as X | Y_].

* Python Software Foundation.
  {link-python-src-layout}[_src layout vs flat layout_].

* Python Software Foundation.
  {link-python-tutorial}[_The Python Tutorial_].

* Solomatin, E (2019).
  {link-pep585}[_PEP 585: Type Hinting Generics In Standard Collections_].

* Van Rossum, G, Lehtosalo, J, and Langa, Ł (2014).
  {link-pep484}[_PEP 484: Type Hints_].

* Van Rossum, G, Warsaw, B, and Coghlan, N (2001).
  {link-pep8}[_PEP 8: Style Guide for Python Code_].
