= Standards

Markdown was originally informally specified by John Gruber in a 2004 blog post. Today, the language remains underspecified and, as a consequence, it has many incompatible interpretations.

To maximize portability and predictable rendering, documents SHOULD target a single, well-specified Markdown dialect. This technical standard RECOMMENDS *CommonMark* as a baseline.

CommonMark is an effort to provide an unambiguous, standardized specification. *GitHub Flavored Markdown (GFM)* is a strict superset of CommonMark that adds tables, strikethrough, task lists, and automatic linking of hyperlinks.

This technical standard RECOMMENDS writing Markdown documents that conform to the {link-commonmark-spec}[CommonMark Specification], and using extended syntax from the {link-gfm-spec}[GitHub Flavored Markdown Specification] where rendering tools support it. (Support for GFM is not limited to GitHub.com.)

Some tools and systems add their own extensions on top of GFM. GitHub, for example, supports callouts, which are not part of the GFM specification. Such extensions MAY be used where the target rendering engine supports them. But authors SHOULD be aware that they are not portable and will degrade in other renderers.

Avoid dialects that are not backed by a formal specification, such as the original Markdown.pl implementation. Avoid proprietary extensions that are unlikely to be portable across rendering engines.
