= Authentication

For user authentication, token-based or certificate-based authentication is RECOMMENDED over password-based authentication.

When users initially log in to a software system, before a token or certificate has issued, there MUST be strict requirements for user IDs and passwords, and two-factor authentication is strongly RECOMMENDED. See below for constraints on the inputs allowed for authentication.

Authentication operations MUST happen over a secure, encrypted channel (eg. TLS). Session data from a prior non-encrypted connection MUST NOT be reused to authenticate a user.

== Re-authentication

Re-authentication MUST be required prior to performing any destructive operations, such as deleting data, or performing any operation that is considered sensitive, such as changing a password or email address.

== Failed authentication attempts

Failed authentication attempts MUST be logged, and the logs MUST be monitored for suspicious activity.

There SHOULD be sensible restrictions on the number of failed authentication attempts permitted within a time window. This is to prevent brute-force attacks. For example, an account MAY be locked after three failed attempts in a 24 hour period.

A user MUST NOT be informed exactly _why_ their authentication attempt failed. This is to prevent information leakage that could be exploited by an attacker. For example, the application MUST NOT indicate whether the user ID or password was incorrect, or if a CAPTCHA code was inputted correctly.

== User IDs

User IDs MUST be at least four characters long and SHOULD be at least 7 characters long.

User IDs MUST be unique.

== User passwords

Users MUST be required to change their passwords on first login and after an administrative password reset.

In addition, it is RECOMMENDED that users be _prompted_ (but not necessarily _required_) to change their passwords at regular intervals, such as every 90 days.

New passwords SHOULD NOT match any of the user's previous 12 passwords.

Passwords MUST be validated for their strength. Users MUST be required to set strong passwords. A strong password is defined as:

* At least 8 characters long.
* Contains at least one uppercase ASCII letter, one lowercase ASCII letter, one number, and one special ASCII character, such as a punctuation mark or symbol, or at least one Unicode character outside of the ASCII range.
* Does not contain dictionary words, common phrases, or common patterns (eg. "12345678", "password", "qwerty", etc.)
* Does not contain the user's user ID, first name, last name, or any other personal information that could be easily guessed.

Applications SHOULD include both password generation tools and password strength meters to help users choose strong passwords.

In graphical user interfaces, input fields for passwords (and other secrets) MUST be masked to prevent display.

Stored passwords MUST be hashed and salted using a strong hashing algorithm. The following steps MUST be followed:

* Concatenate a salt with the user's password.
* Perform a hash on the result using the SHA-3 algorithm, if supported, else SHA-2 (minimum 256-bit hash output shall be used in either case).

== Reset password operations

There SHOULD be sensible restrictions on the number of times a user can trigger a reset password operation on their account within a time window. For example, a user MAY be allowed to trigger a reset password operation no more than three times in any 24 hour period, without an administrative override.

It MUST be possible for users to further secure their accounts by disabling the reset password functionality, or by requiring additional verification steps (such as mobile authentication) for reset password operations.

Reset password operations should generate a short-lived one-time token that is sent to the user via out-of-band communication such as email or SMS, and whose scope is limited to a change password operation. It is RECOMMENDED that this token be valid for no more than 30 minutes.

Reset password operations MUST be logged, and the logs MUST be monitored for suspicious activity.

Users MUST be notified – via both out-of-band communication such as email or SMS, and also via an application's interface – when a reset password operation is triggered on their account. There MUST be a mechanism for users to report suspicious reset password requests and to immediately "lock" their account in the event of a suspected compromise.

== CAPTCHA

reCAPTCHA v2 or v3 MAY be implemented for user authentication operations, for additional security.

It is RECOMMENDED to display a CAPTCHA after a first failed authentication attempt. In addition, it is RECOMMENDED to display a CAPTCHA for transactions that require elevated permissions, such as for changing a password or performing a destructive operation such as deleting data.
