= Web application security

The following security measures are specific to web applications that are served
over HTTP/S and accessed via web browsers.

== Security headers

The `Strict-Transport-Security` header MUST be sent on each HTTP transaction.
The `max-age` directive MUST be set to at least 86400 (1 day).

Applications MUST return a `Content-Security-Policy` header. The RECOMMENDED
baseline for this directive is:

* `default-src 'self'`
* `object-src 'none'`
* `frame-ancestors 'deny'`
* `frame-src 'none'`
* `bse-url 'self'`
* `form-action 'self'`

The `X-XSS-Protection` header SHOULD be sent with each HTTP transaction in cases
where `Content-Security-Policy` is not supported (in legacy browsers). The value
MUST be set to `1; mode=block`, which enables XSS protection in browsers that
support this header.

The `X-Frame-Options` header MUST be sent with each HTTP transaction. Either the
deny or the same origin directive SHOULD be used.

The `X-Content-Type-Options` header MUST be sent on each HTTP transaction. The
"no-sniff" directive MUST be set.

== Caching control

The `Cache-Control` header MUST be sent with each HTTP transaction. The
`max-age` directive MUST be sent, unless the `no-cache` directive is used. The
`max-age` value must be set to a value determined by the sensitivity of the data
being sent to the client. Higher sensitivity data should have a lower `max-age`
value. The `max-age` MUST NOT be longer than 1 year.

The `Expires` header MUST be sent with each HTTP transaction, with a value that
is consistent with the `max-age` directive in the `Cache-Control` header.

== Other data controls

Web applications MUST NOT operate in such a way that causes confidential or
restricted data to be stored on the client after session termination, without
explicit acknowledgement by the client/user. Examples include storage in browser
caches, browser URL histories, persistent memory objects, form autocomplete
histories, client-side JARs, Active-X controls, Flash shared objects, etc.

Applications MUST disable browser and proxy caching if sending confidential or
restricted information. A combination of all three of the following headers is
RECOMMENDED, to satisfy different browsers:

* `Pragma=nocache`
* `Expires="01 Jan 1971 01:01:01 GMT"`
* `Cache-Control="no-store"`

In addition, applications MUST disable the browser auto-complete feature on
forms via which confidential or restricted information may be inputted by the
user.

Interpreted client-side code MUST NOT contain hard-coded passwords, usernames,
or database connection strings.

If non-sensitive data needs to be stored on the client, the following procedures
MUST be followed:

* Data that is not intended for public access MUST be encrypted.
* Data MUST NOT be stored in world readable/writeable locations.
* Data MUST be purged when it is not longer required.

Web applications that generate file-based content intended for one-time viewing
MUST remove access to the file immediately after being retrieved by the user.
The request to access the file MUST be validated to prevent unauthorized access.

Confidential data MUST NOT be sent via SMS, email, or push notifications.
