= Asynchronous operations

In general, synchronous operations SHOULD be preferred over asynchronous ones, as they simplify implementations on both the server-side and client-side. But there are some use cases where asynchronous operations are necessary or beneficial.

Asynchronicity is particularly advantageous in long-running tasks, such as image processing and video transcoding. It is also useful in operations that require interactions with external systems, such as sending emails or SMS messages, where the response time of the external system is unpredictable and where the client requires only confirmation that the message was _sent_ and does not require an immediate understanding of the outcome of that operation.

In implementing asynchronous operations, it is RECOMMENDED to conform to the following best practices.

Responses to resource creation, update, and deletion operations SHOULD return the `202 Accepted` status code. This indicates that the request has been accepted for processing, but the processing has not yet been completed.

The response body MAY include hypermedia links to any created or updated resources. There are two possible approaches to implementing this in the context of asynchronous operations. The first option is to include the final URL of the resource, from where clients can `GET` the latest representation of the resource in the normal way. This can be a good option in scenarios where the resource's ID and path are already known. If a newly-created resource is not yet ready, or if the resource has been deleted, the final URL SHOULD return the HTTP status code `404 Not Found`. Clients simply keep polling the provided endpoint until it is confirmed that the resource has been mutated as expected.

[source,json]
----
{
  "rel": "self",
  "method": "GET",
  "href": "/v1/namespace/resources/{resource_id}"
}
----

A second option is to return a temporary URL where the status of the queued operation may be obtained via some kind of temporary identifier.

[source,json]
----
{
  "rel": "self",
  "method": "GET",
  "href": "/v1/queue/requests/{request_id}"
}
----

It is RECOMMENDED that all HTTP APIs that implement asynchronous processing also support a single webhook that clients may optionally implement to receive push notifications of any asynchronously-updated resources, or the results of any asynchronously-processed actions. This offers a third option for clients to keep their state synchronized with server changes – whether triggered by asynchronous operations or even by other clients. See *link:../022/README.adoc[TS-22: Webhooks]* for further guidelines on implementing this option.

It may be desirable to support both synchronous and asynchronous processing on the same endpoints. One possible design pattern is to support synchronous processing by default but allow clients to opt-in to asynchronous processing using the `Prefer=respond-async` header.
