= Versioning and managing breaking changes

HTTP APIs SHOULD have a major version number that is incremented whenever there are breaking changes in the API. The major version number SHOULD be encoded in the first path segment of the URL.

.Template
----
/v{major}
----

.Example
----
/v1
----

Use the *expanding contract* pattern to maintain backwards compatibility with clients, while incrementally evolving the API's design and capabilities. This is also known as the *additive* approach to building programmatic interfaces.

In practice, this means:

* Breaking changes MUST NOT be made to APIs that are already in use.

* Developers MUST NOT add new required parameters to existing APIs.

* Developers MUST NOT remove existing required parameters.

* Developers MUST NOT change the meaning of existing parameters.

* APIs MUST be designed to be extensible.

A good example of a scalable API design is one that avoids array of scalar data types (strings, integers, etc.). Consider the following example:

[source,json]
----
{
  "countries": [
    "Brazil",
    "France"
  ]
}
----

This data structure is impossible to extend without introducing breaking changes. Always prefer arrays of objects, eg.:

[source,json]
----
{
  "countries": [
    { "name": "Brazil" },
    { "name": "France" }
  ]
}
----

Breaking changes include any changes to the request or response message formats, changes to the semantics of the API, or changes to the behavior of the API.

Where breaking changes are unavoidable, the breaking changes MUST be implemented in a new major version of the API. The old version of the API MUST be maintained for a reasonable period of time to allow clients to migrate to the new version.

APIs MUST have a documented *lifecycle policy*, which describes the support and maintenance of each major version of the API.
