= Technical Standards

These technical standards are a set of general guidelines for software
development that I have curated to help me write high quality, high value
software products.

The scope of these technical standards is broad. At the highest levels they
cover principles of software design and architecture, and at lower levels they
cover coding conventions for a wide variety of computer languages.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords
"REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT",
"OPTIONAL", and "MAY" are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== Formatting

Technical standards documents are written in the AsciiDoc format, as
specified in the AsciiDoctor docs:

https://docs.asciidoctor.org/asciidoc/latest/

=== Tables of contents

Long technical standards documents MUST include a table of contents. This
can be generated automatically by the AsciiDoc processor. It is RECOMMENDED
to use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro]
to control the position of the TOC in each document. Example:

[source,asciidoc]
----
= TS-1: Example Technical Standard
:toc: macro

Some introductory text here.

toc::[]

== Section 1

...
----

== Contributing

To make changes to a technical standard, or to create a new one, use the
normal pull request workflow via GitHub.

== TS index

// TS-1 HTTP API Standards
// TS-2 CLI Standards
// TS-3 ECMAScript (JavaScript) Standards
// TS-4 Node.js API Standards
// TS-5 Web Platform API Standards
// TS-6 HTML Standards
// TS-7 CSS Standards
// TS-8 Java Standards
// TS-9 PHP Standards
// TS-10 React Standards
// TS-11 Markdown Standards
// TS-12 AsciiDoc Standards

== By category

////

=== Life cycle

* IT change management

=== Requirements

* Requirements specification - Functional requirements specification
* Constraints - Non-functional requirements specification

=== Design

Architecture and design, including quality attributes / constraints.

* Architecture
* Distributed systems
* Application development
* Library development
* Data protection / Privacy
* Security

=== APIs

* HTTP APIs
* CLIs

=== Programming

* OOP
* FP

=== Computer languages and application runtime environments

* Web platform APIs
* Java
* ECMAScript
* TypeScript
* Node.js
* PHP
* React
* Markdown
* AsciiDoc
* HTML
* CSS

=== Documentation

* Documentation
* Writing
* Diagrams

=== Quality assurance

* Quality control
* Release testing
* Functional testing
* Non-functional testing

=== Releasing

* Versioning
* Releasing

=== Infrastructure

* Dependency management
* Environments
* Environment variables
* Logging
* Visibility (observability and monitoring)

=== Storage and caching

* Relational databases
* Document-oriented databases and NoSQL

=== Development and operations tools

* Source control (Git)
* VS Code
* GitHub Actions
* Docker

////

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
