= Technical Standards

These technical standards are a set of general guidelines for software development that I have curated over time to help me write high quality, high value software products.

The scope of these technical standards is broad. The technical standards cover all aspects of the software development life cycle, from requirements specification and system design, via coding standards and testing strategies, to deployment and monitoring.

Technical standards are owned exclusively by a project's technical stakeholders. The purpose of technical standards is to define what "good" looks like from a technical perspective. Technical standards describe desirable end results, but not the process of reaching those results. Thus, the topic of IT project management is out of scope of these technical standards and is instead the topic of my *https://github.com/kieranpotts/playbook[software development playbook]*.

These technical standards apply to production systems, and also to development tools and operations infrastructure. These technical standards are not applicable to prototypes, proofs of concept, or other temporary artifacts.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords "REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT", "OPTIONAL", and "MAY" are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== Index

* link:./ts/001-guiding-principles.adoc[TS-1: *Guiding Principles of Software Development*]
* link:./ts/XXX-issue-tracking.adoc[TS-XXX: *Issue Tracking*]
* link:./ts/XXX-source-control.adoc[TS-XXX: *Source Control*]
* link:./ts/XXX-releasing.adoc[TS-XXX: *Releasing*]
* link:./ts/XXX-versioning.adoc[TS-XXX: *Versioning*]
* link:./ts/XXX-requirements-specification.adoc[TS-XXX: *Requirements Specification*]
* link:./ts/XXX-quality-control.adoc[TS-XXX: *Quality Control*]
* link:./ts/XXX-functional-testing.adoc[TS-XXX: *Functional Testing*]
* link:./ts/XXX-performance-testing.adoc[TS-XXX: *Performance (Non-Functional) Testing*]
* link:./ts/XXX-system-design.adoc[TS-XXX: *System Design and Modeling*]
* link:./ts/XXX-application-architecture.adoc[TS-XXX: *Application Architecture*]
* link:./ts/XXX-user-interfaces.adoc[TS-XXX: *User Interfaces*]
* link:./ts/XXX-network-apis.adoc[TS-XXX: *Network APIs*]
* link:./ts/XXX-http-apis.adoc[TS-XXX: *HTTP APIs*]
* link:./ts/XXX-messages.adoc[TS-XXX: *Messages and Events*]
* link:./ts/XXX-json-schema.adoc[TS-XXX: *JSON Schema*]
* link:./ts/XXX-cli.adoc[TS-XXX: *Command Line Interfaces (CLIs)*]
* link:./ts/XXX-ecmascript.adoc[TS-XXX: *ECMAScript (JavaScript/TypeScript)*]
* link:./ts/XXX-web-platform.adoc[TS-XXX: *Web Platform APIs*]
* link:./ts/XXX-web-guis.adoc[TS-XXX: *Web GUIs*]
* link:./ts/XXX-nodejs.adoc[TS-XXX: *Node.js Applications*]
* link:./ts/XXX-html.adoc[TS-XXX: *HTML*]
* link:./ts/XXX-css.adoc[TS-XXX: *CSS*]
* link:./ts/XXX-react.adoc[TS-XXX: *React*]
* link:./ts/XXX-vue.adoc[TS-XXX: *Vue*]
* link:./ts/XXX-java.adoc[TS-XXX: *Java*]
* link:./ts/XXX-php.adoc[TS-XXX: *PHP*]
* link:./ts/XXX-documentation.adoc[TS-XXX: *Documentation*]
* link:./ts/XXX-technical-writing.adoc[TS-XXX: *Technical Writing*]
* link:./ts/XXX-seo.adoc[TS-XXX: *Search Engine Optimization (SEO)*]
* link:./ts/XXX-markdown.adoc[TS-XXX: *Markdown*]
* link:./ts/XXX-asciidoc.adoc[TS-XXX: *AsciiDoc*]
* link:./ts/XXX-relational-databases.adoc[TS-XXX: *Relational Databases and SQL*]
* link:./ts/XXX-non-relational-databases.adoc[TS-XXX: *Non-Relational (NoSQL) Databases*]
* link:./ts/XXX-dates-times.adoc[TS-XXX: *Dates and Times*]
* link:./ts/XXX-platform-engineering.adoc[TS-XXX: *Platform Engineering*]
* link:./ts/XXX-security.adoc[TS-XXX: *Security and Secrets Management*]
* link:./ts/XXX-privacy.adoc[TS-XXX: *Privacy and Data Protection*]
* link:./ts/XXX-visibility.adoc[TS-XXX: *Visibility (Logging, Monitoring, and Observability)*]
* link:./ts/XXX-environment-variables.adoc[TS-XXX: *Environment Variables*]
* link:./ts/XXX-docker.adoc[TS-XXX: *Docker*]
* link:./ts/XXX-aws.adoc[TS-XXX: *Amazon Web Services (AWS)*]
* link:./ts/XXX-github-actions.adoc[TS-XXX: *GitHub Actions*]

== Contributing

All technical standards are living documents. To make changes to a technical standard, or to create a new one, use the normal pull request workflow via GitHub.

Technical standards documents are written in the AsciiDoc format, as specified in the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoctor docs]. Long technical standards documents MUST include a table of contents, generated automatically by the AsciiDoc processor. It is RECOMMENDED to use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro]
to control the position of the TOC in each document.

.Example
[source,asciidoc]
----
= TS-1: Technical Standard #1
:toc: macro
:toc-title: Contents

Introductory text…

toc::[]

== Section 1

…
----

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
