= Technical Standards

These technical standards are a set of general guidelines for software development that I have curated over time to help me write high quality, high value software products.

The scope of these technical standards is broad. The technical standards cover all aspects of the software development lifecycle, from requirements specification and system design, via coding standards and testing strategies, to deployment and monitoring.

Technical standards are owned exclusively by a project's technical stakeholders. The purpose of technical standards is to define what "good" looks like from a technical perspective. Technical standards describe desirable end results, but not the process of reaching those results. Thus, the topic of IT project management is out of scope of these technical standards and is instead the topic of my https://github.com/kieranpotts/playbook[software development playbook].

These technical standards apply to production systems, and also to development tools and operations infrastructure. They are not applicable to prototypes, proofs of concept, or other temporary artifacts.

In an enterprise context, the inclusion of a technology in a technical standard indicates that the technology is approved for use in development, testing, and operations. Organization-level technical standardization is important to contain technical sprawl, especially in large-scale distributed software systems.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords "REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT", "OPTIONAL", and "MAY" are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== Index

* link:./ts/001-guiding-principles.adoc[TS-1: *Guiding Principles of Software Development*]
* link:./ts/002-issue-tracking.adoc[TS-2: *Issue Tracking*]
* link:./ts/003-source-control.adoc[TS-3: *Source Control*]
* link:./ts/004-releasing.adoc[TS-4: *Releasing*]
* link:./ts/005-versioning.adoc[TS-5: *Versioning*]
* link:./ts/006-requirements-specification.adoc[TS-6: *Requirements Specification*]
* link:./ts/007-quality-control.adoc[TS-7: *Quality Control*]
* link:./ts/008-functional-testing.adoc[TS-8: *Functional Testing*]
* link:./ts/009-performance-testing.adoc[TS-9: *Performance (Non-Functional) Testing*]
* link:./ts/010-system-design.adoc[TS-10: *System Design and Modeling*]
* link:./ts/011-application-architecture.adoc[TS-11: *Application Architecture*]
* link:./ts/012-user-interfaces.adoc[TS-12: *User Interfaces*]
* link:./ts/013-network-apis.adoc[TS-13: *Network APIs*]
* link:./ts/014-http-apis.adoc[TS-14: *HTTP APIs*]
* link:./ts/015-messages.adoc[TS-15: *Messages and Events*]
* link:./ts/016-json-schema.adoc[TS-16: *JSON Schema*]
* link:./ts/017-cli.adoc[TS-17: *Command Line Interfaces (CLIs)*]
* link:./ts/018-ecmascript.adoc[TS-18: *ECMAScript (JavaScript/TypeScript)*]
* link:./ts/019-web-platform.adoc[TS-19: *Web Platform APIs*]
* link:./ts/020-web-guis.adoc[TS-20: *Web GUIs*]
* link:./ts/021-nodejs.adoc[TS-21: *Node.js Applications*]
* link:./ts/022-html.adoc[TS-22: *HTML*]
* link:./ts/023-css.adoc[TS-23: *CSS*]
* link:./ts/024-react.adoc[TS-24: *React*]
* link:./ts/025-vue.adoc[TS-25: *Vue*]
* link:./ts/026-java.adoc[TS-26: *Java*]
* link:./ts/027-php.adoc[TS-27: *PHP*]
* link:./ts/028-documentation.adoc[TS-28: *Documentation*]
* link:./ts/029-technical-writing.adoc[TS-29: *Technical Writing*]
* link:./ts/030-seo.adoc[TS-30: *Search Engine Optimization (SEO)*]
* link:./ts/031-markdown.adoc[TS-31: *Markdown*]
* link:./ts/032-asciidoc.adoc[TS-32: *AsciiDoc*]
* link:./ts/033-yaml.adoc[TS-33: *YAML*]
* link:./ts/034-relational-databases.adoc[TS-34: *Relational Databases and SQL*]
* link:./ts/035-non-relational-databases.adoc[TS-35: *Non-Relational (NoSQL) Databases*]
* link:./ts/036-dates-times.adoc[TS-36: *Dates and Times*]
* link:./ts/037-cloud-platform-engineering.adoc[TS-37: *Cloud Platform Engineering*]
* link:./ts/038-security.adoc[TS-38: *Security and Secrets Management*]
* link:./ts/039-privacy.adoc[TS-39: *Privacy and Data Protection*]
* link:./ts/040-visibility.adoc[TS-40: *Visibility (Logging, Monitoring, and Observability)*]
* link:./ts/041-environment-variables.adoc[TS-41: *Environment Variables*]
* link:./ts/042-docker.adoc[TS-42: *Docker*]
* link:./ts/043-aws.adoc[TS-43: *Amazon Web Services (AWS)*]
* link:./ts/044-github-actions.adoc[TS-44: *GitHub Actions*]
* link:./ts/045-terraform.adoc[TS-45: *Terraform*]
* link:./ts/046-jwt.adoc[TS-46: *JSON Web Tokens (JWTs)*]

== Contributing

All technical standards are living documents. To make changes to a technical standard, or to create a new one, use the normal pull request workflow via GitHub.

Technical standards documents are written in the AsciiDoc format, as specified in the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoctor docs]. Long technical standards documents – with two or more sections – MUST include a table of contents, generated automatically by the AsciiDoc processor. Use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro] to control the position of the TOC in each document, after the introductory text and before the first section.

.Template
[source,asciidoc]
----
= TS-1: Technical Standard #1
:toc: macro
:toc-title: Contents

Introductory text…

toc::[]

== Section 1

…
----

Any books, blogs, or other third-party media that influenced the content of a technical standard MUST be listed in a references section at the end of the document.

.Template
[source,asciidoc]
----
…

''''

== References

* https://example.com[Link 1]

* https://example.com[Link 2]

* https://example.com[Link 3]
----

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
