= Technical Standards

These technical standards are a set of general guidelines for software development that I have curated over time to help me write high quality, high value software products.

The scope of these technical standards is broad. The technical standards cover all aspects of the software development life cycle, from requirements specification and system design, via coding standards and testing strategies, to deployment and monitoring. Technical standards are owned exclusively by a project's technical stakeholders.

The purpose of technical standards is to define what "good" looks like from a technical perspective. Technical standards describe desirable end results, not the process of reaching those results. Project management and change management are out of scope.

These technical standards apply to production systems, and also development and operations infrastructure and toolchains. These technical standards are not applicable to prototypes, proofs of concept, or other temporary artifacts. Inclusion of a technology in a technical standard indicates that the technology is approved for use in development, testing, and production environments.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords "REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT", "OPTIONAL", and "MAY" are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== Index

* link:./ts/001-guiding-principles.adoc[TS-1: Guiding Principles of Software Development]
* link:./ts/002-requirements-specification.adoc[TS-2: Requirements Specification]
* link:./ts/003-system-design.adoc[TS-3: System Design and Modeling]
* link:./ts/004-network-apis.adoc[TS-4: Network APIs]
* link:./ts/005-http-api.adoc[TS-5: HTTP APIs]
* link:./ts/006-cli.adoc[TS-6: Command Line Interfaces (CLIs)]
* link:./ts/007-ecmascript.adoc[TS-7: ECMAScript (JavaScript/TypeScript) Coding Standards]
* link:./ts/008-web-platform.adoc[TS-8: Web Platform APIs]

== Contributing

All technical standards are living documents. To make changes to a technical standard, or to create a new one, use the normal pull request workflow via GitHub.

Technical standards documents are written in the AsciiDoc format, as specified in the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoctor docs]. Long technical standards documents MUST include a table of contents. This can be generated automatically by the AsciiDoc processor. It is RECOMMENDED to use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro]
to control the position of the TOC in each document. Example:

[source,asciidoc]
----
= TS-1: Technical Standard #1
:toc: macro
:toc-title: Contents

Introductory text…

toc::[]

== Section 1

…
----

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
