= Technical Standards

These technical standards are a set of general guidelines for software development that I have curated over time to help me write high quality, high value software products.

The scope of these technical standards is broad. The technical standards cover all aspects of the software development life cycle, from requirements specification and system design, via coding standards and testing strategies, to deployment and monitoring. Technical standards are owned exclusively by a project's technical stakeholders.

The purpose of technical standards is to define what "good" looks like from a technical perspective. Technical standards describe desirable end results, not the process of reaching those results. Project management and change management are out of scope.

These technical standards apply to production systems, and also to development and operations infrastructure and toolchains. These technical standards are not applicable to prototypes, proofs of concept, or other temporary artifacts.

Inclusion of a technology in a technical standard indicates that the technology is approved for use in development, testing, and production environments. This constraint is particularly beneficial in distributed systems in which individual services are managed by autonomous teams. Organization-level technical standardization are important in this organizational context to contain technical sprawl.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords "REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT", "OPTIONAL", and "MAY" are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== Index

* link:./ts/001-guiding-principles.adoc[TS-1: *Guiding Principles of Software Development*]
* link:./ts/002-requirements-specification.adoc[TS-2: *Requirements Specification*]
* link:./ts/003-system-design.adoc[TS-3: *System Design and Modeling*]
* link:./ts/004-application-architecture.adoc[TS-4: *Application Architecture*]
* link:./ts/005-network-apis.adoc[TS-5: *Network APIs*]
* link:./ts/006-http-api.adoc[TS-6: *HTTP APIs*]
* link:./ts/007-cli.adoc[TS-7: *Command Line Interfaces (CLIs)*]
* link:./ts/008-ecmascript.adoc[TS-8: *ECMAScript (JavaScript/TypeScript) Coding Standards*]
* link:./ts/009-web-platform.adoc[TS-9: *Web Platform APIs*]
* link:./ts/010-web-gui.adoc[TS-10: *Web GUIs*]
* link:./ts/011-nodejs.adoc[TS-11: *Node.js Applications*]
* link:./ts/012-html.adoc[TS-12: *HTML Coding Standards*]
* link:./ts/013-css.adoc[TS-13: *CSS Coding Standards*]
* link:./ts/014-java.adoc[TS-14: *Java Coding Standards*]
* link:./ts/015-php.adoc[TS-15: *PHP Coding Standards*]
* link:./ts/016-react.adoc[TS-16: *React Coding Standards*]
* link:./ts/017-markdown.adoc[TS-17: *Markdown Standards*]
* link:./ts/018-asciidoc.adoc[TS-18: *AsciiDoc Standards*]
* link:./ts/019-issue-tracking.adoc[TS-19: *Issue Tracking*]
* link:./ts/020-source-control.adoc[TS-20: *Source Control*]
* link:./ts/021-github-actions.adoc[TS-21: *GitHub Actions*]
* link:./ts/022-docker.adoc[TS-22: *Docker*]
* link:./ts/023-environment-variables.adoc[TS-23: *Environment Variables*]
* link:./ts/024-relational-databases.adoc[TS-24: *Relational Databases*]
* link:./ts/025-non-relational-databases.adoc[TS-25: *Non-Relational (NoSQL) Databases*]
* link:./ts/026-security.adoc[TS-26: *Security*]
* link:./ts/027-privacy-and-data-protection.adoc[TS-27: *Privacy and Data Protection*]
* link:./ts/028-quality-controls.adoc[TS-28: *Quality Controls*]
* link:./ts/029-functional-testing.adoc[TS-29: *Functional Testing*]
* link:./ts/030-non-functional-testing.adoc[TS-30: *Non-Functional Testing*]
* link:./ts/031-releasing.adoc[TS-31: *Releasing*]
* link:./ts/032-versioning.adoc[TS-32: *Versioning*]
* link:./ts/033-logging-monitoring-observability.adoc[TS-33: *Logging, Monitoring, and Observability*]
* link:./ts/034-dates-times.adoc[TS-34: *Dates and Times*]
* link:./ts/035-writing.adoc[TS-35: *Writing*]
* link:./ts/036-technical-writing.adoc[TS-36: *Technical Writing*]
* link:./ts/037-seo.adoc[TS-37: *Search Engine Optimization (SEO)*]
* link:./ts/038-platform-engineering.adoc[TS-38: *Platform Engineering*]
* link:./ts/039-aws.adoc[TS-39: *Amazon Web Services (AWS)*]

== Contributing

All technical standards are living documents. To make changes to a technical standard, or to create a new one, use the normal pull request workflow via GitHub.

Technical standards documents are written in the AsciiDoc format, as specified in the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoctor docs]. Long technical standards documents MUST include a table of contents. This can be generated automatically by the AsciiDoc processor. It is RECOMMENDED to use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro]
to control the position of the TOC in each document. Example:

[source,asciidoc]
----
= TS-1: Technical Standard #1
:toc: macro
:toc-title: Contents

Introductory text…

toc::[]

== Section 1

…
----

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
