= Technical Standards

These technical standards are a set of general guidelines for software
development that I have curated over time to help me write high quality, high
value software products.

The scope of these technical standards is broad. At the highest levels they
cover principles of software design and architecture, and at lower levels they
cover coding conventions for a variety of computer languages.

However, the scope of these technical standards is scoped only to the
_design_ and _construction_ of software systems. These standards do not cover,
for example, project management and software delivery methodologies,
requirements gathering and specification, testing and release strategies, or
other processes within the software development life cycle. These things tend
to vary from project to project. These technical standards are intended to be
universal – relevant to any software project.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords
"REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT",
"OPTIONAL", and "MAY" are to be interpreted as described in
https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].

== Index

* link:./ts/001-guiding-principles.adoc[TS-1: Guiding Principles]
// TS-2: HTTP API Standards
// TS-3: CLI Standards
// TS-4: ECMAScript (JavaScript) Standards
// TS-5: Node.js API Standards
// TS-6: Web Platform API Standards
// TS-7: HTML Standards
// TS-8: CSS Standards
// TS-9: Java Standards
// TS-10: PHP Standards
// TS-11: React Standards
// TS-12: Markdown Standards
// TS-13: AsciiDoc Standards

== By category

=== Design

* link:./ts/001-guiding-principles.adoc[TS-1: Guiding Principles]

////

=== Requirements

* Requirements specification - Functional requirements specification
* Constraints - Non-functional requirements specification
  ** Privacy by design
  ** Security
  ** Performance
  ** Reliability
  ** Usability and accessibility

=== Design

Architecture and design, including quality attributes / constraints.

* Architecture
* Distributed systems
* Application development
* Library development
* Data protection / Privacy
* Security

=== APIs

* HTTP APIs
* CLIs

=== Programming

* OOP
* FP

=== Computer languages and application runtime environments

* Web platform APIs
* Java
* ECMAScript
* TypeScript
* Node.js
* PHP
* React
* Markdown
* AsciiDoc
* HTML
* CSS

=== Documentation

* Documentation
* Writing
* Diagrams

=== Quality assurance

* Quality control
* Release testing
* Functional testing
* Non-functional testing

=== Releasing

* Versioning
* Releasing

=== Infrastructure

* Dependency management
* Environments
* Environment variables
* Logging
* Visibility (observability and monitoring)

=== Storage and caching

* Database design
* Database schema
* Relational databases
* Document-oriented databases and NoSQL

=== Development and operations tools

* Source control (Git)
* VS Code
* GitHub Actions
* Docker

////

''''

.Contributing guidelines
****

To make changes to a technical standard, or to create a new one, use the
normal pull request workflow via GitHub.

Technical standards documents are written in the AsciiDoc format, as
specified in the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoctor docs].

Long technical standards documents MUST include a table of contents. This
can be generated automatically by the AsciiDoc processor. It is RECOMMENDED
to use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro]
to control the position of the TOC in each document. Example:

[source,asciidoc]
----
= TS-1: Example Technical Standard
:toc: macro

Some introductory text here.

toc::[]

== Section 1

...
----
****

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
