= Technical Standards

These technical standards are a set of general guidelines for software development that I have curated over time to help me write high quality, high value software products.

The scope of these technical standards is broad. They cover all aspects of the software development lifecycle, from requirements specification and system design, via coding conventions and testing strategies, to deployment and monitoring. These standards apply to production systems, and also to development tools and operations infrastructure, but not to prototypes, proofs of concept, or other temporary artifacts.

In an enterprise context, the inclusion of a technology in a technical standard indicates that the technology is approved for use in development, testing, and operations. Organization-level technical standardization is important to contain technical sprawl, especially in large-scale distributed software systems.

Technical standards are owned exclusively by a project's technical stakeholders. The purpose is to define what "good" looks like from a technical perspective.

Technical standards describe desirable end results, but not the process of reaching those results. Thus, the topic of IT project management is out of scope of these technical standards – though link:./ts/001-guiding-principles.adoc[TS-1] does touch on this subject.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords "REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT", "OPTIONAL", and "MAY" are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC2119].

== Index

* link:./ts/001-guiding-principles.adoc[TS-1: *Guiding Principles of Software Development*]
* link:./ts/002-issue-tracking.adoc[TS-2: *Issue Tracking*]
* link:./ts/003-source-control.adoc[TS-3: *Source Control*]
* link:./ts/004-releasing.adoc[TS-4: *Releasing*]
* link:./ts/005-versioning.adoc[TS-5: *Versioning*]
* link:./ts/006-requirements-specification.adoc[TS-6: *Requirements Specification*]
* link:./ts/007-quality-assurance.adoc[TS-7: *Quality Assurance*]
* link:./ts/008-functional-testing.adoc[TS-8: *Functional Testing*]
* link:./ts/009-performance-testing.adoc[TS-9: *Performance (Non-Functional) Testing*]
* link:./ts/010-system-design.adoc[TS-10: *System Design*]
* link:./ts/011-modeling.adoc[TS-11: *Modeling*]
* link:./ts/012-application-architecture.adoc[TS-12: *Application Architecture*]
* link:./ts/013-code-design.adoc[TS-13: *Code Design*]
* link:./ts/014-user-interfaces.adoc[TS-14: *User Interfaces*]
* link:./ts/015-network-apis.adoc[TS-15: *Network APIs*]
* link:./ts/016-http-apis.adoc[TS-16: *HTTP APIs*]
* link:./ts/017-messages.adoc[TS-17: *Messages and Events*]
* link:./ts/018-json-schema.adoc[TS-18: *JSON Schema*]
* link:./ts/019-sh.adoc[TS-19: *Unix Shells*]
* link:./ts/019a-bash.adoc[TS-19a: *Bash*]
* link:./ts/020-cli.adoc[TS-20: *Command Line Interfaces (CLIs)*]
* link:./ts/021-ecmascript.adoc[TS-21: *ECMAScript (JavaScript/TypeScript)*]
* link:./ts/022-web-platform.adoc[TS-22: *Web Platform APIs*]
* link:./ts/023-web-guis.adoc[TS-23: *Web GUIs*]
* link:./ts/024-nodejs.adoc[TS-24: *Node.js Applications*]
* link:./ts/025-html.adoc[TS-25: *HTML*]
* link:./ts/026-css.adoc[TS-26: *CSS*]
* link:./ts/027-react.adoc[TS-27: *React*]
* link:./ts/028-vue.adoc[TS-28: *Vue*]
* link:./ts/029-java.adoc[TS-29: *Java*]
* link:./ts/030-php.adoc[TS-30: *PHP*]
* link:./ts/031-documentation.adoc[TS-31: *Documentation*]
* link:./ts/032-technical-writing.adoc[TS-32: *Technical Writing*]
* link:./ts/033-seo.adoc[TS-33: *Search Engine Optimization (SEO)*]
* link:./ts/034-markdown.adoc[TS-34: *Markdown*]
* link:./ts/035-asciidoc.adoc[TS-35: *AsciiDoc*]
* link:./ts/036-yaml.adoc[TS-36: *YAML*]
* link:./ts/037-relational-databases.adoc[TS-37: *Relational Databases and SQL*]
* link:./ts/038-non-relational-databases.adoc[TS-38: *Non-Relational (NoSQL) Databases*]
* link:./ts/039-dates-times.adoc[TS-39: *Dates and Times*]
* link:./ts/040-cloud-platform-engineering.adoc[TS-40: *Cloud Platform Engineering*]
* link:./ts/041-security.adoc[TS-41: *Security and Secrets Management*]
* link:./ts/042-privacy.adoc[TS-42: *Privacy and Data Protection*]
* link:./ts/043-visibility.adoc[TS-43: *Visibility (Logging, Monitoring, and Observability)*]
* link:./ts/044-environment-variables.adoc[TS-44: *Environment Variables*]
* link:./ts/045-docker.adoc[TS-45: *Docker*]
* link:./ts/046-aws.adoc[TS-46: *Amazon Web Services (AWS)*]
* link:./ts/047-github-actions.adoc[TS-47: *GitHub Actions*]
* link:./ts/048-terraform.adoc[TS-48: *Terraform*]
* link:./ts/049-jwt.adoc[TS-49: *JSON Web Tokens (JWTs)*]

== Contributing

These technical standards are living documents. To make changes to a technical standard, or to create a new one, use the normal pull request workflow via GitHub.

Technical standards documents are written in the AsciiDoc format, as specified in the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoctor docs]. Long technical standards documents – with two or more sections – MUST include a table of contents, generated automatically by the AsciiDoc processor. Use the https://docs.asciidoctor.org/asciidoc/latest/toc/position/[TOC macro] to control the position of the TOC in each document, after the introductory text and before the first section.

.Template
[source,asciidoc]
----
= TS-1: Technical Standard #1
:toc: macro
:toc-title: Contents

Introductory text…

toc::[]

== Section 1

…
----

Any books, blogs, or other third-party media that influenced the content of a technical standard MUST be listed in a references section at the end of the document.

.Template
[source,asciidoc]
----
…

''''

== References

* https://example.com[Link 1]

* https://example.com[Link 2]

* https://example.com[Link 3]
----

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[CC0 license]
