= Abstraction

.TL;DR
****
* Abstraction hides complexity behind simplified interfaces.
* It compresses code and enables code reuse.
* Trade-off: deep abstractions are hard to understand and can be leaky.
* The best abstractions are small, simple, and focused.
* But deep abstractions are sometimes useful, too.
* Avoid premature abstraction. Extract once you're confident you can keep the
abstraction's interface stable.
* Evolve interfaces in a backwards-compatible way. If you can't do that, create
a new abstraction and incrementally deprecate the old one.
****

Perhaps the most important concept in code design is abstraction.

Abstraction is a general term that refers to any design pattern that hides
complexity. Complex behaviors and/or data are hidden behind some kind of facade,
which exposes a simplified interface for interacting with that hidden logic and
data.

.Definition of abstraction
[quote, Balzer et al. 1989]
____
Abstraction in programming is the process of identifying common patterns that
have systematic variations; an abstraction represents the common pattern and
provides a means for specifying which variation to use.

An abstraction facilitates separation of concerns: The implementor of an
abstraction can ignore the exact uses or instances of the abstraction, and the
user of the abstraction can forget the details of the implementation of the
abstraction, so long as the implementation fulfills its intention or
specification.
____

Abstraction is one of the primary ways by which we make complex systems seem
simpler than they really are. It is implemented through various constructs for
encapsulation, which are typically provided at the level of the programming
language – things like functions, classes, objects, modules, packages,
subroutines, plugins, and macros.

One of the effects of abstraction is the compression of other parts of the code.
Compression refers to complex behavior or logic being represented by less code.
Abstraction makes that possible by hiding complexity behind high-level
programming constructs like function calls. Where an abstraction is used to
extract complexity from code, all that is left in the code – in the place where
all that complexity previously existed – is just a reference to the abstraction.

Abstraction, and the compactness and cleanliness it brings to program code, is
widely held up to be a good thing. Abstraction leads to efficiently-expressed
logic, reducing cognitive load. Abstraction also facilitates code reuse.

[quote, R. Buckminster Fuller, Nine Chains to the Moon (1938)]
____
Do more and more with less and less until eventually you can do everything with
nothing.
____

But, like everything in software design, abstraction involves trade-offs. The
overuse and misuse of abstraction can create problems, too.

Be moderate in your application of abstraction. Avoid extremes and seek balance
between the trade-offs, which we'll discuss next.

== Abstraction depth

In most types of abstraction, the complexity that is hidden behind the facade –
the "common pattern" that is abstracted away – is replaced by an identifier of
some kind, like a function name or class name.

For code to remain understandable, the names given to abstractions SHOULD
accurately express _all_ the important details of the logic and data they hide.
The important details are everything that users of the abstraction need to
understand.

Creating good names for abstractions is easier to do when those abstractions are
small, simple, and focused.

For this reason, shallow abstractions are preferred to deep ones. A shallow
abstraction is something like a function with a single responsibility. The
function does just one very specific thing. It has a simple interface that
clearly expresses the function's expected behavior, without revealing the
technical details of its internal implementation.

A deep abstraction may also have a simple interface, but it hides significant
complexity. The user sees a straightforward interface but the component does
substantial work.

Deep abstractions can be very desirable for some requirements. Consider, for
example, a file I/O library where you call `read(file)` and the library handles
buffering, caching, and error handling internally. Or a database client where
you call `query()` and it handles connection pooling, parsing, optimization, and
networking. These are deep abstractions, because they hide a lot of
implementation detail. But they also have simple interfaces, because much of
their implementation detail does not need to be surfaced to users. These are
good abstractions.

But generally, deep abstractions, which hide complex operations, tend to be
quite difficult to express with sufficient precision and accuracy. Consider, for
example, a single function call that hides hundreds of lines of logic, including
important business rules, and that has multiple interactions with various
external systems. It would be hard to come up with a name that expresses all of
the abstraction's important behavior – stuff that is important to users of the
abstraction. Such an abstraction would also be pretty difficult to debug, to
reuse in different contexts, and to modify and extend.

It's much more important for an abstraction to have a simple interface than a
simple implementation. Though we ought to be wary of over abstracting things,
deep abstractions can be effective as long as their interfaces can be made to be
simple and stable. The goal of abstraction is primarily to create _simple and
stable representations_ of discrete units of logic and/or data – however simple
or complex those extracted units of logic and data are.

Thus, we should not put arbitrary limits on abstractions. We should not, for
example, cap the number of statements allowed in a function body, or restrict
the number of protected or private methods within a class. Abstractions should
be as deep as they need to be to sufficiently hide their internal implementation
details.

Remember, the primary purpose of an abstraction is to extract complexity from
elsewhere in the application code. Do what you need to do to hide that
complexity from users of the abstraction.

== Leaky abstractions

Deep abstractions tend to be leaky. Because deep abstractions encapsulate lots
of complexity, there's a greater chance that some of that complexity will
necessarily be exposed through the abstractions' public interfaces.
Implementation details leak out through the interface.

The problem with leaky abstractions is that, if their internal implementations
change, they typically require corresponding changes to their public interfaces.
If you need to change the public interface to an abstraction, you will need to
change the calling code wherever that abstraction is used, too. Thus, changes in
low-level implementation details can snowball into wider refactorings throughout
a codebase.

The purpose of an abstraction is for the user of the abstraction to be ignorant
of its implementation. Thus, good abstractions have generic interfaces that do
not leak their implementation details. The design goal is to be able to change
the internal workings of an abstraction while keeping its interface stable.

For the same reason, we should avoid premature abstraction. We should extract
common logic and data into abstractions only when we have a good level of
confidence that the interface to those new abstractions can be kept stable. The
best abstractions tend to emerge piecemeal, evolving naturally as the system
grows. Design grounded in actual usage, rather than speculation, tends to
produce abstractions that are more stable and better suited to the problem at
hand.

Once an abstraction is made, we should expect to evolve its interface only in a
backwards-compatible way. Where an interface cannot be changed in a
backwards-compatible way, a new version of the abstraction should be created,
leaving the old version in place to allow for incremental migration to the new
version.

The risks of premature abstraction are greatest in distributed systems.
Extracting microservices too early, for example, can lead to services that are
difficult to evolve independently of one another, due to volatility in their
interfaces and tight coupling between them. The problem is much less acute in
single-node applications, where all the code is in a single repository and
deployed simultaneously. Here, you can more safely evolve the interfaces to your
abstractions.

== Vertical consistency

Within each of the tiered layers of an application's architecture, there should
be a consistent level of abstraction.

Within a layer, if one module makes calls to high-level business services, there
should not be another module that implements low-level abstractions for things
like string manipulation – even if that second module is unconnected to the
first.

Mixed abstraction levels are even worse when they exist in the same module. Such
code reads like a "stream of consciousness" of the developer's thought process
as they tried to make something work, rather than a polished design.

Mixed abstraction levels are a code smell that indicates that some things should
be extracted to new abstractions.
