= Comments

.TL;DR
****
* Reject "clean code" orthodoxy that discourages comments.
* Comments _are_ valuable for algorithms, business rules, design rationales, and assumptions.
* The focus of code comments should be on what's not obvious from the code alone.
* Programs written in low-level languages, like shell scripts, benefit from more comments.
* `TODO` comments are acceptable for work-in-progress code in the context of continuous integration procedures.
* If in doubt: leave a comment!
****

As discussed in earlier sections, abstraction is the primary mechanism for making code expressive and self-explanatory. But abstraction is not always the right tool. When the choice is between premature abstraction and some well-placed comments, add the comments. Comments are cheaper and more reversible than abstractions, and they don't introduce new dependencies or indirection.

The so-called "self-documenting code" approach, popularized by https://www.goodreads.com/book/show/3735293-clean-code[Uncle Bob's "Clean Code" book], encourages developers to express intent through well-named abstractions rather than comments. This has merit, but comments cannot be avoided altogether. There are many things that cannot be easily expressed in code alone, no matter how good the abstractions are. Complex algorithms, important context about business rules, rationales for non-obvious design decisions, and assumptions made about how black-box dependencies work – all these things cannot be fully captured by code alone, and yet this is important knowledge that other developers will need to understand and maintain the code in the future.

Comments are most useful when they explain things that are not obvious from the code itself. Programs written in low-level languages, like shells and other scripting languages, tend to require more comments, because low-level languages provide fewer constructs for abstraction, and the syntax tends to be quite cryptic and non-intuitive, too. In general, the lower the level of the programming language, the few opportunities there are for decomposition into good abstractions, and so the more comments will be relied upon to explain the code. Depending on the audience (the level of experience of the expected maintainers of the code), comments in low-level languages may need to be quite detailed, explaining even basic constructs and control flows.

Inline code comments are particularly valuable for documenting the rationale for unusual or unexpected code or configuration. For example, code that appears to violate good design, but has good reasons to do so (such as legacy constraints, performance requirements, or business necessity), should have those reasons clearly articulated alongside it. Similarly, the rationale for code smells, such as a bloated function or an overloaded class, should be clearly annotated alongside the code. Doing this reduces the risk of future maintainers wasting time trying to refactor the code.

So, we should ignore what Uncle Bob says and instead adopt the view that "comments are (mostly) good"! Even if code looks a bit messier with the addition of comments, this is usually preferable to losing valuable knowledge.

This is not to say that comments should be liberally sprinkled throughout code. Comments that are superfluous, redundant, or that do not add any tangible value, should be removed.

Remember: the purpose of comments is to reduce cognitive overhead. Whatever the language or level of abstraction, add comments where they make things easier to understand, or where you want to communicate important information that cannot be ascertained from the code alone – even with good abstractions.

_If in doubt: leave a comment!_

== Other forms of documentation

Inline code comments should not be confused with out-of-band documentation, such as design documents, README files, wikis, and so on. Out-of-band documentation is appropriate for developer-oriented information that is not specific to any particular piece of code, such as overall system architecture, design rationales, and so on.

Use inline comments for documentation that benefits from being close to the code it describes, such as explanations of complex logic, business rules, assumptions, and so on. Also use inline comments for documentation that is likely to change as the code changes. Keeping the code close to its documentation will help to ensure that the documentation stays up to date.

Inline code comments should not be confused with inline API documentation, such as Javadoc comments or Python docstrings. These serve a different purpose to general inline comments.

== TODO comments

It is okay to leave TODO comments in code. Most software is a perpetual work-in-progress, and inline TODO annotations are particularly handy to communicate notes between developers while new or changed functionality is being implemented in an iterative and incremental fashion.

Under iterative and incremental development models, areas of a codebase may be incomplete at any point in time. If continuous integration is practiced, incomplete code may exist in the project's main branch of development. For example, buttons may exist in the UI, behind feature flags, that do not yet do anything when clicked.

It is RECOMMENDED that areas of incomplete code and configuration be tagged with a consistent inline commenting convention. This allows developers to search the entire codebase for incomplete code. Using a TODO commenting convention reduces the risk that incomplete user journeys will get shipped to production.

Another valid reason to use TODO comments is to flag known technical debt. This can help to keep the project's issue tracker more focused on business requirements, performance enhancements, and more widespread refactoring plans.

The following is a recommended convention for writing TODO comments. The lines should be prefixed with the appropriate comment syntax for the programming language.

----
TODO: <comment>
[<url>]
----

`<comment>` is REQUIRED and it should be a short description of the outstanding task. The `<url>` component is OPTIONAL and is a link to a related ticket in the project's issue tracker, if applicable.

Example:

[source,javascript]
----
// TODO: Find a better solution to ignoring Apollo's __typename key.
// https://hackscorp.atlassian.net/browse/HCK-1234
----

Most modern IDEs can be easily configured to parse a project space for this comment format, and to automatically generate a list of all "TODO" comments. For Visual Studio Code, the https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree[Todo Tree extension] is recommended. It adds a panel to the activity bar where the current workspace can be traversed in a tree view.

Not everyone likes to see "TODO" comments in source code. But used judiciously in appropriate contexts, they can provide a useful extra quality gate — if all the "TODO" comments are expected to be removed before the code hits production — and they provide a standard convention for cross referencing open issues from code.
