= TS-7: Code Design
:toc: macro
:toc-title: Contents

This technical standard covers low-level concerns related to the structure and
formatting of code. It covers topics such as naming conventions, commenting best
practices, and object-oriented design principles.

These guidelines are language-agnostic. They are intended to be applicable to
any general-purpose, high-level programming language – Python, Java, JavaScript,
etc. Some of the content will also be relevant for lower-level languages, such
as shell scripting languages like Bash.

[quote, Robert C. Martin]
____
Clean code can be read and maintained by people other than the original author.
It has unit and acceptance tests. It has meaningful names. It provides one way
rather than many ways of doing one thing. It has minimal dependencies, which are
explicitly defined, and provides a clean and minimal API. [...] The code must be
loosely coupled and highly cohesive – in other words, well designed.
____

Low-level coding design is a nuanced and subjective thing. Some code style
guides, like Robert C. Martin's "Clean Code", impose hard rules like maximum
line lengths and function line counts. This technical standard takes a more
pragmatic approach. Rather than imposing rules on your code, it merely sets out
some general principles to help guide you in finding a reasonable balance
between various trade-offs in code design.

While code design decisions are important, you should not dwell on them.
Instead, focus on logical separation, data structures, communication patterns,
and other architecturally-significant decisions. These concerns are the subject
of *link:../005/README.adoc[TS-5: Application Architecture]* and
*link:../002/README.adoc[TS-2: Software Design Qualities]*.

toc::[]

include::./01-bike-shedding.adoc[leveloffset=+1]
include::./02-abstraction.adoc[leveloffset=+1]
include::./03-decomposition.adoc[leveloffset=+1]
include::./04-expressiveness.adoc[leveloffset=+1]
include::./05-dependency-management.adoc[leveloffset=+1]
include::./06-comments.adoc[leveloffset=+1]
include::./07-error-handling.adoc[leveloffset=+1]
include::./08-code-structure.adoc[leveloffset=+1]
include::./09-object-oriented-design.adoc[leveloffset=+1]
include::./10-concurrency.adoc[leveloffset=+1]
