= TS-8: Functional Testing
:toc: macro
:toc-title: Contents

This technical standard covers testing strategies to evaluate the correct operation of a software system.

A system is said to be "correct" when it performs its intended functions correctly, across various scenarios including normal operation, edge cases, and error conditions.

Functional testing is the cornerstone of software quality assurance. It involves recording the behaviors observed in user workflows and business logic against expected outcomes as specified in the system requirements.

toc::[]

== Test doubles

A test double is a generic term for any object that stands in for a real object in a test. The real objects, which are swapped out for test doubles, are dependencies of the component-under-test.

There are several ways that test doubles can be implemented. The following terms refer to different designs for test doubles:

* Mocks
* Stubs
* Dummies
* Fakes
* Spies

There is no definitive definition of these terms, partly because the documentation for various test utilities tends to use the terms interchangeably. But here are the common definitions:

A *fake* is one of the most advanced types of test double. Fakes will often be fully functioning implementations of the interfaces of the components they replace. They tend to be developed and maintained alongside the real components in the application code (whereas most other types of doubles tend to be defined in the test code). Fake implementations will take some shortcuts in their implementation, so they can be run efficiently and not depend on external systems, which may not be available in test environments. For example, the fake implementation of a database repository may implement an in-memory store, instead.

A *mock* is pre-programmed with expectations about the calls it will receive. If the mock does not receive the expected calls and parameters, it will throw an error, causing the test that called it to fail. Unlike fakes, mocks tend not to replicate any internal logic from their real counterparts.

A *stub* can be thought of as a lightweight mock. A stub provides canned answers to calls made during the test, but it doesn't do anything more elaborate than that. Unlike a mock, a stub does not make any assertions itself – the test that uses it is expected to do that.

A *spy* is another type of lightweight mock. All it does is remember what calls it has received, and it can make that information available to the test for assertion purposes. But it does not make any assertions itself. A classic use case for a spy would be to record how many messages were sent to an email service.

Finally, a *dummy* refers to any test object that is passed around but never actually inspected by tests. These tend to minimal implementations – sometimes, just plain objects – of the real objects they replace. Dummies are commonly used to stand-in for function parameters. This word is also used in the context of dummy data, which is any data that is injected into the system-under-test in place of production data in non-production environments.

Mocks, fakes, and stubs are the terms that are used the most interchangeably. In practice, many test doubles have characteristics of all five designs. For this reason, the term "mock" tends to be used as a synonym for any kind of test double.

