= Test-driven development

[quote, Michael Feathers]
____
Every time you encounter a testability problem, there's an underlying design problem.
____

Test-driven development (TDD) is a method for writing software by writing tests first, then writing the code that makes the tests pass.

TDD puts you in the position of being a consumer of your own code. When you write a test, you're effectively writing a client for the program or component you've just written. Writing that component's tests first gets you thinking about the design of the component's interface – how the component will be used – before you do the implementation.

The idea is you are more likely to design a good interface if you shift-left your experience of using that interface.

TDD might be better described as test-driven _design_. It is actually a process of using automated tests to design software in a series of small steps. TDD enforces iterative and incremental development.

TDD is most commonly used in bottom-up design processes, in which a system is built in a peacemeal fashion, component by component. However, it can also be incredibly effective in top-down design. Indeed, it can often be desirable to take a test-driven approach to tests of all levels: unit, integration, and system.

// TODO: The real objective is *self-testing code*. TDD is one way to achieve that objective, but the ends are more important than the means.
