= TS-12: Quality Assurance
:toc: macro
:toc-title: Contents

This technical standard defines the processes, practices, and culture through which software quality is assured.

Quality assurance (QA) is not a phase of development, nor is it the responsibility of a dedicated team. It is a continuous discipline that is woven into every stage of the software development lifecycle — from requirements analysis through design, implementation, testing (obviously), and deployment.

The goal of QA is not to find defects after they have been introduced, but to prevent them from being introduced in the first place. Detection is necessary, but prevention is more effective and less expensive. The practices described in this standard — code review, quality gates, metrics, and environment management — are the mechanisms by which prevention is operationalized.

This standard focuses on the _process_ of quality assurance: how quality is organized, what gates exist, how quality is measured, and how a culture of quality is sustained. For the specifics of testing, see *link:../008/README.adoc[TS-8: Functional Testing]* and *link:../009/README.adoc[TS-9: Performance (Non-Functional) Testing]*. For release strategies including canary testing and staged rollouts, which are also important quality control practices, see *link:../004/README.adoc[TS-4: Releasing]*.

toc::[]

include::./01-quality-culture.adoc[leveloffset=+1]
include::./02-definition-of-done.adoc[leveloffset=+1]
include::./03-code-review.adoc[leveloffset=+1]
include::./04-quality-gates.adoc[leveloffset=+1]
include::./05-testing-environments.adoc[leveloffset=+1]
include::./06-quality-metrics.adoc[leveloffset=+1]
