= References

* Allegro Tech (2024).
  {link-allegro-2024}[_Ten Years of Microservices at Allegro: Key Lessons Learned_].

* Browne, J (2009).
  {link-browne-2009}[_Brewer's CAP Theorem_].

* Elhage, N.
  {link-elhage}[_Computers Can Be Understood_].

* Fowler, M (2004).
  {link-fowler-2004}[_StranglerFigApplication_].

* Istio.
  {link-istio}[_The Istio Service Mesh_].

* Ongaro, D and Ousterhout, J (2014).
  {link-ongaro-ousterhout-2014}[_In Search of an Understandable Consensus Algorithm_].

* Orner, D (2021).
  {link-orner-2021}[_Why SOLID Principles Are Still the Foundation for Modern Software Architecture_].

* PostHog (2024).
  {link-posthog-2024}[_How We Choose Technologies_].

* Richardson, C.
  {link-richardson-outbox}[_Pattern: Transactional Outbox_].

* Richardson, C.
  {link-richardson-saga}[_Pattern: Saga_].

* ScyllaDB.
  {link-scylladb-pacelc}[_PACELC Theorem_].

* Stripe.
  {link-stripe-idempotency}[_Designing Robust and Predictable APIs with Idempotency_].

* Wikipedia.
  {link-wikipedia-fallacies}[_Fallacies of Distributed Computing_].
