= Risk register

Newly identified threats SHOULD be added to the application's risk register.
Risk registers contain data concerning risk information, and how risks have
evolved over time.

A risk register should take the form of a spreadsheet or other tabular data
format. The following columns/fields are RECOMMENDED as a starting point:

* *Reference number*, eg. "TA1". You might adopt different codes depending on
  the context in which the risk was identified, eg. TA for the Threat Assessment
  table, AS for AppSec, etc.

* *Threat name*, eg. "Workstation user spoofing". Used for metrics. Short but
  descriptive and unique. Must describe what process in the product is impacted or
  vulnerable.

* *Threat type*, eg. "Spoofing". Use STRIDE, OWASP, NIST, or other vulnerability
  databases and frameworks. Use consistent categorization.

* *Threat details*, eg. "Windows user account hash is captured and replayed by
  attacker". Include where the threat can occur, eg. if only certain endpoints
  or users are susceptible. This can be wordy, if necessary – better to be
  specific.

* *Risk probability*, eg. "Probable", "Likely", "Possible", "Unlikely", or
  "Rare".

* *Risk impact*, eg. "Catastrophic", "Critical", "Severe", "Marginal", or
  "Negligible".

* *Risk severity*, eg. "Critical", "High", "Medium", or "Low". This is an
  overall rating based on a combination fo the probability of the threat being
  realized and the impact of a successful attack.

* *Mitigation steps*, eg. "Workstation accounts require MFA". More detailed
  step-by-step instructions can be provided in a runbook or alert response table.

* *Mitigation status*, eg. "Pending", "In progress", "Completed", or deadline
  for completion.

* *Residual risk*, eg. "Critical", "High", "Medium", or "Low". The risk that
  remains after applying the mitigation steps is the residual risk.

* *Countermeasures.* Additional countermeasures to further attempt to mitigate
  the risk. When there is no residual risk, this column can be marked N/A. Note
  the date when the countermeasures were applied, or whether pending or in
  progress.

* *Date reviewed.* The date the status of the threat was last reviewed.
