= References

* Atlassian.
  {link-atlassian-design}[_Atlassian Design System_].

* BBC.
  {link-bbc-error-messages}[_How to Write Useful Error Messages_].

* CFPB.
  {link-cfpb-design-system}[_CFPB Design System_].

* GOV.UK.
  {link-gov-uk-design-principles}[_Government Design Principles_].

* IBM.
  {link-ibm-design-language}[_IBM Design Language_], "Build Bonds".

* Jacquez, K.
  {link-jacquez-google-design}[_Code is a Design Material_].

* Laws of UX.
  {link-laws-of-ux}[_Laws of UX_].

* Lynch, K, adapted by Web Style Guide.
  {link-webstyleguide-interface}[_Interface Design_].

* Nelhage, N (2021).
  {link-nelhage-2021}[_Reflections on Software Performance_].

* Nielsen, J (1994).
  {link-nielsen-1994}[_10 Usability Heuristics for User Interface Design_].

* Postel, J (1980).
  {link-postel-1980}[_RFC 761: DoD Standard Transmission Control Protocol_].

* U.S. General Services Administration.
  {link-digital-gov-usability}[_Usability_].

* U.S. General Services Administration.
  {link-usability-gov}[_Usability.gov_].

* Web Style Guide.
  {link-webstyleguide-typography}[_Typography_].
