= Code blocks

A code block is written using the following syntax.

```
[source,<language>]
----
text
  text
----
```

The `<language>` is optional. Example:

```
[source,bash]
----
subscription-manager repos --enable rhel-server-rhscl-7-rpms
----
```

It is RECOMMENDED to write "plaintext" as the language attribute, for code
examples that do not belong to any particular language. This will disable syntax
highlighting in the code block when rendered.

For shell examples, you need to distinguish between `console` and `bash` as the
source language:

* Use `console` if a prompt is included in the code snippet. Any of the
  characters `>`, `%`, `$`, and `#` may be used for the prompt. Prompts such as
  `[test@ubuntu~]$` may also be supported by some rendering tools. Syntax
  highlighting will be applied only to the commands written after the prompt.

* Use `bash` for standalone shell commands and scripts.

For conventions on formatting placeholders and CLI prompts within code blocks,
see *xref:026.adoc[TS-26: Technical Writing Style Guide]*.
