= Completeness

The quality of completeness is defined here as a system that provides all of the important functions that its target users need or want.

All software – but especially web-based software-as-a-service and other continuously-delivered systems – is perpetual work-in-progress. Modern software systems are continuously evolving, responding to ever-changing requirements. Software can never be "complete", in this sense.

Therefore, rather than aiming for completeness, it is better to target a small but critical subset of functionality for the first release – a minimal viable product (MVP). From that baseline the system's capabilities can be incremented, and its design iterated, driven by user feedback.

This is consistent with Richard P Gabriel's principle of https://dreamsongs.com/WorseIsBetter.html[worse-is-better]. This design philosophy states that it is better to start with a minimal creation that solves the customer's core problem, while leaving rough edges that will require refinement in the future.

The concept of worse-is-better originated in a famous talk by Gabriel at the 1989 European Conference on the Practical Applications of Lisp. In that talk, Gabriel described two contrasting software design philosophies:

* The MIT/Stanford approach (the "right thing"): Prioritizes correctness, consistency, completeness, and simplicity, with a strong emphasis on doing things properly, even if doing so adds complexity.

* The New Jersey style ("worse-is-better"): Emphasizes simplicity in implementation over simplicity of the interface, and tolerates some inconsistencies and incompleteness if that makes the system easier to build and maintain.

In the talk, Gabriel suggested that Unix and C were examples of the worse-is-better design philosophy. These were not superior technologies from a technical perspective, Gabriel argued, but nonetheless they were outperforming (and outliving) more elegant but more complex systems like Lisp ("the right thing").

This approach of starting simple and iterating based on feedback is best achieved through iterative and incremental development. This is a process model in which software is built through repeated cycles of development, with each cycle delivering small, working incremental changes. This process enables short feedback loops with real users, allowing requirements to emerge and the design to evolve – making the software easy to change in response to what is actually needed.

// TODO: Explain why iterative and incremental development is important. It's because it is notoriously difficult to understand up-front what users will actually need. The only way to find that out is to put working software in their hands, and iterate based on their feedback.

The idea of incremental development of software is analogous to https://www.patternlanguage.com/ca/ca.html[Christopher Alexander's] piecemeal growth philosophy in urban design. Architecture that strives for functional completion and technical perfection from the start is often less adaptable, and therefore less effective at meeting the needs of its human occupants over the long term, than architecture that prioritizes simplicity and that tolerates some imperfection.
