= TS-2: Software Design Qualities
:toc: macro
:toc-title: Contents

This technical standard establishes nine core qualities for evaluating software design. In no particular order, these qualities are:

* *Completeness*: +
  Whether a software system provides all the functions its users need.

* *Correctness*: +
  A system's ability to maintain valid, consistent state.

* *Performance*: +
  How well a system operates within specified constraints.

* *Reliability*: +
  A system's ability to handle and recover from failures of all kinds.

* *Experience*: +
  How a system is perceived by its users.

* *Habitability*: +
  How easy a system is for developers to maintain and evolve.

* *Cohesiveness*: +
  To what degree a system's design forms a unified, consistent whole.

* *Changeability*: +
  The ease with which software can be adapted to changing requirements.

* *Simplicity*: +
  How well a system minimizes unnecessary complexity in both its interface and implementation.

// TODO: Add *coupling* as a tenth quality. Perhaps this is key to simplicity, so it comes last?

These software design qualities are universal. They have an impact on every abstraction level within a solution's architecture, and they are relevant to all types of software – whatever the runtime environment, whatever the programming language, and whether the system is distributed or single-node.

No priority should be assumed from the order in which these qualities are presented. Their relative importance will differ between business domains and architectural styles. But _all_ these qualities are of importance in _every_ software system to some degree.

It's best not to view these qualities as being mutually exclusive. In fact, there's much overlap between them and they reinforce one another. For example, the design constraints necessary to make a system fast and responsive tend also to result in system designs that are simple, easy to change, and fault-tolerant.

Taken as a whole, these quality attributes form a cohesive software design philosophy.

****
See also Richard P Gabriel's essay, https://dreamsongs.com/RiseOfWorseIsBetter.html[The Rise of Worse is Better], for a thoughtful exploration of the relative importance of some of these qualities in software design.
****

This technical standard also touches upon the software design _process_ itself. Topics such as iterative and incremental development, feedback loops, and domain modeling are mentioned. After all, these are important methods and tools to help us achieve our design goals. But the focus of this technical standard is the end result – what good software design looks like – not the means of getting there.

Related standards include *link:../005/README.adoc[TS-5: Application Architecture]*, which covers architectural patterns for single-node applications; and *link:../007/README.adoc[TS-7: Code Design]*, which covers low-level concerns such as code formatting and exception handling.

toc::[]

include::./01-completeness.adoc[leveloffset=+1]
include::./02-correctness.adoc[leveloffset=+1]
include::./03-performance.adoc[leveloffset=+1]
include::./04-reliability.adoc[leveloffset=+1]
include::./05-experience.adoc[leveloffset=+1]
include::./06-habitability.adoc[leveloffset=+1]
include::./07-cohesiveness.adoc[leveloffset=+1]
include::./08-changeability.adoc[leveloffset=+1]
include::./09-simplicity.adoc[leveloffset=+1]
