= Bug

Bugs are defects, errors, or regressions in the expected behavior of a computer program, either in terms of its
functionality and behaviors, or its non-functional attributes such as latency or availability. The defects are
discovered in production or a production-like environment, or in a production-grade branch.

Bugs are caused by changes in a program's business logic or its configuration, causing the system to behave in
unintended ways, to produce incorrect results, or to otherwise not work as expected.

Every identified bug MUST be logged in the appropriate issue tracker. There SHOULD be one issue per bug, unless multiple
bugs are thought likely to have the same root cause, in which case the bug reports MAY be merged into a single issue.

Bug issues SHOULD capture step-by-step instructions to reproduce the error, followed by the expected versus actual
outcomes of following those steps.

If relevant, bug issues SHOULD also record the runtime environments in which the errors were discovered. In the context
of web applications, the runtime environment is the web browser and the underlying operating system on which the browser
is installed. For errors seen in remote services, it may be useful to capture the client devices used to access those
services.

Bug tickets should also capture any other relevant materials, such as screenshots or the stderr output, and any other
context that may help the development and operations teams to replicate the error.

.Bug template
[source,markdown]
----
---
name: Bug
about: Report an error or regression in an expected behavior
title: ""
labels: BUG
assignees: ""
---

## Description

Write a concise description of the bug.

## Steps to reproduce

1. Go to …
2. Click on …
3. Scroll down to …

## Outcomes

- **Expected**: …

- **Actual**: …

## Environment

Please describe the environments in which you installed the software, or the client devices from which you accessed it. Example:

- **OS**: [eg. Windows 10, macOS Sequoia]
- **Browser**: [eg. Chrome, Firefox]
- **Version**: [eg. 89]

## Additional artifacts

Please attach screenshots, stderr output, or other artifacts that may help the project's maintainers to diagnose the issue.

----
