= Incident

An incident is an unplanned event that leads to a disruption to the normal
operations of a system in production, or a degradation in the system's
performance. Incidents include outages, security breaches, and data loss. Any
event that causes a production system to become unavailable, to degrade in its
performance, or to otherwise not function as expected, should be recorded as an
incident.

Special types of issues MUST be used to track the analysis and resolution of
incidents. Ideally, these tasks SHOULD be added to the issue trackers in an
automated way.

This issue type is relevant only to software services, and not to
software-as-a-product, shrinkwrap software, libraries, or other such software
components.

.Incident template
[source,markdown]
----
---
name: Incident
about: Log an event that unexpectedly disrupted or degraded production services
title: ""
labels: INCIDENT
assignees: ""
---

## Description

Write a short description of this incident. Include the date and time of the incident, what happened, and how it was discovered.

## Impact

List the systems, applications, or services affected by the incident. Describe how users were impacted, eg. downtime, latency, or data loss.

## Timeline

Record when the incident was first detected, how it was discovered (eg. through monitoring tools or user reports), and write a chronology of actions taken to address the incident.

## Analysis

Write an analysis of the cause of the incident. Include other contributing factors, besides the root cause.

## Resolution

Describe the immediate fixes applied to resolve the incident.

## Communication

List the stakeholders who were informed about the incident, including a summary of communications sent to users or internal teams (eg. status dashboard updates, email notifications).

## Mitigation strategies

Summarize the actions to be taken following the post-mortem analysis. These should be focused on long-term mitigation strategies to prevent similar incidents from recurring in the future, rather than the immediate fixes applied to resolve this particular incident.

## Additional Information

Add any additional information or context that may be relevant. Add links to any relevant documentation or reports related to this incident.

----
