= Maintenance

Maintenance work covers any general housekeeping and _ad hoc_ chores that are necessary in the upkeep of a software
system.

This category of work includes the routine upgrading of dependencies and changes to the configuration of tools and
infrastructure. It also includes improvements made to artifacts such as documentation, test scripts, and requirements
specifications – anything except source code and configuration from which executable programs are compiled.

In some cases maintenance work may involve the refactoring of source code and configuration, for example to maintain
compatibility with breaking API changes in updated dependencies. If this is the case, this work might be better logged
as a refactoring task.

.Maintenance template
[source,markdown]
----
---
name: Maintenance
about: Plan a routine housekeeping task
title: ""
labels: MAINTENANCE
assignees: ""
---

## Description

Write a concise description of the maintenance work that needs to be done.

## Due

What's the deadline for this, if the work needs to be completed by a specific date, eg. before the EOL of a dependency?

## Steps to complete

1. …
2. …
3. …

## Additional notes

Add any additional information or context that might help to complete this task.

----
