= Execution and permissions

Scripts that are intended to be executed directly MUST be executable. This is achieved by setting the executable bit on the script file: `chmod +x <script-name>`.

Libraries – shell scripts that are intended only to be sourced by other scripts – SHOULD NOT be executable. This is achieved by removing the executable bit on the script file: `chmod -x <script-name>`.

SUID and SGID MUST NOT be applied to _any_ shell scripts, whether or not those scripts are executed directly. These permissions open up potential vulnerabilities. Programs with SUID (Set User ID) are run with the elevated permissions of the file owner, so increasing risk if the scripts are exploitable. And SGID (Set Group ID), when applied to a file, executes the file with the group permissions of the file rather than the user's current group. SGID is used to give group access to executables, but it can lead to unintended access if those groups are not managed carefully.

[source,sh]
----
# In the below output, the `s` in the `rws` bit shows that
# SUID is set on the user (owner) permission.
$ ls -l /usr/bin/passwd
-rwsr-xr-x 1 root root ...

# In the below output, the `s` in the group section (`rws`)
# shows that SGID is set on the directory.
$ ls -ld shared_folder
drwxrwsr-x 2 alice devteam ...
----

Use the following commands to unset SUID and SGID from shell scripts:

[source,sh]
----
# Remove SUID.
chmod u-s filename

# Remove SGID.
chmod g-s filename
----
