= Comments

In higher-level programming languages, the higher abstractions allow programmers
to express their design through modules, function and object names, data
structures, and other constructs. Instead of relying on comments to explain the
code, it is considered best practice to try to design the code in a way that it
clearly articulates _what_ it does, without additional annotations. Therefore,
in higher-level programming languages, inline comments tend to be used quite
sparingly, used to explain only the most complex algorithms, or why certain
design patterns where chosen over more obvious ones, and so on.

Lower-level languages, like shells and other scripting languages, provide fewer
opportunities to develop self-explanatory code. Indeed, the syntax of
lower-level languages can often be cryptic and non-intuitive.

For this reason, it is strongly RECOMMENDED that shell scripts be liberally
commented. Use comments to express in plain English things that are not obvious
from the code itself. This is especially important for complex logic, unusual
syntax, and other non-obvious constructs.

For shell scripts, it is okay for comments to describe _what_ the code does.
This is especially useful to draw attention to the most important bits of
business logic. Even for experienced shell programmers, it will often be quicker
to read through the comments, rather than read through the code itself, to
understand what the code does and how it works.

Remember, *the purpose of comments is to reduce cognitive overhead*. Whatever
the language or level of abstraction, add comments where they make things easier
to understand, or where you want to communicate important information that
cannot be ascertained from the code alone. Remove comments that are superfluous,
redundant, or that do not add any tangible value.

If in doubt: leave a comment!

== File-level comments

All shell files SHOULD start – after the shebang and any `set` options – with
one or more contiguous comment lines that provide an overview of the contents
and purpose of the script.

The format of this file-level comment block SHOULD be based on the template
below, but may vary between projects as appropriate.

For publicly-distributed libraries, or components thereof, it is RECOMMENDED to
include copyright, license, and support notices. For scripts that are intended
to be executed directly it is RECOMMENDED to include brief usage documentation.
And for all shell scripts it is RECOMMENDED to list all dependencies – any
commands or programs that the script calls but that are not built-in to the
shell.

[source,sh]
----
#!/usr/bin/env sh

set -eu

#
# File description here.
#
# Copyright: 2025 John Doe
# License: MIT
# Support: https://github.com/team/project/issues
#
# Usage:
#   ./backup.sh [source] [destination]
#
# Dependencies:
# - <dep1>
# - <dep2>
# - <dep3>
#
----

== Function comments

All functions SHOULD be commented - regardless of their length and complexity.

Function comments SHOULD contain:

- A description of the function.
- A list of global variables used (whether or not they are created or modified).
- Arguments taken.
- Outputs to `stdout` and `stderr`.
- Returned values (ie. exit statuses).

The purpose of function comments is to make it easier for other programmers to
use your functions. They should be able to do this by reading simple API
documentation, written in English in a consistent structured format, rather than
needing to reverse engineer the code in their heads.

.Template
[source,sh]
----
# function_name - <Function description.>
#
# <Optional longer description.>
#
# Usage:
#   $ my_func <arg1> <arg2> ...
#
# Globals:
#   $<VAR> - <Description of the global variable.>
#   $<VAR> - <Description of the global variable.>
#
# Arguments:
#   $1 - <Parameter description.>
#   $2 - <Parameter description.>
#
# Output:
#   stdout - <Description of the output to stdout.>
#   stderr - <Description of the output to stderr.>
#
# Returns:
#   1 - <Description required for non-void and non-zero return values (error conditions).>
#
my_func() {
  # ...
}
----

.Example
[source,sh]
----
# print_success - Print notification of a successful operation.
#
# Globals:
#   $BOLD - ANSI escape code for bold text.
#   $GREEN - ANSI escape code for green text.
#   $RESET - ANSI escape code to reset text formatting.
#
# Arguments:
#   $1 - Message to print.
#
# Output:
#   stdout - Formatted success message.
#
print_success() {
  printf '%s%s[SUCCESS]%s %s\n' "${BOLD}" "${GREEN}" "${RESET}" "$1"
}
----

The function description – at the top of a function's comment block – MUST be
clear about any *side effects* of calling the function that might take a
programmer by surprise. Examples of side effects that SHOULD be documented
include:

* Changes to the current working directory.
* Changes to the filesystem (eg. create directories, move files, etc.).
* Exiting the process (`exit`).

However, although printing output to `stdout` and `stderr` is a class of side
effect, this is normal behavior for shell functions, so you don't need to draw
the user's attention to it. Documenting this behavior in the `Outputs:` block is
adequate.

== TODOs

`TODO` comments MAY be included in shell scripts to draw attention to areas that
require further development, review, or refactoring.

Use the following convention for TODO comments.

----
# TODO: Short description. [#34]
----

The square brackets on the end are OPTIONAL; they reference an issue number in
the project's task tracker, if applicable.

If you intend to implement the fix or improvement yourself, you MAY include your
unique identifier in brackets adjoining the `TODO` keyword, as below. Use a
consistent identifier, so you can easily search for your personal TODOs across a
codebase. Your unique identifier may be your email address, GitHub username,
etc.

----
# TODO(username): Short description. [#34]
----

// TODO: Move this to "code design".

[TIP]
======
IDE extensions such as
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree[Todo Tree]
can help you to manage code TODOs.
======
