= Determining value

Judgment about what documentation to create and maintain, and what not to, is usually made by the maintainers who are closest to the code. This happens to be the audience that is least likely to need the documentation.

This is why software developers habitually undervalue documentation. Indeed, the more senior the engineer, and the more experience they have with a particular codebase, the more likely they are to neglect important documentation artifacts. After all, the more fluent you are at reading source code — which is the source-of-truth for what a system does — the less value you will place on the effort involved in maintaining separate documentation that covers much the same ground.

It is true that not everything needs a separate document. Much information can be communicated through *self-documenting code*: clear naming, small functions, obvious hierarchical structure, good code comments, type signatures, data schema, and tests. But, no matter how well a codebase achieves that noble goal, there will always be questions that cannot be answered by reading source code. And even where questions can be answered that way, it will often be quicker and less error-prone to find the answers by reading distilled information in other artifacts and formats, such as diagrams.

There's a good test to determine whether a new unit of documentation would be valuable enough to justify its cost. The test is to ask a maintainer a question about the system. If they cannot answer it quickly, by briefly looking at the source code if they don't already know the answer, then documenting the answer will probably be worthwhile. The more frequently the question is asked, the more valuable the documentation will be. The same test can be adapted to user-oriented documentation.
