= Determining value

Judgment about what documentation to create and maintain, and what not to, is usually made by the maintainers who are closest to the code. This so happens to be the audience that is least likely to need the documentation.

This is why software developers habitually undervalue documentation. Indeed, the more senior the engineer, and the more experience they have with a particular codebase, the more likely they are to neglect important documentation artifacts. The more fluent you are at reading source code — which is the source of truth for what a system does — the less value you will place on the effort involved in maintaining separate documentation that covers much the same ground.

It is true that not everything needs a separate document. Much information can be communicated through *self-documenting code*: clear naming, small functions, obvious hierarchical structure, good code comments, type signatures, data schemas, and tests. But, no matter how well a codebase achieves that noble goal, there will always be questions that cannot be answered by reading source code. And even where questions can be answered that way, it will often be quicker and less error-prone to find the answers by reading distilled information in other artifacts and formats, such as diagrams.

And, of course, not all audiences can read source code.

There's a good test to determine whether a new unit of documentation would be valuable enough to justify its cost. The test is to ask a relevant stakeholder — a maintainer, a user, or support staff, say — a question about the system that they ought to know the answer to. If they cannot answer it, and if they can't quickly find the answer for themselves, then documenting the answer will probably be worthwhile. The more frequently the question is asked by the relevant audience members, the more valuable the documentation will be.

Choosing what documentation to maintain then becomes a matter of asking the right questions. Those questions can uncovered from multiple sources. The classic source is *code review*. If a reviewer cannot answer their own question, you have a gap in your documentation. If the question keeps recurring in code review, you'll get a good return on investing in filling that gap.

The *onboarding* process is another excellent opportunity to patch gaps in documentation. Capture the questions asked by newcomers, and add them to your product backlog. *Support channels*, such as help desks and issue trackers, are another source of gaps in consumer-oriented documentation. Every customer interaction is a signal for potential gaps to close.

The general principle is to treat recurring questions as defects in your documentation, and to log those defects for resolution, and to prioritize them by their value, just as you would handle a bug or feature request.
