= Publications

The documentation that we embed within, or maintain directly alongside, the code is the _source_ content for the documentation that we _publish_.

A single unit of source documentation may be published in multiple output formats, such as API reference guides, man pages, `--help` output, or online tutorials.

For each type of documentation, there SHOULD be a single authoritative source from which all publications are generated.

Whatever the format, published documentation SHOULD have the following characteristics.

* *Discoverable.* Published docs SHOULD funnel users though all the likely pathways they might take to find the information they need, including search, navigation menus and indexes, cross-references from related content, and links from the code itself, such as error messages and `--help` output.

* *Addressable.* Provide addresses that link directly to content at a granular level, so that readers can bookmark, share, and reference specific sections. The more granular and easier to access, the better.

* *Cumulative.* Order content so prerequisite concepts come first. A reader who arrives with partial knowledge and begins reading partway through should be able to rewind to earlier content to fill gaps, eg. to gain knowledge of technical terms that appear in the documentation.

* *Complete.* Within each publication, documentation content SHOULD NOT be truncated from its source, or otherwise made less than fully available.

* *Accessible.* Published documentation, especially that for consumers, MUST be accessible to readers through assistive technologies such as screen readers, as well as readers who navigate by keyboard or who need magnification or high contrast. This means using proper semantic market, including alternative text descriptions for all graphics, not using color along to convey meaning, and so on.

* *Beautiful.* Visual style should be intentional and aesthetically pleasing. Even text-only documentation has visual style in its spacing and capitalization. Aesthetics are not important to every reader, but some will struggle to find comfort in documentation that ignores them.
