= Process artifacts

Most forms of documentation SHOULD be descriptive rather the prescriptive. They should describe the current state of the software, not future aspirations or intentions for it. For this reason, to stay accurate, most documentation SHOULD _follow_ implementation rather than _precede_ it. Documentation written before implementation quickly drifts from reality as plans, designs, and implementations naturally evolve.

However, there are plenty of valid exceptions to this rule. Indeed, there are whole categories of technical documentation where the docs are written (at least in draft form) ahead of the code. Examples include proposals for changes to software requirements specifications, architectural decision records (ADRs), requests for comments (RFCs), and design docs. What all these types of documentation have in common is they are concerned more with the _process_ of designing, developing, maintaining, and operating software, rather than with _describing_ the software itself.

These process artifacts MUST be clearly separated from the system documentation, preferably in entirely different locations — eg. their own repositories, rather than nested within code repositories.
