= Shebang (`#!`)

The first line of a Bash file MUST be the shebang (`#!`, also known as a hashbang). This indicates to the shell which
interpreter to use. The classic Bash shebang is:

----
#!/bin/bash
----

But the env-style shebang is RECOMMENDED:

----
#!/usr/bin/env bash
----

The difference between the two is that the classic shebang bets everything on one path, while the env shebang looks for
the Bash binary in more places, and thus the script has a greater chance of being successfully run across different
environments. The trade-off is ever-so-slightly slower startup time, as the PATH environment variable needs to be
searched to find the Bash binary.

[TIP]
======
If you're using the classic Bash shebang, and if you get an error similar to
"command not found" when running the script, then almost certainly the path to
the Bash interpreter is wrong for the current system. Use `whereis bash` or
`find ./ -name bash` to find the path to the `bash` executable. Some possible
locations include:

* `/bin/bash`
* `/sbin/bash`
* `/usr/local/bin/bash`
* `/usr/bin/bash`
* `/usr/sbin/bash`
* `/usr/local/sbin/bash`
======

If a script is written to be POSIX-compliant, use either of the following shebangs instead. This will trip the Bash
program to executing the script in POSIX-compliant mode, equivalent to passing the `--posix` option to `bash` on the
command line (which in turn is equivalent to using the `sh` command to run Bash in POSIX-compliant mode).

----
#!/bin/sh
#!/bin/env sh
----

Again, the second env-style shebang will have wider compatibility and is therefore RECOMMENDED.
