= Variables

In Bash, local variables can be used to scope data to the functions the
variables are declared in.

[source,bash]
----
hello="hello"

hello() {
  local hello="world"
  echo $hello # → "world"
}

echo $hello # → "hello" (not modified).
----

This syntax is Bash-specific and it is RECOMMENDED to use it for all variable
declarations within functions, so as not to unnecessarily pollute the global
namespace and to prevent unexpected overwrites of global variables. Pay
particular attention to declaring loop variables as local, too – this is a
common source of bugs:

[source,bash]
----
local i
for i in {1..5}; do
  echo $i
done
----

Where the `local` keyword is omitted, include a comment explaining why it is not
used. There will be many use cases where functions are designed to update global
variables – that's fine, just be sure to leave a comment to be explicit in your
intent.

Variable declaration and assignment MAY be on different lines, but try to always
initialize variables with meaningful default values.

[source,bash]
----
some_function() {
  local code=0
  # …
  code=2

  return ${code}
}
----
