= JSON Hyper-Schema

https://json-schema.org/specification/json-hyper-schema[JSON Hyper-Schema] is an extension to JSON Schema that adds properties to allow the embedding of hypermedia links in JSON documents. It builds on https://datatracker.ietf.org/doc/html/rfc6570[URI Templates (RFC 6570)] and other standards.

The main use case for JSON Hyper-Schema is to embed hypermedia controls in JSON documents that enable APIs to be navigated, and explored in a dynamic way (ie. without clients necessarily having initial knowledge of all available resources and endpoints).

The following example, taken from the specification, adds a single link:

[source,json]
----
{
  "type": "object",
  "properties": {
    "id": {
      "type": "number",
      "readOnly": true
    }
  },
  "links": [
    {
      "rel": "self",
      "href": "thing/{id}"
    }
  ]
}
----

JSON Hyper-Schema adds the `links` property, which must be an array of "link description objects" (LDO).

Any IANA-registered link relation type can be used to define the link relation type (`rel`). This defines the semantics of the link in terms of its relationship to the resource. The table below describes some of the most commonly used link relation types.

|===
|Type |Description

|`self`
|Identifies the resource itself.

|`next`/`prev`
|Indicates the next or previous resource in a sequence, eg. in a paginated list.

|`first`/`last`
|Refers to the first or last resource in a sequence.

|`up`
|Refers to a parent resource in a hierarchy of resources.
|===

It is RECOMMENDED to use a small subset of link relation types, and to use them consistently across all endpoints in a hypermedia API. You SHOULD NOT define custom relations, unless absolutely necessary when no standard ones fit the use case.

The following best practices also apply for JSON Hyper-Schema:

* Each response should contain minimal links, just enough for clients to navigate deeper.
* Do not expose an entire API graph in any single response, except for simple APIs composed of just a few endpoints.
* It is RECOMMENDED to always include "self" links to the current resource, wherever relevant.
* Use simple, minimalist URI templates, with only necessary path parameters (variables).
* Provide all required template variables in the response object.
* Use `templatePointers` to clearly map data to template variables.
* Use `targetSchema` to describe expected response formats.
* Use `targetHints` for media types and methods.
* Add `title` properties for human-readable link descriptions.
