= Code blocks

== Placeholders

Prefer to use angle brackets (`<>`) to encapsulate any placeholder text that is intended to be swapped for a value, such as a file name or a command line argument.

Use square brackets (`[]`) to indicate optional arguments.

For example:

[source,sh]
----
./run <script> [<script-args>]
----

== CLI commands

Do not prefix CLI commands with a dollar sign (`$`), as is common in many technical documents. This is because the dollar sign is not universally used to indicate a command prompt, and it can be confusing for readers who are not familiar with this convention.

In addition, some rendering systems will provide functionality for users to easily copy the content of code blocks, allowing the commands to be pasted directly into terminals. Inclusion of prompts invalidates the commands, making for a poor user experience.

[source,markdown]
----
```sh
git clone git@<hostname>:<group>/<project>.git
```
----

The exception to this rule is when documenting the output from CLI commands. In this case, including the prompt can help to clarify which lines are commands and which lines are output. Example:

----
$ heroku logs --help
display recent log output

USAGE
  $ heroku logs

OPTIONS
  -a, --app=app        (required) app to run command against
  -d, --dyno=dyno      only show output from this dyno type (such as "web" or "worker")
  -n, --num=num        number of lines to display
  -r, --remote=remote  git remote of app to use
  -s, --source=source  only show output from this source (such as "app" or "heroku")
  -t, --tail           continually stream logs
  --force-colors       force use of colors (even on non-tty output)

DESCRIPTION
  disable colors with --no-color, HEROKU_LOGS_COLOR=0, or HEROKU_COLOR=0

EXAMPLES
  $ heroku logs --app=my-app
  $ heroku logs --num=50
  $ heroku logs --dyno=web --app=my-app
  $ heroku logs --app=my-app --tail
----
