= TS-26: Technical Writing Style Guide
:toc: macro
:toc-title: Contents

// TODO

toc::[]


== Code blocks

=== Placeholders

Prefer to use angle brackets (`<>`) to encapsulate any placeholder text that is intended to be swapped for a value, such as a file name or a command line argument.

Use square brackets (`[]`) to indicate optional arguments.

For example:

[source,sh]
----
./run <script> [<script-args>]
----

=== CLI commands

Do not prefix CLI commands with a dollar sign (`$`), as is common in many technical documents. This is because the dollar sign is not universally used to indicate a command prompt, and it can be confusing for readers who are not familiar with this convention.

In addition, some rendering systems will provide functionality for users to easily copy the content of code blocks, allowing the commands to be pasted directly into terminals. Inclusion of prompts invalidates the commands, making for a poor user experience.

[source,markdown]
----
```sh
git clone git@<hostname>:<group>/<project>.git
```
----

The exception to this rule is when documenting the output from CLI commands. In this case, including the prompt can help to clarify which lines are commands and which lines are output. Example:

----
$ heroku logs --help
display recent log output

USAGE
  $ heroku logs

OPTIONS
  -a, --app=app        (required) app to run command against
  -d, --dyno=dyno      only show output from this dyno type (such as "web" or "worker")
  -n, --num=num        number of lines to display
  -r, --remote=remote  git remote of app to use
  -s, --source=source  only show output from this source (such as "app" or "heroku")
  -t, --tail           continually stream logs
  --force-colors       force use of colors (even on non-tty output)

DESCRIPTION
  disable colors with --no-color, HEROKU_LOGS_COLOR=0, or HEROKU_COLOR=0

EXAMPLES
  $ heroku logs --app=my-app
  $ heroku logs --num=50
  $ heroku logs --dyno=web --app=my-app
  $ heroku logs --app=my-app --tail
----

== Referencing

There are a number of conventions for including citations and reference lists within documents, such as Harvard, APA, MLA, Chicago, and Vancouver. Most conventions involve two parts:

1. A short inline citation within the text.
2. A full reference at the end of the text.

My preference is the Chicago style of placing an inline superscript number that cross-references a footnote or endnote. In hypermedia formats such as HTML, the inline citation is hyperlinked to its corresponding footnote, and vice versa, so readers can jump to the footnote and back again.

Where I want to reference works listed in a bibliography section at the end of the document, I will use the Harvard style for the inline citation. Example:

(Johnson, 2020)

The author names are written exactly as they appear in the reference list (see below).

I use the same formatting convention for references whether they appear in footnotes or bibliographies. My convention is a mix of the Chicago and Harvard styles. It places emphasis on the author and publication date:

[source,asciidoc]
----
<author> (<year>). _<title>_. <publication>
----

Example:

Johnson, M (2020). _The Future of Learning_. Horizon Press

When there are two authors, I write only their surnames:

Smith and Jones (2020). _Title of the work_. Publication

When there are three: "Smith, Jones, and Patel". When there are more than three authors, I will truncate to "Smith et al".

In hypermedia formats, the title may be hyperlinked. When printed, the full URL (including the https:// schema) should be appended to the end, after the publication. For academic journals it is common practice to include the issue number and page range of the source material. Example:

DeLorne and Fedler (2003). _Journalists' Hostility Toward Public Relations: An Historical Perspective_. Public Relations Review, volume 29, issue 2, pages 99-124. https://www.sciencedirect.com/science/article/abs/pii/S0363811103000195

For consistency, citations of press releases, news stories, and blog posts should follow the same format. However, as a general rule it is preferable to cite the organization or publisher as the author, even if the article has a byline. The following example is a reference for a company's annual report:

Cision (2016). _Inside PR 2026_. https://www.cision.com/resources/guides-and-reports/2026-inside-pr-report/

The following example is a reference to a news story published on the PR Week website. The article has a byline, giving the name of the journalist who wrote the article. But it is more appropriate to cite the name of the publisher, as that is a more accurate reflection of the authorship.

PR Week (2025). _Equiniti to acquire Notified from West Technology Group_. https://www.prweek.com/article/1910473/equiniti-acquire-notified-west-technology-group

''''

== References

* https://www.apstylebook.com/[The Associated Press Stylebook]
* https://education.economist.com/insights/what-to-read/writing-with-style[Writing with Style] – The Economist's style guide

A more extensive list of style guides is maintained on https://en.wikipedia.org/wiki/List_of_style_guides[Wikipedia].
