= References

* Allamaraju, S (2010). {link-allamaraju-cookbook}[_RESTful Web Services Cookbook_].

* Harmon, J. {link-harmon-api-standards}[_API Standards_].

* Internet Assigned Numbers Authority. {link-iana-link-relations}[_Link Relations_].

* Internet Engineering Task Force (2012). {link-ietf-rfc6585}[_Additional HTTP Status Codes_].

* Internet Engineering Task Force (2014). {link-ietf-rfc7231}[_Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content_].

* Internet Engineering Task Force (2014). {link-ietf-rfc7159}[_The JavaScript Object Notation (JSON) Data Interchange Format_].

* Internet Engineering Task Force (1998). {link-ietf-rfc2387}[_The MIME Multipart/Related Content-type_].

* Internet Engineering Task Force (2010). {link-ietf-rfc5789}[_PATCH Method for HTTP_].

* Internet Engineering Task Force (1998). {link-ietf-rfc2388}[_Returning Values from Forms: multipart/form-data_].

* Internet Engineering Task Force (2005). {link-ietf-rfc3986}[_Uniform Resource Identifier (URI): Generic Syntax_].

* Internet Engineering Task Force (2012). {link-ietf-rfc6570}[_URI Template_].

* Internet Engineering Task Force (2010). {link-ietf-rfc5988}[_Web Linking_].

* JSON.org. {link-json-org}[_Introducing JSON_].

* OpenAPI Initiative. {link-openapi-2}[_OpenAPI Specification v2.0_].

* Preston-Werner, T. {link-semver}[_Semantic Versioning 2.0.0_].

* SmartBear. {link-smartbear-api-design}[_API Design_].
