= TS-5: Application Architecture
:toc: macro
:toc-title: Contents

This technical standard sets out principles and best practices for designing and implementing standalone software applications.

An "application" is defined here as a software component that is deployed in a single operation, is usually maintained in a single repository, and is designed to perform a specific function or set of functions. Many applications will be designed to run in a single process (but there are plenty of applications that are designed to spawn multiple processes for performance reasons). An application may be a standalone executable, a library, or a service or microservice within a larger distributed system.

In client-server systems such as web applications, the client-side application may specialize in only the user interface, while the server-side application specializes in data processing, business logic, and state persistence. GUI applications tend to require a specialist architecture, which is outside of the scope of this technical standard. See *link:../023/README.adoc[TS-23: Web GUIs]* for guidance on designing client-side web applications.

Related technical standards include *link:../010/README.adoc[TS-10: Software Design Principles]*, which describes general software architectural design best practices and standards; and *link:../013/README.adoc[TS-13: Code Design]*, which covers concerns such as code formatting and low-level design patterns.

See also *link:../053/README.adoc[TS-53: Caching]*, which is an important consideration in application architecture.

toc::[]

include::./horizontal-layers.adoc[leveloffset=+1]
include::./vertical-slices.adoc[leveloffset=+1]
include::./feature-flags.adoc[leveloffset=+1]
include::./dependencies.adoc[leveloffset=+1]
include::./frameworks.adoc[leveloffset=+1]
include::./services.adoc[leveloffset=+1]
