= Modules

Standard ECMAScript modules (ESM) MUST be used exclusively for all code. Authors
MUST NOT write CommonJS modules – Node's default and proprietary module system –
or any other type of non-standard module system such as AMD or UMD. This means
using `import` and `export` exclusively for all module loading and exporting,
rather than `require` and `module.exports`.

[NOTE]
======
All JavaScript files MUST use the `.js` file extension, and not the `.mjs`
extension. TypeScript files MUST use the `.ts` file extension.
======

[source,javascript]
----
// ES MODULES

// Import specific components into an ES module.
import { AssertionError, RuntimeError } from '@package/err'

// Or import all components from package into an ES module.
import * as err from '@package/err'
----

[source,javascript]
----
// COMMONJS SCRIPTS

// Import specific components into a CJS script.
const { AssertionError, RuntimeError } = require('@package/err')

// Or import all components from a package into a CJS script.
const err = require('@package/err')
----

There MAY be rare exceptions where CommonJS modules are necessary. For example,
some testing frameworks and other development tools still require configuration
files in the CommonJS format. In these cases, the `.cjs` file extension MUST be
used, to distinguish these files from standard ECMAScript modules (`.js`).

Although all major runtime environments, including browsers and server-side
runtimes, now support ECMAScript modules, sometimes it may be necessary to
transform ESM code before it can be consumed by other tools or environments. A
static transcompiler like https://babeljs.io/[Babel] or a runtime transcompiler
like https://www.npmjs.com/package/esm[esm] can be used for this purpose. To
target web browsers, further "bundling" may be beneficial, to reduce
distributable builds. An ESM-compatible bundler like
https://rollupjs.org/guide/en/[Rollup] or https://webpack.js.org/[Webpack 2]
may be used for this purpose.

== Background

For many years in its early history, JavaScript did not have a native module
system. https://www.ecma-international.org/[Ecma International] standardized
ECMAScript Modules – aka ES Modules, ESM, or Harmony Modules – in the 6th
edition of ECMAScript, finalized in 2015.

Within a couple of years, support for ECMAScript Modules started turning up in
mainstream web browsers (via `<script type="module">`). But it took a few more
years for the Node runtime to catch up. Node's implementation of ES Modules was
not marked as "stable" until the following releases:

* https://github.com/nodejs/node/releases/tag/v12.22.0[v12.22.0] (30 March 2021).

* https://github.com/nodejs/node/releases/tag/v14.17.0[v14.17.0] (11 May 2021).

* https://github.com/nodejs/node/releases/tag/v15.3.0[v15.3.0] (24 November 2020).

We can now write code in standard JavaScript modules and run it directly in Node
without a build step or a runtime transcompiler. Node also supports
applications that mix-and-match ESM and CJS files, so existing applications can be
incrementally upgraded from CJS to ESM.

Legacy JavaScript _applications_ SHOULD be incrementally refactored to ESM, too,
for better future-proofing. _Libraries_ that are intended for use in applications
or runtime environments that require CJS modules MUST be distributed as hybrid
packages: a transcompiler such as Babel transforms the source from ESM to CJS,
and conditional exports (see <<Packages and tooling>>) make both module formats
available.

== Imports

A bare specifier is a file or folder name without a provided path. These are
often used to import package names, because it is easier to type a package name
than write out a full file path.

[source,javascript]
----
// A bare specifier. Notice how it's easier to import from `react`
// than from `../../node_modules/react/index.js`.
import React from 'react'

// This is not a bare specifier: the `./` means check the current
// directory for a `FooComponent.js` file.
import FooComponent from './FooComponent.js'
----

With ES6 modules you cannot import directories – this differs from CJS scripts.
You MUST specify the `index.js` file name:

[source,javascript]
----
import database from './database/index.js'
----

=== Internal imports

In large applications, it is not unusual to see imports of internal components
like this:

[source,javascript]
----
import { forIn } from '../../../../../utils/array'
----

It is neater to import internal components using paths relative to some base
root directory, such as `src`. Besides neatness, absolute paths for internal
imports give a unique, searchable path for every import instance of any given
module, making it easier to find everywhere a module is used.

For JavaScript applications, there are several solutions. Node has an
environment variable `NODE_PATH` that extends the locations where the runtime
looks for modules referenced via `require()` and `import`:

[source,json]
----
{
  "scripts": {
    "start": "NODE_PATH=src/ node main.js"
  }
}
----

Alternatively, transpilation or bundling tools like Webpack can be
https://webpack.js.org/configuration/resolve/#resolvealias[configured] to define
path aliases:

[source,json]
----
{
  "resolve": {
    "extensions": [".js", ".vue", ".json"],
    "alias": {
      "@": path.join(__dirname, "..", "src")
    }
  }
}
----

In TypeScript, this is easier still. TypeScript has a
https://www.typescriptlang.org/docs/handbook/module-resolution.html[path mapping]
option that maps arbitrary filesystem paths – anything that does not start with
`/` or `.` – to physical paths. Path maps are defined in `tsconfig` and resolved
automatically by the compiler:

[source,json]
----
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@app/utils/*": ["app/utils/*"],
      "@app/pipes/*": ["app/pipes/*"]
    }
  }
}
----

The path mappings are defined in the `paths` property, all relative to the
`baseUrl`:

[source,javascript]
----
import { forIn } from '@app/utils/array'
----

The RECOMMENDED convention for importing internal application modules is to use
the `~` path prefix. By using a different character entirely, it is easier to
distinguish between internal imports (`~`) and external ones (`@`): `~` always
resolves to `src/`, while `@` always resolves to `node_modules/`.

[source,javascript]
----
import { forIn } from '~utils/array'
----

This convention MUST be used only for in-house applications. It MUST NOT be used
within public libraries, where relative file paths MUST be used.

=== Including JSON

You do not need `JSON.parse` to read JSON files in Node.js; you can `require()`
them like any other JavaScript component:

[source,javascript]
----
let config = require('./config.json')
----

Be aware of side effects. `require()` caches the content of the loaded module or
file. When the same component is required a second time, Node loads it from the
cache rather than reading the filesystem again. This behavior can be undesirable
for some types of configuration file, such as test fixtures. The solution is to
load (using Node's `fs` module) and parse (using `JSON.parse()`) the file
directly, preferably in a non-blocking manner:

[source,javascript]
----
const fs = require('fs')

fs.readFile('./config.json', (err, data) => {
  if (err) throw err
  let config = JSON.parse(data)
  console.log(config)
})
----

Or synchronously, if you must:

[source,javascript]
----
const fs = require('fs')

let rawdata = fs.readFileSync('config.json')
let config = JSON.parse(rawdata)
console.log(config)
----

== Exports

=== Default versus named exports

ES modules support two types of export: named exports and default exports. A
module can have both:

[source,javascript]
----
export const A = 'A'
export default A
----

Default exports do not export any name (symbol) that can be easily associated
with the exported value. Named exports are all about having a name.

Use of default exports is generally considered bad practice. The JavaScript
language supports default exports only to provide easy interoperability with
legacy non-standard module conventions, notably Node's CommonJS API – `require()`
and `module.exports`. Default exports are intended only to provide an easy
upgrade path to the standard module format. New libraries and applications
SHOULD use named exports.

[source,javascript]
----
// Do not do this.
export default {
  propertyA: 'A',
  propertyB: 'B',
}

// Do this instead.
export const propertyA = 'A'
export const propertyB = 'B'
----

Named exports are preferred over default exports for the following reasons:

* Named exports MUST be imported with reference to the identifier they are
  exported as. This makes large-scale refactoring easier, because every
  component has a unique identifier wherever it is used, and typos are easier to
  spot.

* Named exports enable better "tree shaking" of unused exports, making compiled
  artifacts smaller. A single export object with multiple resources referenced
  via properties prohibits tree shaking.

* Named exports are more scalable: an existing module can be easily extended
  with additional exports.

* IDE tooling can more accurately cross-reference components in modules that
  have multiple named exports, and is less reliable where a module exports a
  default object with multiple properties.

Mixing default and named exports in the same module is bad practice, though it
is permitted by the specification. It also makes it difficult to offer CJS
versions of ESM modules, because CJS modules only have a single `module.exports`
object.

=== Named exports

Named exports allow the name of a class, function, or variable to be transferred
into consuming scripts. In consuming files, imports cannot be any randomly
assigned identifier and MUST match the name in the source module:

[source,javascript]
----
// CommonJS
exports.FooBar = class FooBar {}
const FooBar = require('./foobar').FooBar

// ES
export class FooBar {}
import { FooBar } from './foobar.js'
----

A rare problem with named imports is conflicting identifiers – when a consuming
script imports two unrelated dependencies that happen to have the same name. ES
provides aliasing for this:

[source,javascript]
----
import { speak as cowSpeak } from './cow.js'
import { speak as goatSpeak } from './goat.js'
----

Named imports SHOULD NOT be aliased except to resolve identifier conflicts. At
least with aliases you still reference the imports' canonical names, and the
decision to rename the import is made explicit.

=== Exporting functions

Where a function does not need its `this` binding to be rebindable by consumers,
or to be used as a constructor, use a function expression assigned to `const`:

[source,javascript]
----
const fooBar = () => {
  // ...
}

export { fooBar }
----

Use a function declaration only where consumers need the flexibility of changing
the call context (by dynamic binding of `this`) or where the function is meant to
be used as a constructor:

[source,javascript]
----
function fooBar () {
  // ...
}

export { fooBar }
----

== CommonJS

At the time of Node's first release in 2009, JavaScript did not have a native
module system, so Node adopted https://wiki.commonjs.org/wiki/Modules[CommonJS
Modules] (CJS) – a community-derived module system implemented as extensions to
JavaScript's standard API: the `require()` function and the `module.exports`
object (and its alias `exports`).

Although we SHOULD write all new JavaScript components with standard
`import`/`export` syntax, some use cases still require CommonJS files – for
example, some development tools still accept configuration files in the CommonJS
format only.

Node wraps the contents of `.js` files in a function, scoping local variables to
the file with only `exports`, `require`, and `module` provided as references:

[source,javascript]
----
(function (exports, require, module, __filename, __dirname) {
  // ./lib/<modulename>.js
})
----

The `module` variable is an object representing the module. You attach your
module's public API to its `exports` property. By default, `module.exports` is
an empty plain object that gets returned from `require()` when the module is
imported. The `exports` variable is just a reference to `module.exports`.

Be careful not to reassign `exports`, because doing so breaks the reference to
`module.exports`. This function will not be exported:

[source,javascript]
----
exports = function () {}
----

If you replace `module.exports` with a new object, function, or class, and you
still want to keep the `exports` shorthand, you must re-point `exports` to the
new object:

[source,javascript]
----
exports = module.exports = function () {}
----

The safest option is to always use `module.exports` and never its alias
`exports`.

== Module systems in Node

=== Toggling interpreters

Behind the scenes, Node has two JavaScript interpreters: its legacy interpreter
for CJS scripts and a newer one for ES modules. At runtime, Node toggles between
them depending on which module format it encounters in each file.

By default, Node interprets all `.js` files as CommonJS scripts. This default is
necessary for backwards compatibility: ES modules behave differently (they are
loaded asynchronously and are strict-mode compliant by default), so switching the
default would require extensive refactoring of existing libraries and
applications. It is the same reason modern web browsers continue to assume that
inline and imported scripts are non-ESM, requiring authors to opt in explicitly
via `type="module"`.

The easiest way to opt in to Node's ESM interpreter is to change a file's
extension from `.js` to `.mjs`. This is a non-standard extension, and many
development tools – notably TypeScript – do not recognize it. The explicit
toggle is therefore NOT RECOMMENDED.

The RECOMMENDED way to toggle Node's interpreter is to set the following property
in `package.json`:

[source,json]
----
{
  "type": "module"
}
----

With this in place, all `.js` files within the `package.json` directory and its
subdirectories run through the ESM interpreter. The property can be set on the
root manifest or on a directory-by-directory basis via nested `package.json`
files containing just `{ "type": "module" }`.

This toggles Node's default interpreter for `.js` files from CJS to ESM. You can
still mix-and-match: change the extension of CommonJS scripts to `.cjs`, and Node
toggles its interpreter back for those files only. This is the RECOMMENDED
methodology because:

* The standard `.js` extension indicates a standard ECMAScript module or
  script, while the non-standard `.cjs` extension indicates a non-standard
  CommonJS module.

* All `.js` files remain compatible with TypeScript applications.

* Code refactoring is minimised – a single configuration line toggles the
  interpreter.

* Migration from CJS to ESM is easier to manage.

=== Importing CJS into ESM

In Node, ESM files can `import` CJS files in the same way they import other
standard JavaScript modules. As a general rule, when you import CommonJS
components from ES modules, you SHOULD import the whole module using the default
import syntax, because CJS scripts have no concept of named exports:

[source,javascript]
----
import _ from 'lodash'
----

From Node v12.20.0 and v14.13.0, Node supports detection of CommonJS named
exports, so it is sometimes possible to import only specific exports from a
CommonJS-only package:

[source,javascript]
----
import { Router } from 'express'
----

This does not always work – for example, `import { shuffle } from 'lodash'`
fails. There is risk involved: a simple refactoring of a CJS script's source
could unwittingly break Node's automatic detection of its `module.exports`
properties. It is strongly RECOMMENDED to import whole CommonJS scripts, even at
the cost of importing more than you need. You can still use destructuring to
access specific properties:

[source,javascript]
----
import _ from './lodash'
const { shuffle } = _
----

Wherever possible, we MUST prefer to consume ESM over CJS. Where two competing
libraries provide the same features, prefer the ESM package; ESM enables
tree-shaking of unused imports from build artifacts.

=== Importing ESM into CJS

It is also possible to import modern ES modules into legacy CJS scripts. Because
ES modules are loaded asynchronously and Node's `require()` is synchronous, a
different API is needed: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports[dynamic imports], also known as `import()` expressions:

[source,javascript]
----
const foo = await import('./foo')
----

Within ES modules – where top-level `await` is supported – `await import()` can
exist at the top level. CJS scripts do not support top-level `await`, so
`await import()` MUST be wrapped in an `async` block:

[source,javascript]
----
(async () => {
  const foo = await import('./foo')
  // ...
})()
----

Or using promise chaining:

[source,javascript]
----
import('./foo')
  .then((foo) => {
    // ...
  })
  .catch((err) => {
    // ...
  })
----

Importing ES modules into CJS scripts gets messy. For this reason, it is
RECOMMENDED to upgrade CJS scripts to ESM only when all of the module's
dependencies are also readily available as (or easily upgraded to) ESM. The
migration from CJS to ESM SHOULD begin in low-level libraries and incrementally
work up to higher-level components and applications.

Many development tools are still written in CJS and have not been updated to
accept ES modules – for example, neither https://mochajs.org/#nodejs-native-esm-support[Mocha] nor https://eslint.org/docs/user-guide/configuring/configuration-files[ESLint] accept ESM configuration files. Most of the time workarounds exist (both Mocha and ESLint accept `.cjs` configuration files); in the worst case, a transcompiler or some bridging code is needed. Only a handful of legacy packages – such as https://www.npmjs.com/package/proxyquire[proxyquire] and https://www.npmjs.com/package/rewire[rewire], which monkey-patch `require()` for testing – cannot be made to work with ES modules at all; https://sinonjs.org/[Sinon], https://www.npmjs.com/package/testdouble[testdouble.js], and https://www.npmjs.com/package/rewiremock[rewiremock] offer alternatives that support both CJS and ESM.

== Module systems for the web

All major web browsers now implement the standard JavaScript module system via
`<script type="module">`. The same ESM conventions apply on the web as on the
server. Where the cost of many separate module requests outweighs the benefit,
modules MAY be bundled for delivery to the browser using an ESM-compatible
bundler.