= TS-36: ECMAScript (JavaScript/TypeScript)
:toc: macro
:toc-title: Contents

This technical standard covers coding conventions for ECMAScript-based languages
– JavaScript and TypeScript.

[quote]
____
Java is to JavaScript +
as Car is to Carpet.
____

toc::[]

include::./01-language-fundamentals.adoc[leveloffset=+1]
include::./02-syntax-and-style.adoc[leveloffset=+1]
include::./03-functions.adoc[leveloffset=+1]
include::./04-objects-and-classes.adoc[leveloffset=+1]
include::./05-modules.adoc[leveloffset=+1]
include::./06-packages-and-tooling.adoc[leveloffset=+1]
include::./07-dependency-management.adoc[leveloffset=+1]
include::./08-typescript.adoc[leveloffset=+1]
include::./09-asynchronous-programming.adoc[leveloffset=+1]
include::./10-functional-programming.adoc[leveloffset=+1]
include::./11-runtimes.adoc[leveloffset=+1]
include::./12-architecture-and-design.adoc[leveloffset=+1]
include::./13-quality-assurance.adoc[leveloffset=+1]
include::./14-barrel-files.adoc[leveloffset=+1]

''''

== References

* Airbnb (n.d.).
  https://github.com/airbnb/javascript[_Airbnb JavaScript Style Guide_].
  GitHub. — One of the most widely-cited JavaScript coding standards; see also
  the companion
  https://github.com/airbnb/javascript/tree/master/css-in-javascript[CSS-in-JavaScript Style Guide].

* Google (n.d.).
  https://google.github.io/styleguide/jsguide.html[_Google JavaScript Style Guide_].
  — Google's coding standards for JavaScript; see also the
  https://google.github.io/styleguide/javascriptguide.xml[pre-ES6 version].

* Waldron, R (n.d.). https://github.com/rwaldron/idiomatic.js[_Idiomatic.js_].
  GitHub. — A community set of best practices and coding conventions for
  JavaScript.

* Aboukhadijeh, F (n.d.). https://standardjs.com[_Standard JS_]. — An
  opinionated, semicolon-free JavaScript style with a linter and automatic
  code fixer.

* Geisendörfer, F (n.d.).
  https://github.com/felixge/node-style-guide[_Felix's Node Style Guide_].
  GitHub. — A Node.js coding style guide by Felix Geisendörfer.

* Sta. Cruz, R (n.d.). https://ricostacruz.com/rsjs/[_RSJS_]. — A "reasonable
  system for JavaScript structure" for non-SPA web applications.

* Adobe (n.d.).
  https://developer.adobe.com/commerce/php/coding-standards/js/[_Adobe JavaScript Coding Standard_].
  — In-house standard for Adobe Commerce and Magento.

* Platypi (n.d.).
  https://github.com/Platypi/style_typescript[_Platypi TypeScript Style Guide_].
  GitHub. — A corporate style guide for JavaScript and TypeScript.

* McDermott, R (n.d.).
  https://github.com/ryanmcdermott/clean-code-javascript[_clean-code-javascript_].
  GitHub. — Clean-code concepts adapted for JavaScript; see the
  https://github.com/labs42io/clean-code-typescript[TypeScript adaptation].

* Goldberg, Y (n.d.).
  https://github.com/goldbergyoni/nodebestpractices[_Node.js Best Practices_].
  GitHub. — A popular, maintained community best-practices compendium for
  Node.js.

* DesLauriers, M (n.d.).
  https://github.com/mattdesl/module-best-practices[_Module Best Practices_].
  GitHub. — Best practices for writing Node-style modules.

* Elliott, E (n.d.).
  https://medium.com/javascript-scene/master-the-javascript-interview-what-is-functional-programming-7f218c68b3a0[_Master the JavaScript Interview: What is Functional Programming?_].
  Medium. — An overview of functional programming applied to JavaScript.

* Elliott, E (n.d.).
  https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4[_The Two Pillars of JavaScript, Pt 2: Functional Programming_].
  Medium. — On prototypal inheritance and functional programming as
  JavaScript's two defining features.

* Lonsdorf, B (n.d.).
  https://egghead.io/courses/professor-frisby-introduces-composable-functional-javascript[_Professor Frisby Introduces Composable Functional JavaScript_].
  egghead. — A free video course introducing functional programming in
  JavaScript.

* Lonsdorf, B (n.d.).
  https://mostly-adequate.gitbook.io/mostly-adequate-guide[_Professor Frisby's Mostly Adequate Guide to Functional Programming in JavaScript_].
  — A free online book on functional programming in JavaScript.

* Simpson, K (n.d.).
  https://github.com/getify/Functional-Light-JS/tree/master[_Functional-Light JavaScript_].
  GitHub. — A free online book on applying functional programming
  pragmatically in JavaScript.

* Salcescu, C (n.d.).
  https://www.amazon.co.uk/dp/B07PBQJYYG[_Discover Functional JavaScript_].
  Amazon. — A book on functional programming techniques in JavaScript.

* Johansen, C (n.d.). https://vimeo.com/49384334[_Pure JavaScript_]. Vimeo. —
  A video talk on functional programming in JavaScript.

* 7urtle (n.d.).
  https://www.7urtle.com/javascript-functional-programming-advantages[_JavaScript Functional Programming Advantages_].
  — An article on the benefits of functional programming in JavaScript.

* Hewlett-Taylor, T (n.d.).
  https://dev.to/tomht/a-light-introduction-to-tacit-programming-with-javascript-3jm2[_A Light Introduction to Tacit Programming with JavaScript_].
  dev.to. — An introduction to point-free style in JavaScript.

* Haverbeke, M (n.d.).
  https://eloquentjavascript.net/1st_edition/chapter6.html[_Eloquent JavaScript: Functional Programming_].
  — The functional programming chapter from the first edition of Eloquent
  JavaScript.

* Gechev, M (2013).
  https://blog.mgechev.com/2013/01/21/functional-programming-with-javascript/[_Functional Programming with JavaScript_].
  — A practical introduction to functional programming techniques in
  JavaScript.

* Oxley, T (n.d.).
  https://github.com/timoxley/functional-javascript-workshop[_Functional JavaScript Workshop_].
  GitHub. — A Node-based workshop for learning functional programming.

* Rinaldi, B (n.d.).
  https://modernweb.com/functional-reactive-programming-in-javascript/[_Functional Reactive Programming in JavaScript_].
  — Implementing FRP with libraries such as Bacon.js and RxJS.

* Iffland, D (2016).
  https://www.infoq.com/articles/virtual-panel-reactive-javascript-and-elm-in-2016[_Virtual Panel: State of Reactive in JavaScript and Elm_].
  InfoQ. — A panel discussion on the reactive landscape in JavaScript and
  Elm.

* Podwysocki, M (2010).
  https://www.codebetter.com/matthewpodwysocki/2010/02/16/introduction-to-the-reactive-extensions-to-javascript/[_Introduction to the Reactive Extensions to JavaScript (RxJS)_].
  — An early introduction to RxJS.

* Osmani, A (2012).
  https://www.smashingmagazine.com/2012/11/writing-fast-memory-efficient-javascript/[_How to Write Fast, Memory-Efficient JavaScript_].
  Smashing Magazine. — Techniques for writing performant, memory-efficient
  JavaScript.

* Osmani, A (n.d.).
  https://medium.com/dev-channel/javascript-start-up-performance-69200f43b201[_JavaScript Start-Up Performance_].
  Medium. — On parsing and compilation bottlenecks that affect web
  application start-up.

* Baker, G and Arvidsson, E (n.d.).
  https://developers.google.com/speed/articles/optimizing-javascript[_Optimizing JavaScript Code_].
  Google PageSpeed Insights. — Performance guidance from engineers on GMail
  and Chrome.

* Husain, J (n.d.).
  https://egghead.io/courses/asynchronous-programming-the-end-of-the-loop[_Asynchronous Programming: The End of The Loop_].
  egghead. — A free video course on asynchronous programming in JavaScript.

* Severien, T (n.d.).
  https://www.sitepoint.com/importance-of-code-that-humans-can-read/[_The Importance of Writing Code That Humans Can Read_].
  SitePoint. — On writing human-readable code, with JavaScript examples.

* Ronacher, A (2022).
  https://lucumr.pocoo.org/2022/1/10/dependency-risk-and-funding/[_Dependency Risk and Funding_].
  — On the risks of third-party dependencies and the sustainability of the
  open-source ecosystem behind them.