= JSON-LD (JSON for Linked Data)

https://json-ld.org/[JSON-LD] is a schema used to imbue JSON documents with semantic meaning and to embed linked data.

JSON-LD bridges the gap between concepts from the semantic web and modern web service APIs. The idea is that machines
can understand and explore data in JSON documents, similarly to how semantic web technologies like RDF and OWL work.

JSON-LD defines two main properties:

* `@context` references a vocabulary that describes the concepts in the document.
* `@type` indicates the type of the entity represented by an object.

https://schema.org/[Schema.org] is perhaps the most popular vocabulary for JSON-LD. Its vocabulary can also be embedded
in HTML documents using microdata or RDFa.

[source,json]
----
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Jane Doe",
  "jobTitle": "Professor",
  "telephone": "(425) 123-4567",
  "url": "http://www.janedoe.com"
}
----

It is RECOMMENDED to reuse existing vocabularies, such as Schema.org, wherever there is a good fit for an application's
schema. Even if a vocabulary does not cover all the concepts required by the application, it is still better to try to
reuse existing vocabularies, even if only partially. This saves time and effort designing new schemas, and it also helps
to keep data as interoperable as possible with other systems. Even if interoperability is not a requirement now, it may
be in the future.

For example, Schema.org's https://schema.org/Person[Person type], which defines properties such as `givenName`,
`familyName`, `jobTitle`, and `telephone`, is a good basis from which to design a schema for users, customers, or other
such entities.

For further guidance on using JSON-LD, the W3C maintains a https://w3c.github.io/json-ld-bp/[JSON-LD Best Practices]
document.
