= Development and testing environments

Development and testing environments SHOULD be *zero-touch ephemeral
environments*. These are isolated environments that are automatically created
and destroyed as needed, without any manual intervention.

It is RECOMMENDED to use infrastructure-as-code (IaC) tools to manage these
environments. This allows for consistent and repeatable environment creation
on-demand. Rollback is more easily automated, too.

Ephemeral environments are designed to be cost-effective, as they can be easily
spun down when no longer needed, allowing organizations to only pay for the
resources they are actively using. Automation can be used to automatically
terminate most non-production environments outside of normal working hours.

Development and testing environments MUST be close replicas of production
environments, with essentially the same underlying infrastructure and
configuration. This ensures that any issues encountered in production
environments are more likely to be caught early in development or testing, prior
to deployment to production. The only differentiating factors should be the use
of dummy data in non-production environments, and pre-production environments
would typically have fewer resources than production environments, too.
