= TS-49: Cloud Platform Engineering
:toc: macro
:toc-title: Contents

This technical standard sets out some broad principles and best practices for cloud platform engineering. The guidance here is not specific to any particular cloud service provider, but is intended to be applicable to any cloud platform.

Platform engineering is a subset of cloud engineering. The focus here is on the building of *self-service platforms* that enable development teams to deliver applications and services more efficiently. Platform engineering is about creating a standard set of tools, processes, and best practices within an organization to enable development teams to build, test, deploy, and manage their applications themselves, with minimal ops support.

Specific technologies that support cloud platform engineering, such as infrastructure-as-code, CI/CD pipelines, and monitoring and observability tools, are covered in other technical standards. For guidance on cloud cost management and the tradeoffs between dedicated servers and cloud-native architectures, see *link:../054/README.adoc[TS-54: Cloud Economics]*.

toc::[]

include::./01-multi-product-deployments.adoc[leveloffset=+1]
include::./02-development-and-testing-environments.adoc[leveloffset=+1]
