[#references]
= References

* 7urtle.
  {link-7urtle-fp-advantages}[_JavaScript Functional Programming Advantages_].

* Aboukhadijeh, F.
  {link-standardjs}[_Standard JS_].

* Adobe.
  {link-adobe-js-coding-standard}[_Adobe JavaScript Coding Standard_].

* Airbnb.
  {link-airbnb-js}[_Airbnb JavaScript Style Guide_].

* Baker, G and Arvidsson, E.
  {link-baker-arvidsson-optimizing-js}[_Optimizing JavaScript Code_].

* DesLauriers, M.
  {link-deslauriers-module-best-practices}[_Module Best Practices_].

* Elliott, E.
  {link-elliott-fp-interview}[_Master the JavaScript Interview: What is Functional Programming?_].

* Elliott, E.
  {link-elliott-two-pillars}[_The Two Pillars of JavaScript, Pt 2: Functional Programming_].

* Gechev, M (2013).
  {link-gechev-2013}[_Functional Programming with JavaScript_].

* Geisendörfer, F.
  {link-geisendorfer-node-style}[_Felix's Node Style Guide_].

* Goldberg, Y.
  {link-goldberg-node-best-practices}[_Node.js Best Practices_].

* Google.
  {link-google-jsguide}[_Google JavaScript Style Guide_].

* Haverbeke, M.
  {link-haverbeke-eloquent-js-fp}[_Eloquent JavaScript: Functional Programming_].

* Hewlett-Taylor, T.
  {link-hewlett-taylor-tacit}[_A Light Introduction to Tacit Programming with JavaScript_].

* Husain, J.
  {link-husain-async-programming}[_Asynchronous Programming: The End of The Loop_].

* Iffland, D (2016).
  {link-iffland-2016}[_Virtual Panel: State of Reactive in JavaScript and Elm_].

* Johansen, C.
  {link-johansen-pure-js}[_Pure JavaScript_].

* Kikobeats.
  {link-mythbusters-js}[_MythBusters JS_].

* Lonsdorf, B.
  {link-lonsdorf-mostly-adequate-guide}[_Professor Frisby's Mostly Adequate Guide to Functional Programming in JavaScript_].

* Lonsdorf, B.
  {link-lonsdorf-professor-frisby-course}[_Professor Frisby Introduces Composable Functional JavaScript_].

* McDermott, R.
  {link-mcdermott-clean-code-js}[_clean-code-javascript_].

* Osmani, A (2012).
  {link-osmani-2012}[_How to Write Fast, Memory-Efficient JavaScript_].

* Osmani, A.
  {link-osmani-startup-perf}[_JavaScript Start-Up Performance_].

* Oxley, T.
  {link-oxley-functional-js-workshop}[_Functional JavaScript Workshop_].

* Platypi.
  {link-platypi-typescript}[_Platypi TypeScript Style Guide_].

* Podwysocki, M (2010).
  {link-podwysocki-2010}[_Introduction to the Reactive Extensions to JavaScript (RxJS)_].

* Rinaldi, B.
  {link-rinaldi-frp-js}[_Functional Reactive Programming in JavaScript_].

* Ronacher, A (2022).
  {link-ronacher-2022}[_Dependency Risk and Funding_].

* Salcescu, C.
  {link-salcescu-discover-fp-js}[_Discover Functional JavaScript_].

* Severien, T.
  {link-severien-readable-code}[_The Importance of Writing Code That Humans Can Read_].

* Simpson, K.
  {link-simpson-functional-light-js}[_Functional-Light JavaScript_].

* Sta. Cruz, R.
  {link-sta-cruz-rsjs}[_RSJS_].

* The Pragmatic Engineer (2024).
  {link-pragmatic-engineer-bluesky-2024}[_Inside Bluesky's Engineering Culture_].

* Waldron, R.
  {link-waldron-idiomatic-js}[_Idiomatic.js_].
