= TS-1: Guiding Principles of Software Development
:toc: macro
:toc-title: Contents

This technical standard establishes some general guiding principles for the design and implementation of software systems. These are not intended to be concrete rules, but rather are intended to provide a framework for thinking about software design.

toc::[]

== Design for change

The ultimate quality of any software system is how easily it can be changed.

Software is a product and, like any product, it exists to fulfil a need or want. The difficulty is that software development is a particularly *wicked problem*. It is often the case that the users' needs and wants are not understood when development starts on new software products. The problem is often not well defined, and therefore the solution is often not obvious.footnote:[The term "wicked problem" was invented by Horst Rittel and Melvin Webber in their 1973 paper "Dilemmas in a General Theory of Planning". Rittel and Webber were urban planners, and they used the term "wicked problem" to describe the complex, ill-defined problems they were commissioned to solve. A wicked problem is a problem that is not well defined and that has no obvious solution, because all possible solutions involve conflicting goals and constraints. The concept has since been applied to other fields, including software development.]

Even in continuously released software, it is not always obvious which features should be prioritized for the next iteration. There is rarely a shortage of _ideas_ for new features. What is difficult is knowing which ideas will deliver the most value to users. In 2009 Microsoft conducted a research study into its own internal product planning. It found that two-thirds of ideas implemented in its software products did not meaningfully improve the metrics they were intended to improve. And this is _Microsoft_, which has a very mature product development process, involving lots of market research and user testing. The proportion of software features that don't work out is likely to be even higher in many software houses.

The data shows that we often can't be certain that the cost of developing software features will be justified by the value they deliver to users. This is true of any product development, of course. But it seems to be especially true of software. Multiple studies have suggested that as many as https://www.split.io/blog/the-80-rule-of-software-development/[80% of features]
in the average software product are rarely or never used.

[quote, Steve Jobs]
____
People don't know what they want until you show it to them.
____

In enterprise application software, requirements are often constantly changing in response to changing business priorities and external conditions like regulation and competition. And different stakeholders often have different priorities, and sometimes even conflicting product ideas. In consumer software, innovation – in the form of rapid iteration and experimentation – is often required to find product-market fit.

For all these reasons, the optimum solution – the best _design_ for a software product – tends to emerge quite late in the development process, and often some considerable time after construction has begun.

Of course, there will sometimes be software projects with reasonably stable and precise requirements. Yet some degree of uncertainty is unavoidable in software development. At the very least, developers must deal with the changing IT environment around their software. Dependencies will always need to be updated. Newly discovered security vulnerabilities will need to be patched. And program code will need to be changed from time-to-time, for instance to maintain compatibility with new versions of the programming languages in which the programs are written. When you don't respond to these changes, *software rot* sets in.footnote:[The term "software rot" refers to the observation that computer programs appear to decay in their performance and reliability over time, even if nothing appears to change. That's because all computer programs have dependencies on other computer systems, such as an operating system and certain utility programs, and those external dependencies will change over time. Therefore, all software must be continually maintained to keep it working.]

A universal truth of all software projects is that *requirements are emergent* to some degree. In extreme cases – in highly innovative projects, for example – we might not even know what problem we're trying to solve with software, let alone how we will solve it.

But, at least in the field of software development we have an advantage over the development of physical products: we can change software after it has been delivered. The clue is in the title. Software is _soft_. It is malleable, changeable. We can make our software do different things simply by changing parts of its code and configuration. We don't have to remake the whole thing. This is not true of most physical goods.

The natural response to the inherent uncertainty in software projects is to try to lock down requirements early in a project. But a better strategy tends to be to *embrace change*. Rather than attempting to carefully plan every deliverable feature in advance, we should plan instead to deliver system designs that can easily accommodate changing requirements.

Changeability (aka. evolvability) is the ultimate quality of a software system. Software systems that are easy to change tend to have long useful lives and deliver a high return on investment.

