= TS-3: Source Control
:toc: macro
:toc-title: Contents

This technical standard covers the use of source code management (SCM) systems, also known as source control or version control systems.

toc::[]

== Terminology

This technical standard uses railway metaphors in its explanations of source control branching-and-merging strategies. *Mainline tracks* are perpetual branches that represent the main line of progress. Many Git workflows have just a single mainline track, which is invariably named `main`, `master`, `develop`, or `trunk`. But it is also possible, as with railway lines, to have multiple mainline tracks running alongside each other, with *merge points* along their routes where they are synchronized.

Continuing the railway metaphors, *side branches* are short-lived branches that branch off the mainline tracks before merging back in later along the line. In source control systems, side branches are used for parallel development of software features, fixes, and other changes in code and configuration.

== Source control systems

https://git-scm.com/[Git] is the _de facto_ industry standard for source control. It is RECOMMENDED for use in software projects. However, similar decentralized source control systems such as https://www.mercurial-scm.org/[Mercurial] and https://fossil-scm.org/[Fossil] MAY be used instead.

Issue tracking systems SHOULD be integrated with source control Using a combination of the two systems makes it much easier to manage and track changes in source code and configuration. See also *link:./002-issue-tracking.adoc[TS-2: Issue Tracking]*.

In addition, CI/CD systems SHOULD be integrated with source control. This is the basis for continuous integration and continuous delivery practices.

All-in-one devops toolchains such as https://github.com/[GitHub], https://about.gitlab.com/[GitLab], https://azure.microsoft.com/en-us/products/devops/[Azure DevOps], and https://www.atlassian.com/[Atlassian]'s software suite, provide deep integrations between source control, issue tracking, and CI/CD systems, while https://fossil-scm.org/[Fossil] embeds bug tracking directly into the source control system itself. It is RECOMMENDED to use tools like these, as they allow for a higher level of automation in development and operations workflows.

Source control systems are also the basis for continuous integration and continuous delivery practices. CI/CD systems should be integrated with the source control system.

