= TS-5: HTTP APIs


== Authentication and authorization

Authentication and authorization MUST be implemented for all APIs, including private (internal network) APIs.

Authentication and authorization is especially important for operations that modify data.

== Security

All input MUST be validated and sanitized to prevent security vulnerabilities such as SQL injection, cross-site scripting (XSS), and cross-site request forgery (CSRF).

Security measures MUST be implemented for both public and private APIs. Do not assume that private internal networks are secure.

== HTTP methods

HTTP methods define actions to be performed on a resource, which is identified by the request URI. HTTP methods MUST be used for their designated purpose as specified by the HTTP standards. This aids in clarity of the API and makes it easier for client applications to integrate with the API.

The most common HTTP methods are:

* *GET*: Used to retrieve the requested resource, identified by its URL. GET operations MUST NOT modify the state of the resource, and there MUST NOT be any other side effects.

* *POST*: Used to create a new resource.

* *PUT*: Used to fully replace a resource with the request payload. The request payload MUST contain the complete representation of the new version of the resource.

* *PATCH*: used for partial updates to a resource.

* *DELETE*: Used to delete a resource.

=== Idempotence

GET, PUT and DELETE methods are idempotent, which means that multiple identical requests MUST have the same effect as a single request.

POST and PATCH methods are not idempotent.

== HTTP response codes

Appropriate HTTP response status codes MUST be used to indicate the result of API requests.

There are many standardized HTTP status codes. Most APIs will need only a subset of these codes. The supported subset of HTTP status codes MUST be documented as part of the API's interface specification.

Using the correct codes in responses is not just about adhering to the HTTP protocol, but also about facilitating the correct interpretation of the responses by clients.

Commonly-used status codes include:

* *1xx*: Informational response codes.

  ** *100 Continue**: Indicates that the initial part of the request has been received and the client should continue sending the rest of the request.

* *2xx*: Success response codes.

  ** *200 OK*: Indicates that the request was successful. This is the most widely-used success response code.

  ** *201 Created*: Indicates that the request was successful and, as a result, a new resources has been created.

  ** *204 No Content*: Indicates that the request was successful but there is no content to return in the response message. This status code MUST be sent with an empty HTTP message body.

* *3xx*: Redirection response codes.

  ** *301 Moved Permanently*: Indicates that the requested URL has been changed permanently. The new URL MUST be specified in the response.

  ** *302 Found*: Indicates that the request resources is temporarily under a different URL.

* *4xx*: Client error response codes.

  ** *400 Bad Request*: Indicates that the request cannot be understood or processed by the server due to a client syntax error.

  ** *401 Unauthorized*: Indicates that the request requires authentication but the client has not authenticated itself.

  ** *403 Forbidden*: Indicates that the server understood the request but is refusing to authorize it.

  ** *404 Not Found*: Indicates that the server could not find the requested resource.

  ** *405 Method Not Allowed*: Indicates that the HTTP method used in the request is not allowed for the specified resource (but the resource exists and other methods can be run on it).

* *5xx*: Server error response codes.

  ** *500 Internal Server Error*: Indicates that the server encountered a situation it doesn't know how to handle.

  ** *502 Bad Gateway*: Indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.

  ** *503 Service Unavailable*: Indicates that the server is not ready to handle the request, typically due to maintenance or overload.



