= TS-6: HTTP APIs
:toc: macro
:toc-title: Contents

This document outlines standards for designing and implementing HTTP APIs. These standards are applicable to private HTTP APIs between services within distributed software systems ("inter-service communication protocols"), and public HTTP APIs that are made available for integration into client applications ("web services").

toc::[]

== Authentication and authorization

Authentication and authorization MUST be implemented for all APIs, including private (internal network) APIs.

Authentication and authorization is especially important for operations that modify data.

== Security

All input MUST be validated and sanitized to prevent security vulnerabilities such as SQL injection, cross-site scripting (XSS), and cross-site request forgery (CSRF).

Security measures MUST be implemented for both public and private APIs. Do not assume that private internal networks are secure.

== HTTP methods

HTTP methods define actions to be performed on a resource, which is identified by the request URI. HTTP methods MUST be used for their designated purpose as specified by the HTTP standards. This aids in clarity of the API and makes it easier for client applications to integrate with the API.

The following HTTP methods MUST be used:

|===
|Verb |CRUD usage |Idempotent |Description

|GET
|Read
|Yes
|Used to retrieve the requested resource, identified by its URL. GET operations MUST NOT modify the state of the resource, and there MUST NOT be any other side effects.

|POST
|Create
|No
|Used to create a new resource. The server MUST generate a new resource identifier and return it in the response.

|PUT
|Create/Update
|Yes
|Used to fully replace a resource with the request payload. The request payload MUST contain the complete representation of the new version of the resource. Can also be used for creation when the client provides the resource identifier.

|PATCH
|Update
|No
|Used for partial updates to a resource. The request payload SHOULD contain only the fields that are being updated.

|DELETE
|Delete
|Yes
|Used to delete a resource. Should be repeatable, always with a positive response even if the resource is already deleted.
|===

=== Idempotence

GET, PUT and DELETE methods are idempotent, which means that multiple identical requests MUST have the same effect as a single request.

POST and PATCH methods are not idempotent.

== HTTP response codes

Appropriate HTTP response status codes MUST be used to indicate the result of API requests.

There are many standardized HTTP status codes. Most APIs will need only a subset of the standard codes. The supported subset of HTTP status codes MUST be documented as part of the API's interface specification.

Using the correct codes in responses is not just about adhering to the HTTP protocol, but also about facilitating the correct interpretation of the responses by clients.

Commonly-used status codes include:

* *1xx*: Informational response codes.

  ** *100 Continue**: Indicates that the initial part of the request has been received and the client should continue sending the rest of the request.

* *2xx*: Success response codes.

  ** *200 OK*: Indicates that the request was successful. This is the most widely-used success response code.

  ** *201 Created*: Indicates that the request was successful and, as a result, a new resources has been created.

  ** *204 No Content*: Indicates that the request was successful but there is no content to return in the response message. This status code MUST be sent with an empty HTTP message body.

* *3xx*: Redirection response codes.

  ** *301 Moved Permanently*: Indicates that the requested URL has been changed permanently. The new URL MUST be specified in the response.

  ** *302 Found*: Indicates that the requested resource is temporarily under a different URL.

* *4xx*: Client error response codes.

  ** *400 Bad Request*: Indicates that the request cannot be understood or processed by the server due to a syntax error in the client's request message.

  ** *401 Unauthorized*: Indicates that the request requires authentication but the client has not authenticated itself.

  ** *403 Forbidden*: Indicates that the server understood the request but is refusing to authorize access to the specific resource requested.

  ** *404 Not Found*: Indicates that the server could not find the requested resource.

  ** *405 Method Not Allowed*: Indicates that the HTTP method used in the request is not allowed for the specified resource (but the resource exists and other methods can be run on it).

* *5xx*: Server error response codes.

  ** *500 Internal Server Error*: Indicates that the server encountered a situation it doesn't know how to handle.

  ** *502 Bad Gateway*: Indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.

  ** *503 Service Unavailable*: Indicates that the server is not ready to handle the request, typically due to maintenance or overload.

== URI components

=== Path delimiters

The forward slash (`/`) character is used to delimit between path segments in URIs.

Documentation SHOULD be consistent in its use of trailing slashes. It is RECOMMENDED that trailing slashes be omitted in documentation.

However, an API SHOULD accept requests with or without a trailing slash, and SHOULD NOT return a redirect response to the canonical version.

=== Versioning

URL-based versioning SHOULD be used for its simplicity of use for API consumers, compared to the more complex header-based approach.

The first segment of the URI path SHOULD be `/v[major]` where `[major]` is the major version number of the API, eg. `/v1`.

.Template
----
/v[major]
----

.Example
----
/v1
----

=== Namespaces

The next part of the URI path SHOULD be treated as a "namespace" in which related resources will be grouped. Namespaces SHOULD reflect the customer's perspective of how the product works, which may not necessarily reflect the scope and boundaries of the back-end services that will be responsible for fulfilling requests for different resources.

.Template
----
/v[major]/[namespace]
----

.Example
----
/v1/vault
----

Namespaces SHOULD be nouns but MAY be either singular or plural.

=== Resources and collections

Consistent path components SHOULD be used to refer to the same resources and collections across different endpoints.

.URI templates
----
GET /v[major]/[namespace]/[resource]
GET /v[major]/[namespace]/[resource]/[resource_id]
POST /v[major]/[namespace]/[resource]/[resource_id]
PUT /v[major]/[namespace]/[resource]/[resource_id]
PATCH /v[major]/[namespace]/[resource]/[resource_id]
DELETE /v[major]/[namespace]/[resource]/[resource_id]
----

Sub-resources and sub-collections MAY also be supported.

.URI templates
----
GET /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]
GET /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
POST /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
PUT /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
PATCH /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
DELETE /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
----

== Collections

A collection is a list of multiple resources, typically of the same type, and including any related metadata.

Collection resources and their metadata SHOULD be named consistently across different endpoints. This allows clients to implement generic data access handling. Arrays of resources SHOULD be returned in a field named `items`. Metadata fields such as `total_items` and `total_pages` SHOULD be included in a `meta` object.

In cases where individual resources contain a large object, providing a summarized or minimized version of the data representation can help to reduce the bandwidth footprint. Support query parameters that allow clients to opt-in to receiving the full representation of a collection's resources. Alternatively, clients can read the resources individually to retrieve their full representations.

.URI template
----
GET /v[major]/[namespace]/[resource]
----

.Example
----
GET /v1/vault/credit-cards
----

.Example response
----
{
    "total_items": 1,
    "total_pages": 1,
    "items": [
        {
            "id": "123e4567-e89b-12d3-a456-426614174000",
            "type": "visa",
            "number": "xxxxxxxxxxxx0331",
            "expire_month": "11",
            "expire_year": "2018",
            "first_name": "Joe",
            "last_name": "Shopper",
            "create_time": "2014-01-13T07:23:15Z",
            "update_time": "2014-01-13T07:23:15Z",
            "links": [
                {
                    "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
                    "rel": "self",
                    "method": "GET"
                },
                {
                    "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
                    "rel": "delete",
                    "method": "DELETE"
                },
                {
                    "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
                    "rel": "patch",
                    "method": "PATCH"
                }
            ]
        }
    ],
    "links": [
        {
            "href": "https://api.example.com/v1/vault/credit-cards/?page_size=10&sort_by=create_time&sort_order=asc",
            "rel": "first",
            "method": "GET"
        }
    ]
}
----

=== Pagination

Pages of results SHOULD be referred to consistently by the query parameters `page` and `page_size`, where `page_size` refers to the amount of results per response, and `page` refers to the requested page (which starts at page 1, not page zero).

Additionally, responses SHOULD include `total_items` and `total_pages` where possible. `total_items` indicates then total number of items in the collection, and `total_pages` is the number of pages based on the current `page_size` (interpolated from `total_items`/`page_size`).

Hypermedia links SHOULD be included in paginated collections, as they make it easier for clients to navigate through the collection. The `page` and `page_size` query parameters, inputted by the client, MUST be maintained for each link. Links SHOULD be provided with `rel` attributes for "next", "previous", "first", and "last" pages.

=== Filtering

If time selection is needed, `start_time` or `[property_name]_after`, and `end_time` or `[property_name]_before` query parameters SHOULD be supported. These parameters SHOULD be used consistently across different endpoints.

=== Searching

Search query parameters MAY be supported on collections, to allow clients to filter collection lists based on freeform input. The query parameter SHOULD be named `q` and MAY be used to search across multiple fields of the resources.

=== Sorting

`sort_by` and `sort_order` can be provided to allow for collection results ot be sorted. The `sort_by` field SHOULD be a field that exists within the individual resources of the collection, and `sort_order` SHOULD be either "asc" or "desc".

=== HTTP statuses

If a collection is empty (zero items), `404 Not Found` is not appropriate. It was the collection that was requested, not a specific item in the collection, and the collection exists — it is just empty. Instead, return a `200 OK` response with an empty `items` array.

Invalid query parameters SHOULD be signalled with a `404 Bad Request` response.

== Resources

=== Reading

Single resources are typically discovered through a collection, and are identified by a unique identifier. When reading single resources, a more detailed representation of the resource MAY be returned than the default, minimized representations included in collections.

A resource's unique identifier SHOULD be unique to all resources of all types, not only resources of the same type or in the same collection.

Identifiers for sensitive data SHOULD be non-sequential, and preferably non-numeric. In scenarios where this data might be used as a subordinate to other data, immutable string identifiers SHOULD be used for readability and debugging.

If the provided resource identifier is not found, even if the data is "soft deleted" in the data source, the response status code should be `404 Not Found`. Otherwise, `200 OK` MUST be returned when the resource is found.

.URI template
----
GET /v[major]/[namespace]/[resource]/[resource_id]
----

.Example
----
GET /v1/vault/customers/123e4567-e89b-12d3-a456-426614174000
----

=== Updating

There are two ways to update resources:

* Using `PUT` to fully replace the resource.
* Using `PATCH` to partially update the resource.

In both cases, the shape of the input data SHOULD be consistent with the shape of the resource representation returned by the API via the corresponding GET requests.

For `PUT` requests, system-calculated values such as `create_time` and `update_time` SHOULD be optional and SHOULD be ignored on deserialization by the server. For `PATCH` requests, clients SHOULD be expected to omit these fields from the request body.

.URI template
----
PUT|PATCH /v[major]/[namespace]/[resource]/[resource_id]
----

In most use cases, after a successful update, both `PUT` and `PATCH` operations SHOULD respond with `204 No Content` status, with no response body. However, there may be use cases where it is preferable to return `200 OK` with an updated resource in the response body. For example, this may be required where clients need updates to system-calculated fields.

Any request that fails input validation MUST receive a `400 Bad Request` response. If clients attempt to modify read-only fields, this is also a `400 Bad Request`. Specific error codes, eg. for data type, length, etc., SHOULD be returned in the response body. For situations that require interaction with APIs or processes outside of the current request, the `422 Unprocessable Entity` status code may be more appropriate.

=== Deleting

In order to enable retries (eg. due to patchy connectivity), `DELETE` operations MUST be implemented to be idempotent. This means that successful `DELETE` operations MUST always respond with `204 No Content`, even if the response is already deleted. Returning `404 Not Found` is not appropriate for `DELETE` operations in this scenario, as it suggests that the resource never existed at all. If necessary, clients can use `GET` to verify the resource exists prior to `DELETE`.

.URI template
----
DELETE /v[major]/[namespace]/[resource]/[resource_id]
----

For historical reasons, many web servers and HTTP client libraries do not expect a message body to be included in HTTP messages sent using the `DELETE` method. To support the widest possible range of clients, it remains good practice to not require DELETE requests to be accompanied by a payload.

=== Creating

There are two ways to create resources:

* Using `POST` to create a resource but have the server create an identifier for it.
* Using `PUT` to create a full resource, including a unique identifier that is generated client-side.

.URI template
----
POST|PUT /v[major]/[namespace]/[resource]/[resource_id]
----

`PUT` operations are idempotent by default, because the request payload has a built-in unique identifier in the form of the resource ID.

`POST` operations are not idempotent by default, and therefore there is risk that duplicates of the same resource may be created if the client retries a `POST` request. Where it is necessary to prevent this, clients MUST include a unique identifier for the _request_ message (eg. `request_id`). The server will use the request ID to make sure it processes only the first instance that it receives of each distinct request.

For `PUT` requests, system-calculated values such as `create_time` and `update_time` SHOULD be made optional and SHOULD be ignored on deserialization by the server. For `POST` requests, clients SHOULD be expected to omit these fields from the request body.

Otherwise, both operations SHOULD behave in the same way. Both `POST` and `PUT` payloads MAY include only a subset of input fields (only the required fields, for example), with the server filling in optional fields with default values.

For both `POST` and `PUT` creation operations, successful outcomes MUST be signalled by a `201 Created` response, and a representation of the created resource MUST be returned in the response body — including any server-generated fields such as `create_time`.

Response messages SHOULD include a list of hypermedia links that represent all the available operations that can be performed on the newly-created resource. For example, if only `GET` and `DELETE` operations are available:

.Example response
----
{
    "id": "123e4567-e89b-12d3-a456-426614174000",
    "type": "visa",
    "number": "xxxxxxxxxxxx0331",
    "expire_month": "11",
    "expire_year": "2018",
    "first_name": "Joe",
    "last_name": "Shopper",
    "links": [
        {
            "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
            "rel": "self",
            "method": "GET"
        },
        {
            "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
            "rel": "delete",
            "method": "DELETE"
        }
    ]
}
----

== Sub-resources and sub-collections

Sub-resources and sub-collections SHOULD be used sparingly and only where they are essential to expressing an accurate representation of an API's resource model.

.URI templates
----
GET /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]
GET /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
POST /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
PUT /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
PATCH /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
DELETE /v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_id]
----

Where a resource of one type can exist independently of other resources of other types, these resources SHOULD be elevated to top-level resources in most use cases. If one type of resource cannot exist without another, this is a candidate to be lowered to a sub-resource. However, the need to encode hierarchies of resources can increase the complexity of both server-side and client-side code. So, even where there is a tight coupling between two types of resources, look to promoting dependent resources to top-level resources where practical.

Try to have no more than one level of sub-resources - so, two levels of resources in total. Any more levels, and the complexity of client application code grows exponentially. Server code, too, needs to validate each level of resources, including how sub-resources related to resources, increasing code complexity.

Sub-resources MUST have a named type. `/v[major]/[namespace]/[resource]/[resource_id]/[sub_resource_id]` is not acceptable because `sub_resource_id` has ambiguous meaning. Linking resource identifiers to resource types in the URL scheme also supports extensibility; other sub-resources can be more easily added in the future. This constraint also makes it easier to support different identifier naming conventions being used for different types of resources, should that be necessary.

Sub-resources MAY be used as a solution to reducing the size of the parent resource, segmenting a single large resource into multiple smaller resources. These types of sub-resources are known as *singleton sub-resource* and are identified by a *sub-resource name* rather than a conventional identifier. There will be a one-to-one relationship between a resource and each of its singleton sub-resources. Singleton sub-resources are expected to always exist if the parent resource exists, though they may have null values. Singleton sub-resources should be named in the singular form.

.Path templates
----
/v[major]/[namespace]/[resource]/[resource_id]/[sub_resource]/[sub_resource_name]
----

.Example
----
GET /v1/customers/devices/123e4567-e89b-12d3-a456-426614174000/vendor-information
----

== Actions

Some operations do not neatly fit into the RESTful model, in which CRUD-like operations are performed against discrete types of resources. Classic examples include endpoints to "login" or "logout", or to "reset a password", "charge a credit card", "send a notification", or to "receive a webhook event".

These standalone operations, which are not scoped to any particular resource, are known as actions.

Actions tend to be mapped directly to specific controller methods in the server-side code, and for this reason they are the HTTP API equivalent of RPC (remote procedure call) methods.

Actions MUST be performed using the HTTP's `POST` method, except for actions that retrieve read-only data, in which case `GET` MUST be used. The name of the action SHOULD instead suggest the type of CRUD operation that may be performed as a result of the action.

Action names should be like function names. Use lowerCamelCase with the first segment being a verb. The rest of an action's name should, typically, be in the singular forms. Examples: `activateAccount`, `cancelSubscription`, `validateEmail`, `acceptInvitation`, `denyRequest`.

.URI template
----
POST|GET /v[version]/[namespace]/[action]
----

Actions and resources MAY exist in the same namespaces. However, a good practice is to create a collection of actions within each namespace, which SHOULD be named "actions".

.URI template
----
POST /v[version]/[namespace]/actions/[action]
----

This helps to distinguish actions from resources in each namespace. In addition, a `GET /v[version]/[namespace]/actions` endpoint MAY be provided to list all available actions in a namespace, similarly to how resource collections are retrieved.

A common use case for actions is to mutate the state of multiple resources within its namespace in the same operation. These are known as *composite actions*. An example would be a "refund" action that would change the state of a payment, the customer's account, and the merchant's account, and the action would not be considered to be fulfilled until all of these changes are committed.

Another example of a composite action would be the implementation of advanced search functionality, which operate across multiple resource types for example.

Composite actions may be implemented for both performance optimization and usability reasons.

Some actions may be transient — that is, they do not mutate the state of any resources, or create new ones. An example might be a "dry run" action that validates the input data for a subsequent operation, such as a payment.

If actions return read-only data, such as logs or reports, these actions SHOULD use the `GET` method, instead of `POST`, to provide opportunities for caching (`POST` responses are not cacheable).

There may also be use cases for attaching actions to specific resources, or even to sub-resources. For example, where a particular state change requires a comment — such as a cancellation reason — to be provided, it might make sense to require the client to input the comment via a dedicated action, subsequent to the state change being fulfilled via a resource operation. There may be technical constraints for doing so, for example message bodies SHOULD NOT be sent with `DELETE` requests, providing no opportunity to input a comment for that type of operation. But some operations are fundamentally _business processes_ that are related to resources but do not change the core state of the resource itself. In these cases, resource-scoped actions are appropriate.

.URI template
----
POST /v[version]/[namespace]/[resource]/[resource_id]/actions/[action]
----

For successfully executed actions, `204 No Content` will be the most appropriate response status code in most cases (with no body content). However, if the client needs to capture some information from the result of an action a `200 OK` response with a response body MAY be returned. Actions MUST not return updated states for any resource, but MAY return things like statuses for discrete operations such as a payment transaction.

=== Actions-oriented APIs versus resource-oriented APIs

There are risks and benefits to using actions in HTTP APIs. Action-oriented APIs can be harder to scale than resource-oriented ones. The number of URIs can grow much more quickly, producing increased configuration complexity for routing and externalization, among other things. There tends also to be fewer opportunities to promote code reuse in automated tests (because actions tend to have greater variability in their inputs and outputs than operations performed on resources).

However, for most HTTP APIs, not everything fits neatly into the RESTful architectural style. Some operations are simply better expressed as actions.

The preference is to design as much of an API as possible around a resource-oriented model, and augment the API with actions where specific operations do not fit neatly into that model. We should not try to force everything into the resource model just for the sake of purity of the API design.


''''

== Acknowledgements

* link:https://github.com/jharmn/api-standards[Jason Harmon's API standards]
