= TS-6: Requirements Specification
:toc: macro
:toc-title: Contents

This technical standard covers best practices for defining software requirements.

*Software requirements specifications (SRS)*, also known as *system requirements specifications*, define the *acceptance criteria (ACs)* for a software system. Requirements specifications are the basis for the software design and its implementation.

toc::[]

== Responsibility

The requirements are derived from the business domain and SHOULD be written in a way that is understandable to the business stakeholders.

Nevertheless, there are some blurry edges between the high-level business requirements and the low-level technical design choices. For example, a business requirement might be that "passwords must be strong". But this requirement necessitates some technical design choices that the business stakeholders might like to know about. For example, it might be of interest to the business stakeholders what validation algorithms the developers choose to implement to guarantee strong passwords. Although it is not the responsibility of the business stakeholders to specify the password validation algorithm, they might like to understand the high-level rules of the algorithm, such as:

* Minimum 8 characters.
* Mix of letters (any case) and numbers.
* At least one special character, eg. %^&*().
* No dictionary words.

For these reasons, requirements specifications SHOULD be written and maintained in collaboration between the customers (or a representative such as product owner) and the software development team.

== Acceptance criteria

Most requirements specifications SHOULD be written as acceptance criteria. Acceptance criteria – also known as *conditions of satisfaction* – are a set of conditions that a software system must satisfy to be accepted by the customer. They are written in a way that is understandable to the business stakeholders, and are used to define the scope of the software system.

The acceptance criteria SHOULD be written from the perspective of the end users of the software. They should define user needs and wants, but not prescribe specific solutions. This means that acceptance criteria SHOULD NOT include technical implementation details. Indeed, ACs SHOULD NOT even make reference to software.

Acceptance criteria SHOULD be written in a consistent style, using a consistent set of conventions. They MUST be written in a language that is derived from the business domain, and is therefore understood by the business stakeholders.

Acceptance criteria SHOULD capture _requirements_, not convey _instructions_ for things that the business wants implemented in software. A nice analogy is to think of software development teams as like teams of doctors rather than, say, waiting staff in a restaurant. The role of a waiter is to try to give customers exactly what they ask for. The role of a doctor is to discover and learn about an underlying problem, and then prescribe a solution.

This is a critically important distinction. Sometimes, the work of a software development team involves having difficult conversations and giving bad news to the customer, or to other stakeholders in a project. For example, it might be necessary to tell a customer that the requested changes cannot be made within the allocated time and budget constraints. Success in delivery of software projects depends on software development teams being able to represent their rationale viewpoint, so the customer can make better, informed decisions.

Acceptance criteria MUST cover both the functional and non-functional (performance) requirements. The combination of software operations and functionality (specified via the functional requirements) and the constraints within which the software is expected to perform (specified via the non-functional requirements) make up the "features" of a system. A solution is said to be "correct" if it meets both its functional and performance acceptance criteria.

Requirements SHOULD be specified using consistent acceptance criteria definition conventions. These conventions differ slightly between functional and non-functional requirements.

