= TS-6: HTTP APIs
:toc: macro
:toc-title: Contents

This document outlines standards for designing and implementing HTTP APIs.

These standards are applicable to both private HTTP APIs between services within distributed software systems ("inter-service communication") and to public HTTP APIs that are made available for integration into third-party client applications ("web services").

In this technical standard, URLs containing variables are specified according to https://tools.ietf.org/html/rfc6570[IETF RFC 6570: URI Template]. For example, a URL containing a variable called `account_id` would be shown as `https://api.example.com/v1/accounts/{account_id}`.

toc::[]

== General design principles

HTTP APIs, both public and private ones, SHOULD be formed from a consistent set of design patterns — a pattern library. This facilitates a better developer experience and supports greater reuse of code, for example through libraries and software development kits (SDKs), so making integrations quicker and easier to do.

In broad terms, HTTP APIs SHOULD follow the https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm[RESTful architectural style]. This architecture describes the underlying design principles of the World Wide Web, but particularly of the HTTP protocol and HTML language. In practice, a RESTful API is one that repurposes the semantics of the HTTP protocol, using the full capabilities of HTTP as a messaging and encoding protocol, rather than merely as a transport protocol. In simple terms, a RESTful API uses URLs to represent resources and collections of resources, HTTP methods to represent different types of CRUD-like operations to be performed on those resources, and HTTP status codes to represent outcomes from those operations.

A RESTful API is also:

* *Stateless*: Each request from a client to a server SHOULD contain all the information necessary for the server to understand and fulfil the request. Most client requests SHOULD NOT be dependent upon any particular stored context on the server — with exceptions for things like security measures to protect against denial of service. This design constraint will simplify the server implementation and make it more scalable.

* *Uniform*: A RESTFUL API SHOULD have a highly uniform interface, which means it uses a consistent subset of a HTTP methods and status codes, composes message content from a common library of types, and uses a consistent URL structure to represent resources and collections. This constraint will help to simplify client implementations, promote code reuse, and make integrations easier.

* *Cacheable*: As much as possible, responses from a RESTFUL API server SHOULD be cacheable. This helps to reduce load on the server, reduce latency for clients, and supports strategies for fault tolerance and availability.

* *A layered system*: The server application SHOULD have a layered architecture, in which cross-cutting concerns such as security and caching are implemented in discrete layers that span all endpoints of the API.

The following RESTful design constraints are OPTIONAL:

* *Hypermedia as the engine of application state (HATEOAS)*: HTTP APIs MAY embed hypermedia links through which clients can explore the available resources and operations of the API. Clients MAY use the encoded hypermedia controls to read, query, and update application state. This design constraint is not commonly used in practice, but it can be beneficial for some use cases. HATEOAS may be appropriate for APIs that are intended to be consumed directly by human users, who interact with the API through a generic program to explore the available resources and operations, which themselves are constantly evolving. HATEOAS is less useful for APIs that are intended for programmatic integration into other computer systems.

* *Code on demand*: The server MAY send executable code to the client, to extend the functionality of the client. Again, this design constraint is not commonly used in practice, but one possible use case would be for an API to serve updates to SDKs, written in various programming languages, that are dynamically integrated into client applications.

Although most HTTP APIs should be primarily RESTful, or resource-oriented, there are many use cases where a RESTful design is not appropriate. For example, if an API is a thin layer around a legacy system that itself does not support RESTful principles, it may be necessary to deviate from RESTful design principles and focus on creating an functional abstraction of the underlying system.

Even within an HTTP API that is predominantly RESTful in its design characteristics, it will often be beneficial to include operations that are more RPC-like in their design. For example, besides the usual create, read, update and delete operations that are made available on a collection of resources, an HTTP API may augment these operations with additional "actions" that perform tasks on the resources that do not neatly fit the CRUD model, or which abstract multiple CRUD-like operations in a single request. See the section on *Actions* for more information.

In designing an HTTP API, developers SHOULD prioritize creating an accurate model of the system that the API abstracts, rather than trying to religiously adhere to any particular architectural style. Remember, the goal of an HTTP API is to provide a useful and usable interface to a complex system. The best API design will be the one that makes it as easy as possible for clients to interact with the underlying system.

== Authentication and authorization

Authentication and authorization MUST be implemented for all HTTP APIs, including private (internal network) HTTP APIs.

Authentication and authorization is especially important for operations that modify data.

== Security

Security measures MUST be implemented for both public and private APIs. Do not assume that private/internal networks are secure.

All input MUST be validated and sanitized to prevent security vulnerabilities such as SQL injection, cross-site scripting (XSS), and cross-site request forgery (CSRF).

== HTTP methods

HTTP methods define actions to be performed on a resource or collection of resources.

HTTP methods MUST be used for their designated purpose, as specified by the HTTP standards. This will make it much easier for client applications to be integrated with the API.

HTTP APIs MUST use only the following subset of standard HTTP methods:

|===
|Verb |CRUD usage |Description

|GET
|Read
|Used to retrieve the requested resource. GET operations MUST NOT modify the state of the resource, and there MUST NOT be any other side effects.

|HEAD
|Read
|Used to retrieve the only the headers of the resource, without the body.

|POST
|Create
|Used to create a new resource. The server MUST generate a new resource identifier and return it in the response.

|PUT
|Create/Update
|Used to fully replace a resource with the request payload, or to create a new resource in scenarios where the client takes over responsibility from the server for generating a unique identifier for the resource.

|PATCH
|Update
|Used for partial updates to a resource. The request payload SHOULD contain only the fields that are being updated.

|DELETE
|Delete
|Used to delete a resource. Should be repeatable, always with a positive response even if the resource is already deleted.
|===

Other standard HTTP methods are `OPTIONS`, `TRACE`, and `CONNECT`. These are technical methods used to support the HTTP protocol itself, and are not intended the be included in the interface definitions for HTTP APIs.

== HTTP status codes

Appropriate HTTP response codes MUST be used in response messages to indicate the result of API requests. Using the correct codes in responses is not just about adhering to the HTTP protocol, but also about facilitating the correct interpretation of HTTP responses by clients.

There are many standardized HTTP status codes. Most APIs will need only a subset of the standard codes. The supported subset of HTTP status codes MUST be documented as part of the API's interface definition. Commonly-used status codes include:

* *1xx*: Informational response codes.

  ** `100 Continue`: Indicates that the initial part of the request has been received and the client should continue sending the rest of the request.

* *2xx*: Success response codes.

  ** `200 OK`: Indicates that the request was successful. This is the most widely-used success response code.

  ** `201 Created`: Indicates that the request was successful and, as a result, a new resource has been created.

  ** `202 Accepted`: For asynchronous operations that will be fulfilled by the server at a later time.

  ** `204 No Content`: Indicates that the request was successful but there is no content to return in the response message. This status code MUST be returned with an empty HTTP message body.

* *3xx*: Redirection response codes.

  ** `301 Moved Permanently`: Indicates that the requested URL has been changed permanently. The new URL MUST be specified in the response.

  ** `302 Found`: Indicates that the requested resource is temporarily under a different URL.

* *4xx*: Client error response codes.

  ** `400 Bad Request`: Indicates that the request cannot be understood or processed by the server due to a syntax error in the client's request message.

  ** `401 Unauthorized`: Indicates that the request requires authentication but the client has not authenticated itself.

  ** `403 Forbidden`: Indicates that the server understood the request but is refusing to authorize access to the specific resource requested.

  ** `404 Not Found`: Indicates that the server could not find the requested resource.

  ** `405 Method Not Allowed`: Indicates that the HTTP method used in the request is not allowed on the target resource (but the resource exists and other methods can be run on it).

* *5xx*: Server error response codes.

  ** `500 Internal Server Error`: Indicates that the server encountered a situation it doesn't know how to handle.

  ** `502 Bad Gateway`: Indicates that the server, while acting as a gateway or proxy, received an invalid response from an upstream server.

  ** `503 Service Unavailable`: Indicates that the server is not ready to handle the request, typically due to maintenance or overload.

== URLs

URLs identify resources, collections of resources, and actions.

=== Path delimiters

The forward slash (`/`) character is used to delimit between path segments in URLs.

API documentation SHOULD be consistent in its use of trailing slashes. It is RECOMMENDED that trailing slashes be omitted in documentation. However, an API SHOULD accept requests with or without a trailing slash, but SHOULD NOT respond with a redirect to the canonical version.

.Postel's Law (aka. the Robustness Principle)
****
Be liberal in what you accept, and conservative in what you send.
****

=== Versioning

HTTP APIs MUST be versioned, and version information SHOULD be encoded in the URL path. This pattern is widely used for its simplicity of use by clients and compatibility with caching and proxying systems (compared to alternative designs such as header-based versioning).

HTTP APIs MUST use https://semver.org/[Semantic Versioning], as specified in *link:./032-versioning.adoc[TS-32: Versioning]*. However, only the major version number needs to be exposed in the URL schema.

It is RECOMMENDED that the major version number be the first segment of the URL path, eg. `/v1`. This tends to make it easier for clients to implement version-specific behavior, and it also tends to make it easier to maintain and deploy multiple major versions of an API in parallel on the server side.

.Template
----
/v{major}
----

.Example
----
/v1
----

See the *Versioning* section, below, for more guidance on HTTP API versioning.

=== Namespaces

The next part of the URL path SHOULD be treated as a "namespace" in which related resources will be grouped.

Namespaces are used to create logical groups of resources, collections, and actions. But they do not necessarily map directly to modules or back-end services that are responsible for fulfilling requests. Namespaces SHOULD reflect the customer's perspective of how the product works. That perspective may not necessarily reflect the internal structure of the system, or the business domains and subdomains.

.Template
----
/v{major}/{namespace}
----

.Example
----
/v1/vault
----

Namespaces SHOULD be nouns but MAY be either singular or plural, as most appropriate.

=== Resources and collections

The remaining segments of a URL path are used to identify resources and collections of resources,

Consistent path components SHOULD be used to refer to the same resources, and collections of them, across different endpoints.

.Templates
----
GET /v{major}/{namespace}/{resource}
GET /v{major}/{namespace}/{resource}/{resource_id}
POST /v{major}/{namespace}/{resource}/{resource_id}
PUT /v{major}/{namespace}/{resource}/{resource_id}
PATCH /v{major}/{namespace}/{resource}/{resource_id}
DELETE /v{major}/{namespace}/{resource}/{resource_id}
----

Sub-resources and sub-collections MAY be supported, too.

.Templates
----
GET /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}
GET /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
POST /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
PUT /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
PATCH /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
DELETE /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
----

The `{resource}` and `{sub_resource}` components SHOULD be named using nouns. These SHOULD be in the singular form where there is only ever one instance of the resource, and never a collection of resources of the same type. More commonly, there will be collections of each type of resource and sub-resource, and these SHOULD be named in the plural form.

Resource-oriented endpoints SHOULD use lowercase hyphen-delimited slugs to name resources and sub-resources. Examples: "account", "users", "billing", "charge-points", "charge-points/{charge_point_id}/sessions", "credit-cards", "credit-cards/{credit_card_id}/transactions".

== Collections

A collection is a list of multiple resources of the same type, plus any related metadata.

Collections, and the resources they encapsulate, SHOULD be named consistently across different endpoints. This allows clients to implement generic data access handling.

.Template
----
GET /v{major}/{namespace}/{resource}
----

.Example
----
GET /v1/vault/credit-cards
----

// TODO: Update to match standard schema.
.Example response
----
{
  "metadata": {
    "total_items": 1,
    "total_pages": 1
  },
  "items": [
    {
      "data": {
        "id": "123e4567-e89b-12d3-a456-426614174000",
        "type": "visa",
        "number": "xxxxxxxxxxxx0331",
        "expires": {
          "month": "11",
          "year": "2018",
        },
        "name": {
          "first": "Joe",
          "last": "Shopper"
        }
      },
      "metadata": {
        "create_time": "2014-01-13T07:23:15Z",
        "update_time": "2014-01-13T07:23:15Z",
      },
      "links": [
        {
          "rel": "self",
          "method": "GET"
          "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000"
        },
        {
          "rel": "delete",
          "method": "DELETE",
          "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000"
        },
        {
          "rel": "patch",
          "method": "PATCH",
          "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000"
        }
      ]
    }
  ],
  "links": [
    {
      "rel": "self",
      "method": "GET",
      "href": "https://api.example.com/v1/vault/credit-cards?page=3&per_page=10&sort_by=create_time&sort_order=asc"
    },
    {
      "rel": "prev",
      "method": "GET",
      "href": "https://api.example.com/v1/vault/credit-cards/?page=2&per_page=10&sort_by=create_time&sort_order=asc
    },
    {
      "rel": "next",
      "method": "GET",
      "href": "https://api.example.com/v1/vault/credit-cards/?page=4&per_page=10&sort_by=create_time&sort_order=asc"
    },
    {
      "rel": "first",
      "method": "GET",
      "href": "https://api.example.com/v1/vault/credit-cards/?per_page=10&sort_by=create_time&sort_order=asc"
    },
    {
      "rel": "last",
      "method": "GET",
      "href": "https://api.example.com/v1/vault/credit-cards/?page=123&per_page=10&sort_by=create_time&sort_order=asc"
    }
  ]
}
----

=== Pagination

Any collection that could contain a large, potentially unbounded list of resources SHOULD implement pagination. The following design patterns are RECOMMENDED.

----
/accounts?per_page={per_page}&page={page}
----

Pages of results SHOULD be referred to consistently by the query parameters `page` and `per_page`, where `per_page` is a non-zero positive integer representing the number of results per paginated response, and `page` is a number of 1 or more that represents the current page of results requested.

The `per_page` query parameter SHOULD be optional. If not provided by the client, the server should fallback to a sensible, specified default.

The `page` query parameter SHOULD also be optional. If not provided by the client, the server MUST return the first page of results (ie. the default value for `page` MUST be 1).

The values of both `page` and `per_page` MUST be validated by the server. A `400 Bad Request` SHOULD be returned for semantically invalid values. However, if the requested range if outside of the available range of results (eg. `per_page=100&page=2` is requested but there are only 50 results) a `200 OK` response SHOULD be returned with an empty result list, not a `404 Not Found`.

In certain cases, such as querying on a large data set, in order to optimize the query execution while paginating, querying and retrieving the data based on the result set of the previous page might be appropriate. A `page_token` parameter MAY be used for this purpose. This could be, for example, an encrypted value of primary keys to navigate to the next and previous pages, along with directions.

Additionally, responses MAY include `total_items` and `total_pages` metadata fields. `total_items` indicates then total number of items in the collection, and `total_pages` is the number of pages (interpolated from `total_items`/`per_page`). This will help clients to implement better user experiences, for example by disabling navigation to pages that are outside of the available range. Where providing the `total_items` and `total_pages` requires expensive queries on the server-side, the client SHOULD be able to opt-in to receiving this information using a query parameter, for example `?include_totals=true`.

Hypermedia links with `rel` attributes for "next", "previous", "first", and "last" pages SHOULD be included in paginated collections, to make it easier for clients to navigate through collections. The `page` and `per_page` query parameters, inputted by the client, MUST be maintained for each link, to ensure consistent client behavior. See the section on *Hypermedia* for more information.

=== Filtering

Collections MAY be filtered by default. For example, resources to which a user is not authorized to access MUST NOT be included in a collection. If all resources in a collection are not authorized, returning a `403 Forbidden` response would be appropriate.

Additional, optional filtering may be applied by clients using query parameters.

==== Time selection

Query parameters with regard to time range MAY be used to select a subset of resources in the following manner:

* `start_time` or `{property_name}_after`: An ISO-8601 date and time string that represents the start of a temporaal range. `start_time` may be used when there is only one unambiguous time dimension, otherwise the property name should be used, eg, `processed_after`, `uploaded_after`. THe property SHOULD map to a time field in the representation.

* `end_time` or `{property_name}_before`: An ISO-8601 date and time string indicating the end of a temporal range. `end_time` may be used when there is only one unambiguous time dimension, otherwise the property name should be used, eg. `processed_before`, `uploaded_before`. The property SHOULD map to a time field in the representation.

These query parameters SHOULD be used consistently across all endpoints that support time-based filtering.

=== Searching

Search query parameters MAY be supported on collections, to allow clients to filter collection lists based on freeform input. The query parameter SHOULD be named `q` and MAY be used to search across multiple fields of the resources.

=== Sorting

Results could be ordered according to sorting-related instructions given by the client. This includes sorting by a specific field's value, and sorting order.

The following URL parameters SHOULD be used for this purpose:

* `sort_by`: A dimension by which items should be sorted. The dimensions SHOULD be an attribute in the item's representation.

* `sort_order`: The order, one of "asc" or "desc", indicating ascending or descending order.

The default sort field and sort order MUST be documented for each collection. All collections have a default sorting, except in use cases where the order is deliberately randomized (if so, this still needs to be specified).

=== HTTP statuses

If a collection is empty (zero items), `404 Not Found` is not appropriate. It was the collection that was requested, not a specific item in the collection, and the collection exists — it is just empty. Instead, return a `200 OK` response with an empty `items` array.

Invalid query parameters SHOULD be signalled with a `404 Bad Request` response.

== Resources

=== Reading

Single resources are typically discovered through a collection, and are identified by a unique identifier. When reading single resources, a more detailed representation of the resource MAY be returned than the default, minimized representations included in collections.

A resource's unique identifier SHOULD be unique to all resources of all types, not only resources of the same type or in the same collection.

Identifiers for sensitive data SHOULD be non-sequential, and preferably non-numeric. In scenarios where this data might be used as a subordinate to other data, immutable string identifiers SHOULD be used for readability and debugging.

If the provided resource identifier is not found, even if the data is "soft deleted" in the data source, the response status code should be `404 Not Found`. Otherwise, `200 OK` MUST be returned when the resource is found.

.Template
----
GET /v{major}/{namespace}/{resource}/{resource_id}
----

.Example
----
GET /v1/vault/customers/123e4567-e89b-12d3-a456-426614174000
----

.GET versus HEAD
****
It is RECOMMENDED that all GET endpoints — for both resources and collections — in an HTTP API also support HEAD requests. HEAD responses are identical to GET responses, except that the server MUST NOT return a message body in the response. This can be useful for clients that need to check the existence of a resource without downloading the full representation.
****

=== Updating

There are two ways to update resources:

* Using `PUT` to fully replace the resource.
* Using `PATCH` to partially update the resource.

In both cases, the shape of the input data SHOULD be consistent with the shape of the resource representation returned by the API via the corresponding GET requests. The only difference is that `PATCH` may submit fewer fields — essentially a diff of what's changed since the last `GET`.

For `PUT` requests, system-calculated values such as `create_time` and `update_time` SHOULD be optional and SHOULD be ignored on deserialization by the server. For `PATCH` requests, clients SHOULD be expected to omit these fields from the request body, and the server SHOULD return `400 Bad Request` if they are included. For `PATCH` requests, the client is expected to submit only the fields that have been updated by the client.

.Template
----
PUT|PATCH /v{major}/{namespace}/{resource}/{resource_id}
----

Alternatively, standards such as https://datatracker.ietf.org/doc/html/rfc6902[JSON Patch] MAY be implemented for https://tools.ietf.org/html/rfc5789[PATCH] requests. Rather than sending a partial representation of the resource, clients instead send a list of operations to be made on particular members or fields of the resource.

[source,http]
----
PATCH /widgets/abc123 HTTP/1.1
Host: api.example.com
Content-Length: ...
Content-Type: application/json-patch

[
  {
    "op": "replace",
    "path": "/a/b/c",
    "value": 42
  },
  {
    "op": "remove",
    "path": "/a/b/c"
  },
  {
    "op": "move",
    "from": "/a/b/c",
    "path": "/a/b/d"
  }
]
----

The value of the "path" field is a https://tools.ietf.org/html/rfc6901[JSON Pointer] that references the location within the target document where the operation is to be performed. For example, the path `/a/b/c` refers to the element "c" in the below JSON:

[source,json]
----
{
  "a": {
    "b": {
      "c": "",
      "d": ""
    },
    "e": ""
  }
}
----

The supported operations are "add", "remove", "replace", "move", "copy", and "test". To support partial updates to fixed-schema resources, APIs need to support only "add", "remove", and "replace" operations.

For most use cases for update operations, after a successful update both `PUT` and `PATCH` operations SHOULD respond with `204 No Content` status, with no response body. However, there may be use cases where it is preferable to return `200 OK` with an updated resource in the response body. For example, this may be required where clients need updates to system-calculated fields, or otherwise to optimize the client-server interactions. Alternatively, clients may opt-in to receiving a `200 OK` response with a response body by include the request header `Prefer:return=representation`.

Any update request (whether PUT or PATCH) that fails input validation MUST receive a `400 Bad Request` response. If clients attempt to modify read-only fields, or if the resource is in a non-updateable state, this is also a `400 Bad Request`. If there are business rules or validation contraints, eg for data type, length, etc., that are not satisfied, a `400 Bad Request` response is appropriate and in addition appropriate error codes and messages SHOULD be encoded in the response body. For situations that require interaction with downstream servers or external APIs or processes, returning the `422 Unprocessable Entity` status code may be more appropriate than `400 Bad Request`.

=== Deleting

In order to enable retries (eg. due to patchy connectivity), and for conformance with HTTP standards, `DELETE` operations MUST be implemented to be idempotent. This means that successful `DELETE` operations MUST always respond with `204 No Content`, even if the response is already deleted. Returning `404 Not Found` is not appropriate for `DELETE` operations in this scenario, as it suggests that the resource never existed at all. If necessary, clients can use `GET` to verify the resource exists prior to `DELETE`.

.Template
----
DELETE /v{major}/{namespace}/{resource}/{resource_id}
----

There may be use cases where a client expects resources to exist but they unexpectedly disappear. This could be because a resource expired, or because of some policy, such as a data retention policy that data is only retained for a maximum of two years. In these use cases, services MAY return a `410 Gone` error code in response to a request for a resource that no longer exists. Doing so provides the client with extra information (it tells the client that the resource had already been deleted) but the trade-off is that the code suggests a client error, which is not really the case.

For historical reasons, many web servers and HTTP client libraries do not expect a message body to be included in HTTP messages sent using the `DELETE` method. To support the widest possible range of clients, it remains good practice to not require DELETE requests to be accompanied by a payload. This is an OPTIONAL constraint, and is only REQUIRED if there are known to be clients that will be unable to support DELETE requests with payloads.

=== Creating

There are two ways to create resources:

* Using `POST` to create a resource but have the server create an identifier for it.
* Using `PUT` to create a full resource, including a unique identifier that is generated client-side.

.Template
----
POST|PUT /v{major}/{namespace}/{resource}/{resource_id}
----

`PUT` operations are idempotent by default, because the request payload has a built-in unique identifier in the form of the resource ID, generated by the client.

`POST` operations are NOT idempotent by default, and therefore there is risk that duplicates of the same resource may be created if the client retries a `POST` request. Where it is necessary to prevent this, clients MUST include a unique identifier for the _request_ message (eg. `request_id`). The server will use the request ID to make sure it processes only the first instance that it receives of each distinct request.

For `PUT` requests, system-calculated values such as `create_time` and `update_time` SHOULD be made optional and SHOULD be ignored on deserialization by the server. For `POST` requests, clients SHOULD be expected to omit these fields from the request body, and therefore the server SHOULD return `400 Bad Request` when such fields are included in the request content.

Otherwise, both operations SHOULD behave in the same way. Both `POST` and `PUT` payloads MAY include only a subset of input fields (only the required fields, for example), with the server filling in optional fields with default values. The number of required fields SHOULD be minimized as much as reasonably possible for the business case.

For both `POST` and `PUT` creation operations, successful outcomes MUST be signalled by a `201 Created` response, and a representation of the created resource MUST be returned in the response body — including any server-generated fields such as `create_time`.

Response messages SHOULD include a list of hypermedia links that represent all the available operations that can be performed on the newly-created resource. For example, if only `GET` and `DELETE` operations are available:

.Example response
----
{
  "data": {
    "id": "123e4567-e89b-12d3-a456-426614174000",
    "type": "visa",
    "number": "xxxxxxxxxxxx0331",
    "expire_month": "11",
    "expire_year": "2018",
    "first_name": "Joe",
    "last_name": "Shopper",
  },
  "links": [
    {
      "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.example.com/v1/vault/credit-cards/123e4567-e89b-12d3-a456-426614174000",
      "rel": "delete",
      "method": "DELETE"
    }
  ]
}
----

== Sub-resources and sub-collections

Sub-resources and sub-collections SHOULD be used sparingly and only where they are essential to expressing an accurate representation of an API's resource model.

.Templates
----
GET /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}
GET /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
POST /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
PUT /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
PATCH /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
DELETE /v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_id}
----

Where a resource of one type can exist independently of other resources of other types, these resources SHOULD be elevated to top-level resources in most use cases. If one type of resource cannot exist without another, this is a candidate to be lowered to a sub-resource.

Sub-resources require multiple identifiers (*composite keys*, in database lexicon) to be uniquely identified. To identify a sub-resource, the parent resource's identifier is required, as well as the sub-resource's identifier. This is a potential source of complexity for client applications, as they need to manage multiple identifiers for essentially the same resource.

Sub-resources SHOULD be used sparingly. The need to encode hierarchies of resources can increase the complexity of both server-side and client-side code. So, even where there is a tight coupling between two types of resources, look to promoting dependent resources to top-level resources (with single identifiers) where practical.

Where sub-resources are necessary or beneficial, try to have no more than one level of sub-resources - that's two levels of resources in total. Any more levels, and the complexity of client application code grows exponentially. Server code, too, needs to validate each level of resources, including how sub-resources related to their parent resources, and this complexity also grows exponentially with each additional tier.

Sub-resources MUST have a named type. `/v{major}/{namespace}/{resource}/{resource_id}/{sub_resource_id}` is not acceptable because `sub_resource_id` has ambiguous meaning. Linking su-resource identifiers to sub-resource types in the URL scheme also supports extensibility; other sub-resources can be more easily added in the future. This constraint also makes it easier to support different identifier naming conventions being used for different types of sub-resources, should that be necessary.

Sub-resources MAY be used as a solution to reducing the size of the parent resource, so segmenting a single large resource into multiple smaller resources. These types of sub-resources are known as *singleton sub-resources* and are identified by a static *sub-resource name* rather than a dynamically-generated identifier. Singleton sub-resources should be named using nouns in the singular form.

.Template
----
/v{major}/{namespace}/{resource}/{resource_id}/{sub_resource}/{sub_resource_name}
----

.Example
----
GET /v1/customers/devices/123e4567-e89b-12d3-a456-426614174000/vendor-information
----

There will be a one-to-one relationship between a resource and each of its singleton sub-resources. Singleton sub-resources are expected to always exist if the parent resource exists, though they may have null values. (Do not return `404 Not Found` if a singleton sub-resource does not exist, but simply return `null` for its value.)

Singleton sub-resources are not standalone resources, but are attached to their parent. Therefore, singleton sub-resources SHOULD be created and updated via the operations for their parent resource, rather than adding dedicated endpoints for them. Singleton sub-resources SHOULD NOT duplicate resources from other collections, but SHOULD be unique to their parent resource.

== Safeness and idempotency

The HTTP standards define the concepts of *safeness* and *idempotency* for HTTP methods.

A *safe* operation is one that does not modify the state of the resource. The HTTP standards define the `GET` and `HEAD` methods as safe methods, as these methods are intended not to request any kind of action other than data retrieval.

An *idempotent* operation is one that has the same effect on the state of the requested resources, regardless of how many times the operation is performed. Clients can therefore retry operations, sending identical requests multiple times, without worrying about data corruption or other unexpected side effects of doing the retries.

There are many use cases for clients to send identical requests multiple times. Commonly, this is done in retry mechanisms in response to failed connection attempts.

Building in idempotency is an important aspect of the design of any HTTP API. It makes it easier for clients to interact with the API, and improves the fault tolerance of the server-side system.

The HTTP standards define the `GET`, `HEAD`, `PUT`, and `DELETE` methods as being idempotent methods. HTTP APIs therefore MUST implement these operations to be idempotent.

The HTTP standards to not specify the `PATCH` method and being neither safe nor idempotent. However, it is strongly RECOMMENDED that `PATCH` operations are implemented to be idempotent.

`POST` operations are, by definition, neither safe nor idempotent. By default, executing an identical `POST` operation multiple times will create multiple discrete resources with different identifiers but duplicate data. There may be legitimate use cases where this is the desirable behavior. For example, a "like" operation on a social media post may not be required to be idempotent, as the desired behavior of sending multiple instances of the same request may be to toggle the user's "like" state of the post.

However, for most use cases in most APIs it is expected that `POST` operations will need to be implemented to be idempotent, to avoid unwanted duplicates of data entities being created.

Idempotency keys MUST be used to implement idempotency in `POST`, `PUT`, `PATCH`, and `DELETE` operations as required. An idempotency key is generated client-side and it is a unique identifier for each discrete request. It is used by the server to ensure that it processes only the first instance of each discrete request it receives. Subsequent requests with the same idempotency key are ignored, and the _same response is returned as for the first request_ (the server should assume that the client never received the first response).

Idempotency keys have other use cases too. They can double up as identifiers to correlate requests with responses, and supporting the *tracing* of cause-and-effect throughout distributed systems. For this reason, it is RECOMMENDED that idempotency keys be implemented universally across all operations in an API, including `GET` and `HEAD` operations.

The header field `X-Request-Id` SHOULD be used as the idempotency key. This is a widely-used header field, and it is used by many client libraries and frameworks to generate unique identifiers for requests.

[source,http]
----
POST /v1/payments/payouts HTTP/1.1
Host: api.example.com
Content-Type: application/json
Authorization: Bearer {token}
X-Request-Id: 123e4567-e89b-12d3-a456-426655440000

{
  // ...
}
----

If a `X-Request-Id` header is not provided by the client, the server MAY generate a unique identifier for the request. However, for most use cases it will be more appropriate for the service to respond with a `400 Bad Request` and a link to the relevant documentation.

Whether an idempotency key is generated client-side or server-side, it MUST be returned in response messages, also in the `X-Request-Id` header field.

Each idempotency key MUST be unique and MUST NOT be reused with other requests with different payloads. For simplicity of implementation, idempotency keys SHOULD be unique across all clients, too. For this reason, it is RECOMMENDED to use the UUID version 4 algorithm to generate idempotency keys. This probability of generating the same UUID twice is so low that it can be considered to be zero for all practical purposes.

If a client reused an idempotency key with a different request payload, the server MUST reply with a `422` status code.

To implement idempotency, servers are required to cache response payloads against their idempotency keys. The server MUST return the cached response payload for each subsequent request with the same idempotency key, even if the response status code is not `200 OK`. This is to ensure that the client receives the same response as it would have received if the request had not been retried.

Validity of idempotency keys HOULD be time-based, allowing for servers to optimize storage by periodically purging the cached response payloads associated with expired idempotency keys (which are persisted for longer). The key expiry time MAY vary depending on the use case, but a good default value is 24 hours. After this time, the server SHOULD return a `400 Bad Request` response for requests with expired idempotency keys.

== Actions

Some operations do not neatly fit into the RESTful model, in which CRUD-like operations are performed against discrete types of resources. Classic examples include endpoints to "login", "logout", "reset password", "charge a credit card", "send a notification", and to "receive a webhook event".

These standalone operations, which are not scoped to any particular resource, are referred to as "actions" in this technical standard. Elsewhere, they may be referred to by other names such as "controllers", "procedures", "operations", or simply "endpoints".

Actions tend to be mapped directly to specific controller methods in the server-side code, and for this reason they are the HTTP API equivalent of RPC (remote procedure call) methods.

Actions MUST be performed using the HTTP's `POST` method, except for actions that retrieve read-only data, in which case `GET` MUST be used to support caching. The name of the action SHOULD suggest the type of CRUD operation to be be performed, rather than this being baked into the semantics of the HTTP method.

Action names should be like function names. Use lowerCamelCase with the first segment being a verb. The rest of an action's name should, typically, be in the singular forms. Examples: `activateAccount`, `cancelSubscription`, `validateEmail`, `acceptInvitation`, `denyRequest`. This naming convention helps to distinguish actions from resource-oriented endpoints, which are named using hyphen-delimited slugs.

.Template
----
POST|GET /v{major}/{namespace}/{action}
----

Actions and resources MAY coexist in the same namespaces. However, a good practice is to create a collection of actions within each namespace. Collections of actions SHOULD be named "actions".

.Template
----
POST /v{major}/{namespace}/actions/{action}
----

This helps to distinguish actions from resources in each namespace. In addition, a `GET /v{major}/{namespace}/actions` endpoint MAY be provided to list all available actions in a namespace, similarly to how a list of available resources within a namespace is retrieved.

A common use case for actions is to mutate the state of multiple resources within its namespace in the same operation. These are known as *composite actions*. An example would be a "refund" action that would change the state of a payment, the customer's account, and the merchant's account, and the action would not be considered to be fulfilled until all of these changes are committed. Another example of a composite action would be the implementation of a search function that operates across multiple resource types.

Composite actions may be implemented for both performance optimization and usability reasons.

Some actions may be transient — that is, they do not mutate the state of any resources, or create new ones. An example might be a "dry run" action that validates the input data for a subsequent operation, such as a payment.

If actions return read-only data, such as logs or reports, these actions SHOULD use the `GET` method, instead of `POST`, to provide opportunities for caching. (`POST` responses are not cacheable.)

There may be use cases for attaching actions to specific resources, or even to sub-resources. For example, where a particular state change requires a comment to be provided, it might make sense to require the client to input the comment via a dedicated action, subsequent to the state change being fulfilled via a conventional resource operation. There may be technical constraints for doing so (for example, message bodies SHOULD NOT be sent with `DELETE` requests, providing no opportunity to input a comment for that type of operation). More commonly, resource-scoped actions will be used to separate operations that are fundamentally _business processes_ from operations that change the core state of the resources themselves. For example, for auditing purposes the business may require freeform comments to be attached to subscription cancellations. Since the comments would not be part of the model of a subscription resource, a resource-scoped action would be appropriate here.

.Template
----
POST /v{major}/{namespace}/{resource}/{resource_id}/actions/{action}
----

For successfully executed actions, `204 No Content` will be the most appropriate response status code in most cases (with no body content). However, if the client needs to capture some information from the result of an action, a `200 OK` response with a response body MAY be returned. Actions MUST not return updated states for any resource, but MAY return things like statuses for discrete operations such as a payment transaction.

.Action-oriented APIs versus resource-oriented APIs
****
There are risks and benefits to using actions in HTTP APIs. Action-oriented APIs can be harder to scale than resource-oriented ones. The number of URLs can grow much more quickly, producing increased configuration complexity for routing and externalization, among other things. There tends also to be fewer opportunities to promote code reuse in automated tests (because actions tend to have greater variability in their inputs and outputs than operations performed on resources).

However, for most HTTP APIs, not everything fits neatly into the RESTful architectural style. Some operations are simply better expressed as actions.

The preference is to design as much of an API as possible around a resource-oriented model, and augment the API with actions where specific operations do not fit neatly into that model. We should not try to force everything into the resource model just for the sake of purity of the API design.
****

== Concurrent operations

A common issue in network API design is how to manage concurrent operations. There is always the potential for multiple clients to attempt to modify the same resource at the same time. This can lead to data corruption or lost updates (where one client's changes are overwritten by another client's changes).

These are not always issues, but where they are, APIs will need to implement concurrency control mechanisms. The appropriate mechanism will depend on the specific use case. But common patterns typically involve the use of ETags.

ETags (Entity Tags) are used to implement a strategy known as *optimistic concurrency control*. They are used to prevent accidental overwrites — the "lost update" problem, in which the most recent update always wins — by allowing clients to check if a resource has already been modified before requesting further mutations to that resource.

ETags themselves are unique identifiers assigned by a web server to a _specific version_ of a resource. When a resource changes, its ETag changes. ETags are returned in HTTP headers, allowing clients to detect changes to resources that originated from other clients.

When a client requests a resource, it receives an `ETag` header with a value that represents the current version of the resource represented in the message body. This may be any arbitrary value, but it is typically implemented as a hash of the resource's content.

----
ETag: "<etag_value>"
----

When the client subsequently requests an update to the resource, it includes in the request the ETag of the last version of the resource that it has. This is sent in the `If-Match` header.

The server then checks if the ETag in the request matches the current version of the resource known to the server. If they match, the update proceeds. If they do not match, it means another client has updated the resource in the meantime, and the update fails with a `412 Precondition Failed` status code.

== Asynchronous operations

Certain types of operations may require processing of requests in an asynchronous manner. In general, synchronous operations should be preferred over asynchronous ones, as they simplify implementations on both the server-side and client-side. But there are some use cases where asynchronous operations are necessary. Asynchronicity is particularly advantageous in long-running tasks, such as image processing and video transcoding. It is also useful in operations that require interaction with external systems, such as sending emails or SMS messages, where the response time of the external system is unpredictable and where the client requires only confirmation that the message we _sent_ and does not require an immediate understanding of the outcome of that operation.

In implementing asynchronous operations, it is RECOMMENDED to conform to the following best practices.

Responses to resource creation, update, and deletion operations SHOULD return the `202 Accepted` status code. This indicates that the request has been accepted for processing, but the processing has not been completed.

The response body MAY include hypermedia links to the created or updated resource, and there are two possible approaches to implementing this in the context of asynchronous operations. The first option is to include the final URL of the resource, from where clients can `GET` the latest representation of the resource in the normal way. This can be a good option in scenarios where the resource's ID and path are already known. If a newly-created resource is not yet ready, or if the resource has been deleted, the final URL SHOULD return the HTTP status code `404 Not Found`. Clients simply keep polling the provided endpoint until it is confirmed that the resource has been mutated as expected.

[source,json]
----
{
  "rel": "self",
  "method": "GET",
  "href": "/v1/namespace/resources/{resource_id}"
}
----

A second option is to return a temporary URL where the status of the queued operation may be obtained via some kind of temporary identifier.

[source,json]
----
{
  "rel": "self",
  "method": "GET",
  "href": "/v1/queue/requests/{request_id}"
}
----

It is RECOMMENDED that all HTTP APIs that implement asynchronous processing also support a single *webhook* that clients may optionally choose to implement to receive push notification of any asynchronously-updated resources, or the results of any asynchronously-processed actions. This offers a third option for clients to keep their state synchronized with changes — whether triggered by asynchronous operations or even other clients — on the server.

It is possible to support both synchronous and asynchronous processing on the same endpoints. The RECOMMENDED design is to support synchronous processing by default but allow clients to opt-in to asynchronous processing using the `Prefer=respond-async` header.

== Cached responses

HTTP API servers MUST provide guidance to clients on appropriate caching of response messages. Clients MAY cache responses based on the guidance issued by the server.

Client-side caching is typically guided using the `Cache-Control` header.

// TODO: More details of possible implementation strategies.

== Headers

=== Non-standard headers

Non-standard headers SHOULD be prefixed with `X-` to indicate that they are custom headers, and to avoid potential conflicts with future standard headers.

Examples:

* `X-Request-Id`: A unique identifier for the request, used for logging and tracing,and to implement idempotent operations.

* `X-Correlation-Id`: A unique identifier to correlate requests and responses through distributed systems. This may be useful in scenarios where a client does not supply an `X-Request-Id` header, or where processes are initialized by the system (such as batch processes or scheduled jobs) rather than by a user.

* `X-Client-Id`: A unique identifier for the client application making the request. This may be useful where you want to track the behavior of a specific client application, rather than a specific user.

=== `Prefer` header

HTTP APIs MAY support the `Prefer` header. This standard HTTP header is specified in https://tools.ietf.org/html/rfc7240[RFC 7240]. It is used by client to opt-in to specific behaviors when the server is processing the client's requests.

The `Prefer` header is useful for a number of use cases. Perhaps the most common use case is to allow clients to opt-in to receiving a response body, encoding up-to-date resources, for requests that would not otherwise receive one. For example, instead of `PUT` and `PATCH` requests receiving a `204 No Content` response by default, clients can opt-in to receiving a `200 OK` response with the updated resource in the response body. This can be useful for clients that need to capture system-generated fields, such as `create_time` and `update_time`, or where clients benefit from receiving up-to-date representations of resources that are particularly volatile (they might have been updated by other clients).

By default, HTTP APIs should return full representations of requested and updated resources. But sometimes the client does not need the full representation and the client-server interaction can therefore be optimized by returning partial representations of resources. This can be particularly beneficial in collections in which individual resources are large objects in their complete representations. Clients may therefore choose to fetch minimal or summarized lists of resources, and then fetch the full representations of individual resources as-and-when needed.

The `Prefer: return=minimal` header MAY be used for this purpose. The definition of a "minimal" representation is left to the discretion of the service, but it SHOULD be documented as part of the API's interface specification.

To gives more clients more granular control over the subset of resource data that they receive, API services MAY support a query parameter named `fields`. This accepts a comma-separated list of field names that the client is interested in. The response body SHOULD include only the fields that are listed in the `fields` query parameter, plus any required fields that the server always provides.

----
GET https://api.example.com/v1/users/bob?fields=department,title,location
----

The `fields` pattern, if implemented, SHOULD be supported globally across all resources and collections.

The `fields` query parameter SHOULD NOT be used in conjunction with the `Prefer: return=minimal` header. Clients SHOULD be expected to supply one or the other, or neither, but not both.

== Content

The content, or payload, of HTTP request and response messages SHOULD be in the JSON format, for the majority of regular use cases. JSON is natively supported by most modern programming languages, it is human-readable as well as machine parsable, and has become the _de facto_ standard for encoding data in HTTP APIs.

=== Structure

The structure of JSON payloads SHOULD be consistent across all endpoints in an API. This consistency makes it easier for clients to understand the API, and to write reusable code for interacting with it.

As for what that structure should look like, there is no universal standard. There have been some attempts to standardize JSON API structures, notably the Open Data (OData) protocol (https://www.odata.org/), which is the closest thing we have to an industry standard. But OData is an overly complex system for most use cases, and for this reason it is not widely adopted. Lighter weight standards include JSON API (https://jsonapi.org/), and indeed this is the main inspiration for the JSON payload structure documented below — which is this technical standard's RECOMMENDED structure for HTTP API message content.

Both request and response payloads, where a payload is included in the HTTP message, MUST have a field named "data". Its value MUST be an object, which MAY be empty. Therefore, the minimum REQUIRED payloads is as follows:

.Minimal REQUIRED payload.
[source,json]
----
{
  "data": {}
}
----

OPTIONAL top-level fields and their types are:

* "meta" (object)
* "links" (array)
* "messages* (object)

[source,json]
----
{
  "meta": {},
  "data": {},
  "links": [],
  "messages": {}
}
----

The "links" and "messages" fields MAY be included in HTTP response messages but MUST NOT be accepted by servers when included in clients' HTTP request messages. The "meta" field MAY be included in both HTTP request and response messages. The "data" field MUST be included in both HTTP request and response message that have a payload.

==== "meta"

The "meta" field encapsulates metadata about the response or request. This metadata is not part of any representations of resources included in the "data" field, but it MAY hold additional information about those resources.

The "meta" field is an object, which MAY be empty.

The "meta" field MAY include any number of key-value pairs. The keys SHOULD be strings. The values MAY be any native JSON type, including other objects and arrays.



The request and response payloads of an HTTP API SHOULD be composed from a consistent set of common types for representing data.

It is RECOMMENDED to use JSON Schema to define this library of common types. JSON Schema is a vocabulary that allows you to annotate and validate JSON documents. It is widely supported by many tools and libraries, and can be used to generate documentation, code, and tests.

See link:./ts-7-json-schema.adoc[TS-7: JSON Schema] for more information.

== Versioning

HTTP APIs SHOULD have a major version number that is incremented whenever there are breaking changes in the API. The major version number SHOULD be encoded in the first path segment of the URL.

.Template
----
/v{major}
----

.Example
----
/v1
----

Use the *expanding contract* pattern to maintain backwards compatibility with clients, while incrementally evolving the API's design and capabilities. This is also known as the *additive* approach to building programmatic interfaces.

In practice, this means:

* Breaking changes MUST NOT be made to APIs that are already in use.

* Developers MUST NOT add new required parameters to existing APIs.

* Developers MUST NOT remove existing required parameters.

* Developers MUST NOT change the meaning of existing parameters.

* APIs MUST be designed to be extensible.

A good example of a scalable API design is one that avoids array of scalar data types (strings, integers, etc.). Consider the following example:

[source,json]
----
"countries": [
  "Brazil",
  "France"
]
----

This data structure is impossible to extend without introducing breaking changes. Always prefer arrays of objects, eg.:

[source,json]
----
"countries": [
  { name: "Brazil" },
  { name: "France" }
]
----

Breaking changes include any changes to the request or response message formats, changes to the semantics of the API, or changes to the behavior of the API.

Where breaking changes are unavoidable, the breaking changes MUST be implemented in a new major version of the API. The old version of the API MUST be maintained for a reasonable period of time to allow clients to migrate to the new version. APIs MUST have a documented *life cycle policy*, which describes the support and maintenance of each major version of the API.

== Documentation and interface definition

HTTP APIs MUST be thoroughly documented.

// TODO: Add notes on preferred IDLs such as OpenAPI.

''''

== References

* http://tools.ietf.org/html/rfc7231[Hypertext Transfer Protocol (HTTP/1.1) - RFC 7231]

* https://tools.ietf.org/html/rfc6585[Additional HTTP Status Codes - RFC 6585]

* https://tools.ietf.org/html/rfc3986[Uniform Resource Identifier (URI): Generic Syntax - RFC 3986]

* https://tools.ietf.org/html/rfc6570[URI Template - RFC 6570]

* https://tools.ietf.org/html/rfc5988[Web Linking - RFC 5988]

* http://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA Link Relations]

* http://techbus.safaribooksonline.com/9780596809140[RESTful Web Services Cookbook] by Allamaraju, S.

* http://json.org/[Introducing JSON]

* https://tools.ietf.org/html/rfc7159[JSON Data Interchange Format as described in - RFC 7159]

* http://swagger.io/specification/[OpenAPI Specification v2.0]

* http://semver.org/[Semantic Versioning 2.0.0]

* https://www.ietf.org/rfc/rfc2388.txt[Returning Values from Forms: multipart/form-data - RFC 2388]

* https://tools.ietf.org/html/rfc2387[The MIME Multipart/Related Content-type - RFC 2387]

== Acknowledgements

* https://github.com/jharmn/api-standards[Jason Harmon's API standards, based on PayPal's API design guidelines]
