= TS-7: JSON Schema

JSON Schema is a vocabulary that allows you to annotate and validate JSON documents. It is used to define the structure of JSON data for the purpose of validation and documentation.

JSON Schema SHOULD be used to define a library of common types and structures, from which request and response payloads are composed in link:./ts-6-http-api.adoc[HTTP APIs] and other protocols for data exchange.

== Extending types

API developers are encourage to use the library of common types "as is". However, types MAY be extended, and there are several possible ways of achieving this:

* Use *composition*: Use `$ref` to reference a common type from one of the properties of your type, and add more properties to your type as needed.

* Use the `allOf` keyword from http://json-schema.org/latest/json-schema-validation.html#anchor82[JSON Schema Draft 4]. (This replaces the `extends` keyword that was proposed in JSON Schema Draft 3.) However, note that not all code and documentation generator tools recognize this keyword at this time.

* Make a copy of the common type and modify it as needed. This is the least preferred option, as it can lead to duplication and inconsistency.
