= TS-10: System Design
:toc: macro
:toc-title: Contents

This technical standard describes general software architectural design best practices and
standards.

toc::[]

== Quality attributes

All software systems MUST be designed with the following performance qualities in mind. Desirable performance qualities are presented here in order of importance, from most to least. These qualities are not mutually exclusive and often overlap in practice.

=== Reliability

Reliability is the ability of a system to consistently perform its core functions correctly. This quality is primarily about *correctness*: does a system's actual operations meet their expected behavior, as specified in the system requirements.

*Data integrity* – which means that a system correctly processes and maintains data throughout its lifecycle – is a critical aspect of reliability.

=== Resilience

Also known as fault tolerance, resilience is the ability of a system to recover from failures and continue operating. This includes *gracefully handling* network issues, unexpected exceptions, and other disruptions.

A system is resilient when it has *high availability*.

=== Speed

Fast software changes the behavior of its users. It reduces the cognitive friction involved in using the software, allowing users to stay focused on their tasks, and so to be more productive.

Conversely, slow software limits us, perhaps more than most people realize. Think, for example, when was the last time you got any meaningful work done on airplane Wi-Fi?

This is why speed must be prioritized in user experience design.

Fast, reliable software also has a competitive advantage. The speed and reliability of Instagram have no doubt played big roles in its success, relative to the many other photo sharing apps that competed with it in its early days.

In order to make things fast, you often have to do complex things behind the scenes. Instagram, for example, optimistically uploads users' photos while they are still typing the captions for them, so the subsequent user-initiated upload operation feels instantaneous.

Fast is not just a technical accomplishment. It subliminally signals quality and reliability to users.

=== Simplicity

Achieving fast software also demands a relentless focus on the simplicity of the product design.

Companies that do fast very well tend also to have very focused products. That's because the effort required to make software fast often requires stripping away non-essential features. Consider, for example, how a streamlined project management tool like Linear loads quickly and has higher overall perceived performance than heavier-weight enterprise applications like Workday.

Simple software signals to the user that you've thought about what _really_ matters to them, and eliminated everything else. Simplicity commands respect.
