= TS-13: Code Design
:toc: macro
:toc-title: Contents

This technical standard covers low-level concerns related to the structure and formatting of code. It covers topics such as naming conventions, commenting best practices, and object-oriented design principles.

These guidelines are language-agnostic. This technical standard is meant to be relevant for any general-purpose, high-level programming language (Python, Java, JavaScript, etc.). Some of the content will also be relevant for lower-level languages, such as shell scripting languages like Bash.

For higher-level design concerns, such as architecture and design patterns, see link:./012-application-architecture.adoc[TS-12: Application Architecture] and link:./010-system-design.adoc[TS-10: System Design].

== Naming things

Generally, err on the side of clarity over brevity. Do not truncate or abbreviate the names of things where doing so would decrease understandability of the code.

The names of all things – functions, variables, etc. – SHOULD be descriptive in the places in which those things are _used_, not only in the places where they are _defined_. This means you can't rely on adjacent comments to document the meaning of things where they are declared, because those names will appear in other code contexts where those descriptions are not present.
toc::[]
