= TS-13: Code Design
:toc: macro
:toc-title: Contents

This technical standard covers low-level concerns related to the structure and formatting of code. It covers topics such as naming conventions, commenting best practices, and object-oriented design principles.

These guidelines are language-agnostic. This technical standard is meant to be relevant for any general-purpose, high-level programming language (Python, Java, JavaScript, etc.). Some of the content will also be relevant for lower-level languages, such as shell scripting languages like Bash.

For higher-level design concerns, such as architecture and design patterns, see link:./012-application-architecture.adoc[TS-12: Application Architecture] and link:./010-system-design.adoc[TS-10: System Design].

toc::[]

== Naming things

Generally, err on the side of clarity over brevity. Do not truncate or abbreviate the names of things where doing so would decrease understandability of the code.

The names of all things – functions, variables, etc. – SHOULD be descriptive in the places in which those things are _used_, not only in the places where they are _defined_. This means you can't rely on adjacent comments to document the meaning of things where they are declared, because those names will appear in other code contexts where those descriptions are not present.

== Comments

In higher-level programming languages, the higher abstractions allow programmers to express their design through modules, function and object names, data structures, and other constructs. Instead of relying on comments to explain the code, it is considered best practice to try to design the code in a way that it clearly articulates _what_ it does, without additional annotations.

Therefore, in higher-level programming languages, inline comments tend to be used quite sparingly, used to explain only the most complex algorithms, or why certain design patterns where chosen over more obvious ones, and so on.

Lower-level languages, like shells and other scripting languages, provide fewer opportunities to develop self-explanatory code. Indeed, the syntax of lower-level languages can often be cryptic and non-intuitive. For this reason, it is strongly RECOMMENDED that things like shell scripts be liberally commented.

Remember, *the purpose of comments is to reduce cognitive overhead*. Whatever the language or level of abstraction, add comments where they make things easier to understand, or where you want to communicate important information that cannot be ascertained from the code alone.

Remove comments that are superfluous, redundant, or that do not add any tangible value.

Removing comments does not necessarily make the code "cleaner". Even if things get messier with comments, this is usually preferable to losing valuable knowledge. Ignore what Uncle Bob says and adopt the view that "comments are mostly good".

_If in doubt: leave a comment!_
