= TS-15: Network APIs
:toc: macro
:toc-title: Contents

This technical standard defines broad guidelines for network APIs of all kinds – REST, GraphQL, gRPC, etc. The emphasis here is on considerations such as security and reliability, and especially performance optimization.

This technical standard also covers guidelines for implementing abstractions for network APIs in application code.

toc::[]

== Abstracting network APIs in application code

In application code, network APIs SHOULD NOT be overly abstracted such that the network is hidden from application developers. One of the dangers of abstracting network calls behind "in memory" object calls, for example, is that it can lead to the false assumption that network calls are instantaneous. (The assertion that "latency is zero" is the second of the famous https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing[fallacies of distributed computing].)

When network calls are abstracted too much, it can lead to a lack of awareness about the underlying network operations and their potential latencies and failure modes. This in turn can lead to application logic that does not account for network latency, that wastes bandwidth with unbounded payloads, or that does not gracefully handle network failures. For distributed systems to be fault tolerant and robust, applications are required to implement patterns such as timeouts, retries, and fallbacks.

So, it is better practice to design application code to reflect the underlying network operations and their potential latencies, even if this means more verbose application code. Aim for *network transparency* in application code, meaning that network operations are explicit and visible in the codebase.
