= TS-16: JSON Schema
:toc: macro
:toc-title: Contents

This technical standard sets out some guidelines for JSON schema. The emphasis on this technical standard is on _designing_ JSON schema, though there is also some information on using published JSON schemas such as JSON-LD.

JSON Schema provides a vocabulary for describing the structure of JSON data. Documentation, code, and other artifacts can be generated from JSON Schema definitions, but the primary use case if to validate JSON documents.

JSON schema is commonly used to define the structure of data transferred between systems via network APIs. It may also be used for input validation, to define interfaces for data structures constructed at runtime, and to define data persistence schema (eg. document stores).

toc::[]

== Versions

JSON Schema was originally defined as an http://tools.ietf.org/html/draft-zyp-json-schema-04[IETF standard], but is now maintained as a https://json-schema.org/[community project]. Versions 00 through 04 were published as IETF drafts, while draft-05 moved to the community project.

The current version of JSON Schema is `Draft 2020-12`. It is RECOMMENDED to use this version for new projects. The metaschema for this version is `https://json-schema.org/draft/2020-12/schema`.

== Cross-references

JSON Schema defines a https://www.learnjsonschema.com/2020-12/core/ref/[`$ref`] keyword to link schema from other schema.

.Example
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Locale",
  "description": "Locale, composed from a BCP-47 language tag, ISO-3166 alpha-2 country code, and Olsen IANA timezone ID.",
  "type": "object",
  "required": [
    "country_code",
    "language"
  ],
  "properties": {
    "country_code": {
      "$ref": "country-code.schema.json"
    },
    "language": {
      "$ref": "language-code.schema.json"
    },
    "timezone": {
      "$ref": "timezone.schema.json"
    }
  }
}

----

As per the JSON Schema documentation, it is RECOMMENDED to not require client applications to automatically resolve schema that are referenced from other schema via the `$ref` attribute. Instead, it is RECOMMENDED that JSON Schema publishers automatically swap `$ref` properties for inline schema, using a build step.

A https://github.com/sourcemeta/jsonschema/blob/main/docs/bundle.markdown[command-line tool] is available to do this.

