= TS-17: Messages and Events
:toc: macro
:toc-title: Contents

This technical standard covers best practices for designing and implementing messages and events in event-driven architectures, including schema design, reliability, security, and developer experience.

See also the *webhooks* section in link:./016-http-apis.adoc[TS-16: HTTP APIs].

toc::[]

== Message schema

In message-driven architectures, messages are the primary means of communication between different components and services. Designing a robust, flexible, scalable, and maintainable message schema is a crucial aspect of the design of distributed systems with asynchronous message-based communication patterns.

Ideally, all asynchronous communication between services within a distributed system should use a consistent, versioned JSON schema for all types of messages. Standardization on the high-level design of all messages across an entire system reduces overall complexity, encourages code reuse via shared libraries, and improves interoperability between services.

It is RECOMMENDED to model all types of messages using a unified schema. This means defining an extensible structure that can scale to represent different kinds of messages. Broadly, there are three categories of messages: events, commands, and queries. Events represent things that have happened in the service emitting the event (eg., `user.created`, `order.placed`). Commands represent requests for operations to be performed by other services (eg. `sendEmail`, `refundOrder`). Queries are requests for data (eg., `getUserDetails`, `listOrders`). A well-designed message schema will accommodate all three types of messages in a consistent way.

=== Standards

Some industry standards are starting to emerge for message schema.

https://www.standardwebhooks.com/[Standard Webhooks] is the most prominent initiative to establish common conventions for event schemas. The guidelines target webhooks – ie. messages transmitted between systems owned by different parties – though they are useful also for internal communication design. Standard Webhooks captures common conventions used for event naming, payload structure, security (signatures), and delivery patterns.

https://cloudevents.io/[CloudEvents] is another standard for event schemas, developed under the https://github.com/cncf[Cloud Native Computing Foundation]. It's focus is on improving interoperability across different cloud providers and platforms. It does this by specifying a common format for event data and metadata that can be used across wide variety of messaging and transport protocols.

The remainder of this technical standard draws inspiration from both of these standards, but does not mandate their use.

=== Data interchange formats

It is RECOMMENDED to use JSON as the data interchange format for messages, due to its widespread adoption, human readability, and compatibility with all mainstream programming languages and platforms.

Other formats, such as XML or Protocol Buffers, may be used in specific scenarios where their features are desired. But JSON SHOULD be the default go-to choice for most services.

=== High-level design

There are two parts to a message schema: the main payload, and metadata for the message container itself. These two parts SHOULD be clearly differentiated in the schema.

The following high-level design achieves this separation.

----
{
  // Metadata:
  "messageId": "string",      // Unique identifier for the message.
  "messageType": "string",    // Message type: "event", "command", or "query".
  "timestamp": "string",      // Time of message delivery.
  "schemaVersion": "string",  // Version of the message schema.
  "correlationId": "string",  // Correlation ID for tracing.

  "event": "string",          // Event type (eg., "user.created").
  "command": "string",        // Command name (eg., "sendEmail").
  "query": "string",          // Query name (eg., "getUserDetails").

  "data": {
    // Payload:
    "field1": <value>,        // Payload schema is specific to each
    "field2": <value>,        //   type of event, command, and query.
    "field3": <value>
  }
}
----


----

