= TS-17: Messages and Events
:toc: macro
:toc-title: Contents

This technical standard covers best practices for designing and implementing messages and events in event-driven architectures, including schema design, reliability, security, and developer experience.

See also the *webhooks* section in link:./016-http-apis.adoc[TS-16: HTTP APIs].

toc::[]

== Message schema

In message-driven architectures, messages are the primary means of communication between different components and services. Designing a robust, flexible, scalable, and maintainable message schema is a crucial aspect of the design of distributed systems and their internal communication patterns.

Ideally, all asynchronous communication between services within a distributed system should use a consistent, versioned JSON schema for all types of messages. Standardization on the high-level design of all messages across an entire system reduces overall complexity, encourages code reuse via shared libraries, and improves interoperability between services.

It is RECOMMENDED to use JSON as the encoding format for messages, due to its widespread adoption, human readability, and compatibility with most programming languages and platforms. Other formats, such as XML or Protocol Buffers, may be used in specific scenarios where their features are desired, but JSON SHOULD be the default go-to choice for most services.

It is also RECOMMENDED to model all types of messages using a common JSON schema. This means defining a unified structure that can scale to represent different kinds of messages.

Broadly, there are two categories of messages: events and commands. Events represent things that have happened in the service emitting the event (eg., `user.created`, `order.placed`), while commands represent requests for actions to be performed by other services (eg., `getUserDetails`, `listOrders`). A well-designed message schema will accommodate both types of messages in a consistent way.

=== Standards

Some industry standards are starting to emerge for message schema.

https://www.standardwebhooks.com/[Standard Webhooks] is the most prominent initiative to establish common conventions for event schemas. The guidelines target webhooks, ie. messages transmitted between systems owned by different parties, though they are useful also for internal system design. Standard Webhooks captures common conventions used for event naming, payload structure, security (signatures), and delivery patterns.

https://cloudevents.io/[CloudEvents] is another standard for event schemas, developed under the https://github.com/cncf[Cloud Native Computing Foundation]. It focuses on interoperability across different cloud providers and platforms, defining a common format for event data and metadata that can be used across various messaging and transport protocols.

The remainder of this technical standard draws inspiration from both of these standards, but does not mandate their use.

