= TS-18: Source Control

== Repositories

All code and configuration MUST be stored in a version control system. The RECOMMENDED version control system is Git.

For each repository, there MUST be a single centralized repository that is the "source of truth" for the codebase. This is known as the *upstream repository*. It is from this that downstream repositories are cloned for development purposes.

The boundaries of code repositories SHOULD NOt be arbitrary. Instead, the boundaries of repositories SHOULD map directly to the boundaries of applications or services, which in turn SHOULD map directly to the boundaries of the teams that are responsible for the development and maintenance of those applications and services. Thus, each repository SHOULD be owned by one team.

The objective of repository design is that a developer SHOULD be able to check out a repository, run a build script contained within it, and have a complete working system running in a local development environment (also configured in the repository) without any external dependencies.

In addition, a developer SHOULD be able to checkout any version from the repository's history and build, run, test, and deploy that version – also without relying on any external dependencies that are not configured in the same repository.

If the application calls other external systems or services, the application MUST operate without error when those external systems are unavailable. It SHOULD also be possible to run the application in a "test mode" that mocks all external dependencies.

=== Mono-repos

Mono-repos MAY be used to encapsulate two or more related software components, and in fact they are REQUIRED in some contexts.

If the goal of repository design is for developers to be able to check out everything they need to build, run, test, and deploy (to all environments) the application under source control, then a mono-repo MUST be used when two or more discrete applications or services are so tightly coupled that they must always coexist – ie. be built, run, tested, and deployed together.

In a mono-repo, all applications and services SHOULD have the same version numbers. The idea is that, within a repository, everything at the same revision should work together. Thus, the boundaries of repositories define the relationship between highly coupled components.

For example, if v17 of Service A and v12 of Service B represent v2 of our application, those two services SHOULD go in the same repository (ideally). Unless the application can "fail gracefully" without one or the other component, ie. it is not tightly coupled to either.

It MUST also be possible to run a deployment from a single repository, even if the same deployment ships different things to run in different processes. It MUST NOT be necessary to coordinate deployments, even in sequence, across multiple repositories.

Normally, all code within the same repository SHOULD follow a consistent coding standard. The exception is for mono-repos, which are repositories that encapsulate the code and configuration for more than one application. Since different applications MAY be written in different programming languages and for different runtime platforms, the coding standards may differ between applications within a mono-repo.

== Repository naming conventions

A clear repository naming convention, standardized across teams and projects, makes it easier to:

* Identify the purpose and content of a repository at a glance.
* Search and retrieve repositories more effectively.
* Implementation automation more effectively. For example, CI/CD workflows dynamically adjust their processes based on a repository's naming.

It is RECOMMENDED to:

* Prefix repositories with the name of the team, subdomain, or project. Best of all, use internal code names to identify projects, which will not change even if the public-facing branding changes. So, for the website for a product branded "Initech", the repository name might be `zeus-website`.

* For repositories that are not scoped to any particular project or team, but which is relevant to the whole organization, use a generic prefix like `common`, `shared`, or `global`, or the name of the organization itself.

* Suffix repositories to identify the type of content they contain. For example, `app`, `config`, `docs`, `infra`, `lib`, `test`, `tool`, etc.

* Do not reference the technology stack in the repository name. The technology stack is an implementation detail that can change over time, and it does not help to identify the contents of the repository. If you want to identify the technology stack, hosted repository services like GitHub and GitLab also allow you to add descriptions, metadata, labels, tags, or topics to repositories.

* Use lower case ASCII letters only. Avoid including numbers and do not include special characters. Use hyphens to separate words in the repository name.

* If different versions of a software component are maintained in different repositories, suffix the repository names with a version identifier, eg `-legacy`, `-next`.


== References

* https://nvie.com/posts/a-successful-git-branching-model/[GitFlow] — This branching-and-merging strategy, documented by Vincent Driessen in 2010, was designed for the intermittent release of versioned software. It is characterized by its two main branches, `master` and `develop`. GitFlow was not intended for continuously delivered, singly versioned software like web apps, though it has been widely adopted for that purpose.

* https://about.gitlab.com/2014/09/29/gitlab-flow/[GitLab Flow] — This workflow offers a better template for the source code management of continuously delivered web-based software systems.

* https://scottchacon.com/2011/08/31/github-flow.html[GitHub Flow] — This is a minimalist workflow, ideal for personal and small open source projects. It uses a single `main` branch, and feature branches are created for each new feature or bug fix.

* https://www.atlassian.com/blog/archives/simple-git-workflow-is-simple[Atlassian's Simple Git Workflow] — This uses feature branches but with the rebase strategy suggested for integrations back to the main branch. It also adds environment branches and release branches.

* https://www.atlassian.com/git/tutorials/comparing-workflows[Comparing Git workflows] — This article, also from Atlassian, provides a good overview of the main design choices to be made when establishing a Git workflow.
