= TS-19: Source Control

The following technical standards cover the use of source code management (SCM), also known as source control or version control systems.

https://git-scm.com/[Git] is the _de facto_ industry standard for source control. These technical standards assume that Git is used, but any similar decentralized version control systems, such as Mercurial or Fossil, MAY be used instead.

Source control SHOULD be tightly integrated with issue tracking. Using a combination of the two systems make it much easier to manage changes in source code and configuration. All-in-one development operations services like GitHub, GitLab, Azure DevOps, and Atlassian's software suite, provide deep integrations between source control and issue tracking out-of-the-box. See also link:./018-issue-tracking.adoc[TS-18: Issue Tracking].

Source control is also the cornerstone of continuous integration and continuous delivery practices. Neither are really possible without a well-designed process for using source control systems. See also link:./018-issue-tracking.adoc[TS-20: GitHub Actions].

