= TS-19a: Bash
:toc: macro
:toc-title: Contents

This technical standard extends link:./019-sh.adoc[TS-19: Unix Shells] with guidelines for using the https://www.gnu.org/software/bash/[Bash shell] specifically.

These guidelines assume that you are writing scripts that are specifically intended to be executed by Bash, and not other shells.

toc::[]

== Shebang (`#!`)

The first line of a Bash file MUST be the shebang (`#!`, also known as a hashbang). This indicates to the shell which interpreter to use. The classic Bash shebang is:

----
#!/bin/bash
----

But the env-style shebang is RECOMMENDED:

----
#!/usr/bin/env bash
----

The difference between the two is that the classic shebang bets everything on one path, while the env shebang looks for the Bash binary in more places, and thus the script has a greater chance of being successfully run across different environments.

[TIP]
======
If you're using the classic Bash shebang, and if you get an error similar to "command not found" when running the script, then almost certainly the path to the Bash interpreter is wrong for the current system. Use `whereis bash` or `find ./ -name bash` to find the path to the `bash` executable. Some possible locations include:

* `/bin/bash`
* `/sbin/bash`
* `/usr/local/bin/bash`
* `/usr/bin/bash`
* `/usr/sbin/bash`
* `/usr/local/sbin/bash`
======

If a script is written to be POSIX-compliant, use either of the following shebangs instead. This will trip the Bash program to executing the script in POSIX-compliant mode, equivalent to passing the `--posix` option to `bash` on the command line. Again, the second env-style shebang will have wider compatibility and is therefore RECOMMENDED.

----
#!/bin/sh
#!/bin/env sh
----

== Variables

In Bash, local variables can be used to scope data to the function the variable is declared in.

[source,bash]
----
hello="hello"

hello() {
  local hello="world"
  echo $hello # → "world"
}

echo $hello # → "hello" (not modified).
----

This syntax is Bash-specific and it is RECOMMENDED to use `local` for all variable declarations within functions, so as not to unnecessarily pollute the global namespace and to prevent unexpected overwrites of global variables.

Where the `local` keyword is omitted, include a comment explaining why it is not used. There will be many use cases where functions are designed to update global variables – that's fine, just use comments to be explicit about your intent.

Variable declaration and assignment MAY be on different lines, but try to always initialize variables with meaningful default values.

[source,bash]
----
some_function() {
  local code=0
  # ...
  code=2

  return ${code}
}
----

== Functions

Prefer the POSIX-compliant function declaration syntax. It is cleaner, more readable, and more portable.

[source,bash]
----
# ❌ Explicit function declaration.
function some_function () {
  return 0
}

# ✅ Implicit function declaration.
some_function() {
  return 0
}
----

== Conditionals

For conditional expressions, it is RECOMMENDED to use the Bash-specific double-bracket syntax, `[[ ... ]]`, over the POSIX-compliant single-bracket syntax, `[ ... ]`.

In older versions of Bash, using single bracket syntax with `&&` or `||` could cause syntax issues. Using the double bracket syntax is better, therefore, for backwards compatibility with older implementations of Bash.

The double bracket syntax is preferred for other reasons, too. It prevents pathname expansion and word splitting, which eliminates a common class of bugs in shell scripts. It also allows for regular expression matching, which the single bracket syntax does not support.

.Examples
[source,bash]
----
if [[ "filename" =~ ^[[:alnum:]]+name ]]; then
  echo "Match"
fi

if [[ "filename" == "f*" ]]; then
  echo "Match"
fi

# For comparison, this gives a "too many arguments" error as
# f* is expanded to the contents of the current directory.
if [ "filename" == f* ]; then
  echo "Match"
fi
----

''''

== References

* https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html[Bash reference manual]

* https://github.com/dylanaraps/pure-bash-bible[Pure Bash bible] by Dylan Araps

* https://tldp.org/LDP/Bash-Beginners-Guide/html/[Bash guide for beginners] by Machtelt Garrels

* https://tldp.org/LDP/abs/html/[Advanced Bash scripting guide] by Mendel Cooper

* https://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO.html[BASH Programming - Introduction HOW-TO] by Mike G

* https://mywiki.wooledge.org/BashGuide[BashGuide], written by various authors.

* https://guide.bash.academy/[The Bash guide] by Maarten Billemont (work-in-progress)

* https://web.archive.org/web/20230331215718/https://wiki.bash-hackers.org/[The Bash hackers wiki], community-maintained documentation (archived).

* https://en.wikibooks.org/wiki/Bash_Shell_Scripting[Bash shell scripting], a Creative Commons wiki-book by various authors.

* https://jvns.ca/blog/2017/03/26/bash-quirks/[Bash scripting quirks and safety tips] by Julia Evans
