= TS-21: ECMAScript (JavaScript/TypeScript)
:toc: macro
:toc-title: Contents

This technical standard covers coding conventions for ECMAScript-based languages – JavaScript and TypeScript.

toc::[]

== Dependency management

The following rules apply to the management of third-party ("vendor") libraries and packages, which may or may not be managed using a package manager tool.

=== Updating MAJOR versions

It is RECOMMENDED to use static analysis tools to detect libraries that have new major versions available, and to automatically raise issues in the project's issue tracker for these updates.

LTS releases of dependencies SHOULD be chosen over non-LTS releases wherever possible.

For libraries that have Service Level Agreements (SLAs), major versions MUST be updated before their End of Life (EOL) date.

=== Updating MINOR and PATCH versions

Dependencies with MINOR/PATCH updates SHOULD be updated regularly - best practice is to have recurring tasks in the project's issue tracker to cover this routine maintenance work.

It is RECOMMENDED to do MINOR/PATCH version updates at the start of a new release cycle. This means that dependency updates are not done close to release, leaving minimal time to reveal breaking changes and regressions caused by the dependency updates.

Dependencies MAY be updated as part of other development work, but it is RECOMMENDED to have dedicated issues assigned to these tasks.
