= TS-25: Privacy and Data Protection

== Data retention

Applications that store data ("data applications") MUST have a *data retention policy*, which MUST be documented as part of the application's design.

The data retention policy MUST define a *data retention schedule* for each discrete type of data stored by the application. The data retention policy MUST clearly define the retention period for each type of data, and the conditions under which data will be deleted. In addition, the data retention policy MUST document the data types that may be stored indefinitely, which MUST include technical data such as logs and monitoring data.

[IMPORTANT]
======
Data MUST NOT be retained for longer than it is required to fulfil specific business or user functions. This is a legal requirement throughout Europe and in many other jurisdictions worldwide.
======

Data applications MUST have an automated mechanism for deleting data as per the data retention policy. A common implementation pattern is to use scheduled tasks. Data deletion schedules and operations MUST be planned to minimize impact on the performance or availability of production systems.

In addition, there MUST be a documented manual process for finding and deleting data that is outside of its retention period. The manual process MUST be undertaken at regular intervals to verify that the automatic deletion mechanism is functioning as expected.

Automated and manual data deletion processes MAY need to involve caches, replicas, backups and failovers, as well as primary data sources, depending on the data synchronization strategies in use.

For auditing purposes, applications MUST log data deletion events. Such logs will capture information such as:

* When the process ran, and when is completed.
* Who initiated the run (user or automated agent).
* Which data was deleted. (This may be a simple matter of recording the number of entities deleted for each data type.)
* Any errors that were encountered. (The errors SHOULD also be captured in a separate error log.)

Data deletion audit logs MUST be easily accessible and searchable for reporting purposes.

== Logging and monitoring data

Logs and monitoring data SHOULD be persisted in separate storage from an application's primary data stores (for state and session data).

Personal Identifiable Information (PII) MUST NOT be sent to log output.

