= TS-30: Search Engine Optimization (SEO)
:toc: macro
:toc-title: Contents

This technical standard covers some SEO basics.

toc::[]

== Best practices for SEO

SEO is more about good habits than strategies. Good SEO outcomes depends on being disciplined. It means:

* Updating content frequently to keep it fresh.
* Manually adding internal links to every new thing you publish.
* Sweating the detail of everything you write.
* Doing thorough research and backing up your content with evidence from reliable sources.
* Crafting headlines that stand out in search.
* Constantly searching for new content opportunities.

Above all, write content that is genuinely useful to your target users. For example, write content that helps to solve real problems that your users have.

Do not spend much effort on trying to optimize content for particular search keywords or particular crawlers. Content must be easily parsable by machines, but beyond this you should focus on writing high quality content that people will find useful and want to share.

"Quality" content means independent, authoritative, and trustworthy content. Avoid producing content that is overly promotional or self-serving, or overly technical or jargon-heavy (unless appropriate for the target audience).

Don't oversell your products. Focus on how your product is different, now why it's better. "Better" is subjective and people will see right through any claims you make. Instead, incentivize people to try your product for themselves, and let them figure out if it's better or not.

== Web vitals

Google publishes a list of https://support.google.com/webmasters/answer/9205520[Core Web Vitals], which are three metrics that Google uses to report on user experience. The metrics are:

* Largest Contentful Paint (LCP)
* Interaction to Next Paint (INP)
* Cumulative Layout Shift (CLS)

These are certainly useful metrics for measuring user experience, but they are surprisingly unimportant when it comes to search engine ranking (at least in Google). We know this because in a https://www.youtube.com/watch?v=Ts7rPPIFhVg[2023 video] a Google dev advocate said:

[quote]
____
Google Search always seeks to show the most relevant content, even if the page experience is not the best. So page loading performance and also core web vitals aren't as important as some people might think they are. They are not irrelevant, but do not over focus on these things.
____

This has also been reiterated by John Mueller, Google’s search relations team lead, on numerous occasions on various https://www.linkedin.com/feed/update/urn:li:activity:7254734115789234176/[social media threads]:

[quote]
----
A perfect score is a fun technical challenge, and you'll learn something along the way, I know the feeling (I worked on mine too), but it's not going to make your site's rankings jump up.

