= TS-35: AsciiDoc
:toc: macro
:toc-title: Contents

AsciiDoc is RECOMMENDED for technical documentation. AsciiDoc is preferred over other lightweight human-editable markup languages such as Markdown as it is specifically designed for technical writing, it supports embedded diagrams and lots of other valuable features, and it has great tooling for publishing content to different formats.

This technical standard offers tips and best practices for writing AsciiDoc, and for using tools such as https://asciidoctor.org/[AsciiDoctor] and https://antora.org/[Antora] to process AsciiDoc files.

For a complete language reference, see the [Asciidoctor Documentation](https://asciidoctor.org/docs/). The AsciiDoctor website also has a useful [AsciiDoc Syntax Quick Reference](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) guide.

.AsciiDoc versus AsciiDoctor
****
AsciiDoc is the language specification. AsciiDoctor is a particular implementation; it is a free and open source tool for the processing of AsciiDoc files to HTML5, DocBook 5, PDF, and other formats.
****

toc::[]

== Markdown syntax

Asiidoctor supports a subset of Markdown syntax as an alternative to some standard AsciiDoc syntax. In general, prefer to use native Asciidoc syntax, not Markdown styles that happen to be supported by AsciiDoctor.

== File extensions

AsciiDoc files SHOULD use the `.adoc` extension. `.asciidoc` MAY be used as an alternative.

The extensions `.ad` and `.asc` MUST NOT be used.

== Attributes

https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/[Attributes] are a way of creating a variable whose value can be used throughout the document. Using attributes is encouraged as it increases readability and makes it easy to change content in one place for all locations where it is used.

Attributes are written in the document header and have the following form:

[source,asciidoc]
----
:name-of-an-attribute: value
----

To reference an attribute in the document body, use curly braces `{}` around the attribute name.

[source,asciidoc]
----
Lorem ipsum {name-of-an-attribute} ...
----

== Include directive

The https://asciidoctor.org/docs/user-manual/#include-directive[include directive] is used to include the content from another file in the current document.

It is RECOMMENDED to use include directive extensively. This helps to keep AsciiDoc files small and modular. Documentation sites and technical books are thus _composed_ from lots of files being included in one main file. Includes directives also allow reusing of content – such as code examples – in multiple places.

An include directive is written in the following form:

[source,asciidoc]
----
include::<path>/file[<attrlist>]
----

The `attrlist` is OPTIONAL and can contain one or more comma-separated attributes that modify the behavior of the include directive. For exampke, `leveloffset=+1` will adjust the section levels of the included file; heading level 1 (`=`) will become level 2 (`==`), level 2 will become level 3, and so on.

=== Antora

https://antora.org/[Antora] is a documentation generation tool. It creates documentation websites from structured hierarchies of AsciiDoc files and other assets. Antora imposes some additional constraints on how files can be included in AsciiDoc source files. The following conventions MUST be followed:

* All documents are saved in the `modules/<module-name>/pages/<path>` directory.
* All images are saved in `modules/<module-name>/assets/images/<path>`.
* All examples are saved in `modules/<module-name>/examples/<path>`.

When using paths to include something , you might need to use the `<module-name>` component when linking to another module, but you MUST NOT use `pages`, `assets/image`, or `examples` in the path component – only the `<path>` bit.

If you include a standard page – a page that is stored in the `pages` directory – into another page, you MUST set the `page-partial` AsciiDoc attribute in the document header of the page being included.

[source,asciidoc]
----
= The Page Header
:page-partial:

Page contents.
----

