= TS-35: AsciiDoc
:toc: macro
:toc-title: Contents

AsciiDoc is RECOMMENDED for technical documentation. AsciiDoc is preferred over other lightweight human-editable markup languages such as Markdown as it is specifically designed for technical writing, it supports embedded diagrams and lots of other valuable features, and it has great tooling for publishing content to different formats.

This technical standard offers tips and best practices for writing AsciiDoc, and for using tools such as https://asciidoctor.org/[AsciiDoctor] and https://antora.org/[Antora] to process AsciiDoc files.

For a complete language reference, see the [Asciidoctor Documentation](https://asciidoctor.org/docs/). The AsciiDoctor website also has a useful [AsciiDoc Syntax Quick Reference](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) guide.

.AsciiDoc versus AsciiDoctor
****
AsciiDoc is the language specification. AsciiDoctor is a particular implementation; it is a free and open source tool for the processing of AsciiDoc files to HTML5, DocBook 5, PDF, and other formats.
****

toc::[]

== Markdown syntax

Asiidoctor supports a subset of Markdown syntax as an alternative to some standard AsciiDoc syntax. In general, prefer to use native Asciidoc syntax, not Markdown styles that happen to be supported by AsciiDoctor.

== File extensions

AsciiDoc files SHOULD use the `.adoc` extension. `.asciidoc` MAY be used as an alternative.

The extensions `.ad` and `.asc` MUST NOT be used.

== Attributes

https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/[Attributes] are a way of creating a variable whose value can be used throughout the document. Using attributes is encouraged as it increases readability and makes it easy to change content in one place for all locations where it is used.

Attributes are written in the document header and have the following form:

[source,asciidoc]
----
:name-of-an-attribute: value
----

To reference an attribute in the document body, use curly braces `{}` around the attribute name.

[source,asciidoc]
----
Lorem ipsum {name-of-an-attribute} ...
----

