= TS-35: AsciiDoc
:toc: macro
:toc-title: Contents

AsciiDoc is RECOMMENDED for technical documentation. AsciiDoc is preferred over other lightweight human-editable markup languages such as Markdown as it is specifically designed for technical writing, it supports embedded diagrams and lots of other valuable features, and it has great tooling for publishing content to different formats.

This technical standard offers tips and best practices for writing AsciiDoc, and for using tools such as https://asciidoctor.org/[AsciiDoctor] and https://antora.org/[Antora] to process AsciiDoc files.

For a complete language reference, see the [Asciidoctor Documentation](https://asciidoctor.org/docs/). The AsciiDoctor website also has a useful [AsciiDoc Syntax Quick Reference](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) guide.

.AsciiDoc versus AsciiDoctor
****
AsciiDoc is the language specification. AsciiDoctor is a particular implementation; it is a free and open source tool for the processing of AsciiDoc files to HTML5, DocBook 5, PDF, and other formats.
****

toc::[]
