= TS-39: Privacy and Data Protection
:toc: macro
:toc-title: Contents

This technical standard covers general principles and practices for protecting the privacy of individuals and the data that is collected about them.

toc::[]

== Privacy by Design

Applications MUST be designed with privacy and data protection embedded as core design principles. This is known as *Privacy by Design* or *Privacy by Default*. This concept emerged in the 1970s and it means, simply, "data protection through technology design". It means that data processing procedures and data protection controls are considered at the design stage of an IT system, or at the design stage of any subsequent change made to that system, rather than these concerns being treated as separate features that are added on later.

The principle of Privacy by Design has since been added to data protection legislation such as the European Union's General Data Protection Regulation (GDPR). The GDPR explicitly requires that technical and organizational measures for protecting data be _proactively_ designed into business processes and systems, and that businesses anticipate and put in place prevention mechanisms for privacy breaches before they happen.

The principles of Privacy by Design can be summarized by the following seven statements:footnote:[Taken from the Information and Privacy Commissioner of Ontario, Canada: https://www.ipc.on.ca/en/resources-and-decisions/privacy-design]

1. Be proactive about privacy, not reactive. Anticipate and prevent privacy breaches before happen.

2. Built in maximum privacy to default settings. Users may explicitly opt-in to reduced privacy settings, but maximum privacy safeguards must be the default. Thus, if users do nothing, they are protected.

3. Embed privacy into the design of IT systems and business processes. Privacy should be integral to a system, not an add-on.

4. Privacy may need to be balanced against other legitimate interests and objectives, but the goal is to achieve a positive-sum (not zero-sum) outcome, in which privacy is not traded off against other objectives.

5. End-to-end security: embed strong encryption and other security measures to the complete life cycle of data.

6. Be open and transparent about your privacy policies and standards. Inform users about how their data is processed and stored. Allow for independent verification of your privacy practices.

7. Give users control over their data, and make it easy for them to manage their privacy settings.

== Personally Identifiable Information (PII)

*Personally-identifiable information* (PII) is any information that can be used to identify an individual. This includes, but is not limited to:

* Names
* Postal addresses
* Email addresses
* Phone numbers
* Passport numbers, social security numbers, and other government-issued identifiers
* Bank account numbers and other financial credentials

Combinations of values can also form personally-identifiable information. For example, neither a date of birth nor a postcode can, on their own, identify an individual. However, when combined, they can.

Some values are considered to be "borderline" PII, such as IP addresses. Whether borderline values should be handled as PII depends on the context. For example, an IP address may be considered PII if it is logged with other information such as timestamps and user agent strings.

*PII MUST NOT be stored anywhere other than production databases and their backup systems.*

For non-production systems, synthetic (dummy) data MUST be used in place of real PII. Alternatively, a hash of real PII MAY be used, as long as a strong cipher is used (making the hash irreversible without the cipher). The cipher must be handled as a secret – see *link:./security.adoc[TS-38: Security and Secrets Management]*.

Where it is not easy to distinguish between real and synthetic PII, the data should be clearly annotated as being synthetic.

Automated tools SHOULD be used to detect and prevent the storage of PII in illegal systems such as source code repositories. For example, pre-commit hooks can be enabled in Git to run secret scanning tools.


