= TS-39: Dates and Times

This technical standard sets out some best practices for working with, and storing, date and time values.

''''

Date and time values are captured in string data types in most programming languages and data storage systems. There are multiple formats that can be used to represent date and time values in a string. Which date and time formats to support is an important design consideration. The choice can have impacts on quality attributes of a system, notably interoperability with other systems, but also maintainability and usability.

Applications MUST use the https://www.rfc-editor.org/rfc/rfc3339 standard – which is analogous to the https://www.iso.org/standard/70907.html[ISO 8601] standard – for representing dates and times in data storage and data exchange formats.

It is strongly RECOMMENDED that applications use a small subset of date and time encoding formats, which are compliant with both RFC 3339 and ISO 8601, and also which have a high degree of interoperability with other standards such as the HTML Living Standard.

The RECOMMENDED subset of date and time formats for use in applications are shown in the table below.

|===
| Description | Format | Example

| Date only
| %Y-%M-%D
| 2025-12-31

| Time in UTC
| %h:%m:%sZ
| 23:59:59Z

| Time with UTC offset
| %h:%m:%s±00:00
| 23:59:59+00:00

| Date and time in UTC
| %Y-%M-%DT%h:%m:%sZ
| 2025-12-31T23:59:59Z

| Date and time with UTC offset
| %Y-%M-%DT%h:%m:%s±00:00
| 2025-12-31T23:59:59-00:00
|===

Notice the use of uppercase `T` and `Z` symbols, rather than lowercase.

Split second formats – eg. `2025-01-10T11:15:21.027652567Z` – SHOULD be used only when the fine-grained precision is required for a use case, for example in high-frequency trading systems, scientific applications, or for performance benchmarking.

Dates and times SHOULD be stored in UTC, and converted to the local time zone only when required for application output or processing. An exception to this rule is when the local time zone is a critical part of the data and it is a requirement that the data be represented in the original time zone.

Applications MAY accept date and time values in a wider range of formats as input, for a more convenient user experience, but alternative formats SHOULD be converted to the recommended subset of formats before persisting the data or exchanging rhe data with other internal systems.

Dates and times SHOULD be rendered in a human-readable locale-specific format for user interfaces.

''''

== References

* https://ijmacd.github.io/rfc3339-iso8601/[RFC 3339 vs ISO 8601]: A useful venn diagram showing where these two standards overlap.
