= TS-39: Amazon Web Services (AWS)

== Identity and access management

=== Root users

Every AWS account has a root user, which is the most privileged user in the account. It has full access to all AWS services and resources.

For security reasons, it is strongly RECOMMENDED that you do not use the root user for everyday tasks. Instead, create an administrative IAM user with more limited permissions.

After signing up for a new AWS account, you SHOULD:

* Set a very, _very_ strong password for the root user.
* Enable multi-factor authentication for the root user.
* Make sure that the root user does not have any access keys, so restricting the root user's access to the web console only.
* Create an IAM user with the `AdministratorAccess` policy, and use it to administer your AWS account instead.
* Enable IAM user and role access to billing information (via Billing and Cost Management), so that costs can also be managed by a non-root user.
* Set alerts for root user activity.

There will still be a few use cases where you will still need to access AWS using the root user. For example, when you want to close your AWS account, or when you want to change the primary email address associated with the account. Otherwise, all AWS activities SHOULD be undertaken by non-root users.

=== IAM and IAM Identity Center

The AWS *Identity and Access Management (IAM)* service is used to create *users*, *groups*, *roles*, and *policies*. The policies define which resources users can create and manage in the AWS account.

The *IAM Identity Center*, which was previously known as the *AWS Single Sign-On (SSO)* service, serves a broader purpose. It is used for managing identities of all kinds, including but not limited to IAM users.

It is now RECOMMENDED to use the IAM Identity Center to manage all user identities from a single, centralized service.

IAM Identity Center can have multiple identity sources. An identity source could be IAM itself, or it could be an external identity provider such as Active Directory (self-managed), Azure AD (hosted), Okta, or any other standard identity provider (IdP) that uses SAML 2.0.

IAM Identity Center also supports built-in SSO integrations with many widely-used business applications, from Adobe Creative Cloud to Zoom, so you can enable user access to lots of SaaS services very easily.

IAM Identity Center also integrates with *AWS Organizations*, which provides an alternative interface through which to manage IAM users.

=== AWS Organizations

AWS Organizations is a service that can be used to manage multiple AWS accounts under a single organization.

To use AWS Organizations, you create a *Management Account*, which will be at the root of the account hierarchy you create. You can then create additional AWS accounts, or invite existing accounts, into your organization. For example, you might choose to create a "Production" and a "Development". Additional accounts will be managed by the Management Account.

It is a common pattern in large organizations to have multiple AWS accounts managed under one AWS Organization. It allows the control of resources and permissions to be delegated to divisions or products within the organization.

It is RECOMMENDED to use AWS Organizations for this reason. Even if your organization starts with a simple structure and a s ingle product, building out your infrastructure under a sub-account allows you to more easily scale to new products and services in the future while keeping your cloud infrastructure clearly delimited by product.

=== IAM policies

IAM policies MAY be attached directly to IAM users, but it is RECOMMENDED to attach them to groups instead.

This makes it much easier to manage permissions across multiple users. This is especially important for large organizations with lots of users, where it becomes impractical to manage the permissions of users individually.
