= TS-39: Privacy and Data Protection
:toc: macro
:toc-title: Contents

This technical standard covers general principles and practices for protecting the privacy of individuals and the data that is collected about them.

toc::[]

== Personally Identifiable Information (PII)

*Personally-identifiable information* (PII) is any information that can be used to identify an individual. This includes, but is not limited to:

* Names
* Postal addresses
* Email addresses
* Phone numbers
* Passport numbers, social security numbers, and other government-issued identifiers
* Bank account numbers and other financial credentials

Combinations of values can also form personally-identifiable information. For example, neither a date of birth nor a postcode can, on their own, identify an individual. However, when combined, they can.

Some values are considered to be "borderline" PII, such as IP addresses. Whether borderline values should be handled as PII depends on the context. For example, an IP address may be considered PII if it is logged with other information such as timestamps and user agent strings.

*PII MUST NOT be stored anywhere other than production databases and their backup systems.*

For non-production systems, synthetic (dummy) data MUST be used in place of real PII. Alternatively, a hash of real PII MAY be used, as long as a strong cipher is used (making the hash irreversible without the cipher). The cipher must be handled as a secret – see *link:./security.adoc[TS-38: Security and Secrets Management]*.

Where it is not easy to distinguish between real and synthetic PII, the data should be clearly annotated as being synthetic.

Automated tools SHOULD be used to detect and prevent the storage of PII in illegal systems such as source code repositories. For example, pre-commit hooks can be enabled in Git to run secret scanning tools.

