= TS-40: Visibility (Logging, Monitoring, and Observability)
:toc: macro
:toc-title: Contents

This technical standard sets out principles and best practices for logging, monitoring, and observability – collectively known as the *visibility* quality attribute.

toc::[]

== Logging

Personal Identifiable Information (PII) MUST NOT be sent to log output.

Runtime errors MUST be logged, so that issues can be detected and investigated.

== Monitoring

Uptime monitoring MUST be implemented for software-as-a-service applications. Individual services within a distributed system MUST be monitored separately to the user interface of the application as a whole.

== Alerting

Production alerting – notifications of errors or other issues – MUST be implemented in production environments, and SHOULD be implemented in pre-production environments.

== Metrics

Metrics MUST be gathered to inform and evaluate:

* Success criteria for changes made.
* Future development.
* Stability and reliability monitoring.
* Customer usage / activity patterns.

Key metrics – eg. API response times, batch processing times, speed of transactions etc. – MUST be tracked and monitored.

Customer-facing applications MUST have front-end analytics integrated, to provide insights into how customers use the application.
