= TS-X Architectural Standards

This document describes general software architectural design best practices and
standards.

== Principles

* *Design emerges*. Architecture provides a framework into which a design can
  be applied. Architecture SHOULD, therefore, be lightweight.

* Build the simplest solution that could possibly work, but keep it flexible
  enough to change, to accommodate future features.

////

* *Release early, release often*. This principle emphasizes the importance of
  early and frequent releases in creating tight feedback loops between the
  technical teams and users. This helps to identify bugs early, and also to
  improve the software for the users. Canary testing and other strategies are
  related.

* *Services-first*. A service-oriented architecture (SOA) is an architectural
  approach that enables software components to be reusable and interoperable
  through well-defined service interfaces. Each service embodies the code and
  data required to execute a complete discrete business function. The service
  interfaces promote loose coupling, meaning they can be called with little
  knowledge of how each service is implemented internally.

  Developing _capabilities as services_, over single-use products, allows a
  business to build customer-facing applications on top of networks of
  capabilities.

////

== Objectives

The architecture of a system should address the following design objectives.

****
It should not be assumed that all objectives can be applied equally. Trade-offs
will always be required within these guidelines for making architectural
decisions that are reasonable and consistent. No priority should be assumed
from the order in which these objectives are presented below.
****

=== Performance

Performance is defined as how well a software system performs its intended
functions. It can be measured in terms of response time, throughput, latency,
and resource utilization.

=== Scalability

Scalability is defined as the ability of a software system to handle increasing
workloads by adding resources to the system such as processes, memory, and
storage.

=== Reliability

Reliability is defines as the ability of a software system to _consistently_
perform its intended functions without failures or errors.

=== Availability

Availability is defined as the proportion of time that a software system is
operational and accessible to users. It is often measured as a percentage of
time, called uptime.

=== Extensibility

Extensibility is defined as the ability of a software system to easily
accommodate changes or additions to its functionality, without requiring
major refactorings.

=== Maintainability

Maintainability is defined as the ease with which a software system can be
updated, repaired, or enhanced over its lifetime. It includes factors such as
code readability, modularity, and documentation.

=== Manageability

Closely related to maintainability, this is the ease with which a software
system can be controlled and operated by system administrators.

=== Stability

Architectural stability is defined as the ability of the architecture to remain
consistent and predictable over time, even as the requirements of the system
change - perhaps significantly.

So, a stable architecture is one that can accommodate new features
(extensibility) without requiring major refactoring of the underlying logic
structure and data model.

=== Evolvability

Evolutionary architecture is defined as the ability of the architecture to
change over time.

Evolvability is not necessarily contradictory to stability. A good design will
demonstrate both characteristics: it will support the addition of new features
without requiring major refactorings, and it will also evolve over time to
accommodate changing non-functional requirements such as greater scalability
or performance under heavier load.

[quote, Gereon Hermkes]
____
Just because the architecture is supposed to be stable, it does not mean it
should never change.
____

=== Visibility

Visibility – also known as observability, though the two terms are not
exactly synonymous – refers to the ease with which a software system can be
monitored and diagnosed at runtime.

=== Security

A software system is said to be secure when it is protected against unauthorized
access, data breaches, and other security threats.

=== Compliance

Compliance requirements can be addressed by incorporating the necessary
controls, security measures, and data protection mechanisms into the design of
a system.

It is important to understand the specific regulations that apply to a system
based on the industry or geographic region where it will be deployed and used.
Examples include the General Data Protection Regulation (GDPR) in the European
Union and the UK, the Health Insurance Portability and Accountability Act
(HIPAA) in the United States, and the Payment Card Industry Data Security
Standard (PCI DSS) for organizations that handle payment card transactions.
