= TS-X Dependency Management Standards

== Updating MAJOR versions

* Updating dependencies to new MAJOR versions MUST be tracked through
  dedicated issues in the issue tracker. It is RECOMMENDED to use tools to
  automatically raise issues when new major versions of dependencies become
  available.

* LTS releases of dependencies SHOULD be chosen over non-LTS releases wherever
  possible.

* MUST upgrade between End of Life (EOL) for components that have Service
  Level Agreements (SLAs).

== Updating MINOR and PATCH versions

* Dependencies with MINOR/PATCH updates SHOULD be updated regularly - best to
  put in recurring tasks for these things.

* It is RECOMMENDED to to MINOR/PATCH version updates at the start of a new
  release cycle. This means that dependency updates are not done close to
  release, leaving minimal time to reveal breaking changes and regressions
  caused by the dependency updates.

* Dependencies MAY be updates as part of other development work, but it is
  RECOMMENDED to have dedicated issues assigned to these tasks.
