= TS-X Functional Testing Standards

All test code is subject to the same coding standards as application code.

== Unit tests

Working unit tests MUST be developed for every change, inclusive of back-end
and front-end changes.

Unit test coverage MUST be measured and SHOULD be ≥ 90% in trunk.

=== Mocking in unit tests

SQLite, optionally running in a container, MAY be used to implement tests where
integration with a database needs to be mocked.

== Functional tests (aka feature tests)

Feature tests SHOULD be written in BDD style.

A functional test pack MUST be created for each application, and it MUST have
tests that cover the majority of the application's operations, such that
executing the test pack is enough to verify that the application is suitable
for customer use, without undertaking additional manual testing.

Functional tests MUST be automated wherever possible. Manual test scripts MUST
cover scenarios that cannot be practically automated.

Functional test packs MUST be suitable for use in regression testing.

For web applications, e2e browser tests SHOULD be done automatically, with
regular manual testing.

== API integration testing

Testing API integrations – ie. between services – MUST be done prior to
applications being released to production.

All integrations MUST be testable in dev/QA environments.

Applications SHOULD mock integrations in dev/QA environments.
