= TS-X HTTP API Standards

This document outlines standards for designing and implementing HTTP APIs. These standards are applicable to private HTTP APIs between services within distributed software systems ("inter-service communication protocols"), and public HTTP APIs that are made available for integration into client applications, including client applications operated by third parties ("web services").

When designing HTTP APIs, it is important to respect existing HTTP interaction patterns and resource models.

== URI components

=== Versioning

URL-based versioning SHOULD be used for its simplicity of use for API consumers, compared to the more complex header-based approach.

The first segment of the URI path SHOULD be `/v[major]` where `[major]` is the major version number of the API, for example `/v1`.

.Template
----
/v[major]
----

.Example
[source]
----
/v1
----

=== Namespaces

The next part of the URI path SHOULD be considered a "namespace" in which related services will be grouped. Namespaces SHOULD reflect the customer's perspective of how the product works, which may not necessarily reflect the organization's structure or the boundaries of the services or the teams that are responsible for developing and operating them. Consumer-oriented namespaces make APIs easier to understand and use.

.Template
[source]
----
/v[major]/[namespace]
----

.Example
[source]
----
/v1/vault
----

Namespaces SHOULD be nouns but MAY be singular or plural.

=== Resources

Consistent path components SHOULD be used to refer to the same resources across different endpoints.

.Template
[source]
----
/v[major]/[namespace]/[resource]/[resource-id]/[sub-resource]/[sub-resource-id]
----

''''

== Acknowledgements

The following resources informed TS-X Web Service API Standards.

* link:https://github.com/jharmn/api-standards[Jason Harmon's API standards]
