= TS-X: Java Standards

:link-google-style-guide: https://google.github.io/styleguide/javaguide.html
:link-oracle-style-guide: https://www.oracle.com/java/technologies/javase/codeconventions-introduction.html
:link-escape-sequences: http://docs.oracle.com/javase/tutorial/java/data/characters.html

.Terminology
****
Throughout this document, the following works shall have the following meanings:

* "Class-like constructs" means any ordinary classes, enums, interfaces, or
  annotation types (`@interface`).

* "Members" means all fields, methods, constructors, and nested classes within
  a class or other class-like structure.

* "Comments" refers only to _implementation_ comments, while "Javadoc" refers
  to _API documentation_ comments.
****

== Code style

The most common coding standard for Java is {link-google-style-guide}[Google's
Java Style Guide]. It is widely adopted in the industry as is the basis for
the following code style recommendations.

.Summary
****
* Source files: `<ClassName>.java`.
* Indentation: 2 spaces.
* Line lengths: 80 soft limit, 100 hard limit.
* Braces: K&R style.
* Classes and interfaces: UpperCamelCase.
* Methods and variables: lowerCamelCase.
* Constants: ALL_UPPER_CASE.
****

=== Source files

Each source file SHOULD contain exactly one class-like construct. In special
circumstances, a source file MAY have exactly one top-level public class and
additional class-like constructs that are tightly coupled to that class and
shared with no other classes. The top-level public class MUST be the first
construct within the file.

Source files are distinguished by the `.java` file extension. Java bytecode
files have the `.class` extension. Source file names MUST match exactly
– including the letter case – the name of their top-level public class or
whatever other class-like construct is their main content.

The contents of source files MUST be laid out in the following order, from
top to bottom:

1. License or copyright notice, if required.
2. Package statement.
3. Import statements.
4. The main top-level class-like construct, eg. a public class.
5. Other class-like constructs used by the main construct.

=== Encoding

Source files MUST be encoded in UTF-8.

Source files MUST use Unix-style line endings, that is they MUST use the line
feed (LF) character, which is represented by the escape sequence `\n`. Source
files MUST NOT use Windows-style line endings, that is the carriage return and
line feed (CRLF) pair, which are represented by the escape sequence `\r\n`).

Whitespace characters included in source files MUST be limited to the line
termination sequence and the horizontal space character. Tab characters are not
used for indentation and MUST NOT be included in source files for this or any
other purpose.

Other whitespace characters MAY be included only in string and character
literals (they MUST NOT be included in any other parts of the code) and they
MUST be represented by escape sequences. Those whitespace characters that have
a {link-escape-sequences}[special escape sequence] in Java MUST be encoded
using that escape sequence, eg.: `\b`, `\t`, `\n`, `\f`, `\r`, `\"`, `\'`,
and `\\`. For other whitespace characters, either their octal (eg. `\012`) or
their Unicode (eg. `\u000a`) code MAY be used.

Non-whitespace (ie. printable) characters outside of the ASCII range MAY be
encoded using either their actual Unicode character (eg. `∞`) or that
character's Unicode escape sequence (eg. `\u221e`). The choice of which encoding
to use is at the discretion of the developer, but the choice SHOULD be
determined by the readability and understandability of the code.

[source,java]
----
/*
This code is perfectly clear. The "μ" character can be printed verbatim, rather
then represented by an escape sequence, and no comments are necessary.
*/
`String unitAbbrev = "μs";`
----

For all characters that are encoded using escape sequences, except for those
that are widely recognized (`\t`, `\n`, etc.), a comment SHOULD be included
to explain the meaning of the escape sequence. End-of-line `//` comments
SHOULD be used for this purpose.

[source,java]
----
`return '\ufeff' + content; // byte order mark`
----

=== Indentation

Use two spaces to represent one level of indentation. Do not use tabs.

Increase the indentation by one level for each nested block or block-like
construct. When the nested block ends, the indent returns to the previous
level.

Indentation of comments and Javadocs MUST align with the code to which they
are related.

=== Line length

There MUST be no more than one statement per line.

Line lengths SHOULD be limited to 80 characters (including preceding whitespace
for indentation) and MUST NOT exceed 100 characters.

=== Brace style

In Java code, the most common formatting options for braces are:

* Kernighan and Ritchie (K&R) style.
* Allman style.
* GNU style.

In the K&R style, the opening brace is placed at the end of the line that begins
the compound statement, and the closing brace is placed on a line of its own at
the same indentation level as that opening statement.

.K&R style
[source,java]
----
class Example {
  public void method() {
    if (condition) {
      // …
    } else {
      // …
    }
  }
}
----

The Allman style differs from K&R by moving the opening brace to a new line,
aligned to the left of the compound statement. This style emphasizes vertical
alignment and increases the use of white space, arguably improving readability.

.Allman style
[source,java]
----
class Example
{
  public void method()
  {
    if (condition)
    {
      // .…
    }
    else
    {
      // …
    }
  }
}
----

The GNU style is similar to the Allman style, but the braces are indented for
alignment with the _inner_ code blocks, rather than the _outer_ block
statements that encapsulate them.

.GNU style
[source,java]
----
class Example
  {
  public void method()
    {
    if (condition)
      {
        // …
      }
    else
      {
        // …
      }
    }
  }
----

Of these three, it is the K&R style that is most widely used and which is the
most widely recommended in Java coding style guides. For consistency with the
prevailing industry standard, the K&R convention MUST be used to format braces.

=== Naming conventions

Classes MUST be named using UpperCamelCase. Methods and variables MUST be named
using lowerCamelCase. Constants MUST be named using ALL_CAPS_SLUGS.

=== Class and interface declarations

Method declarations MUST be separated by a blank line.

=== Comments

Java supports three comment notations:

* `//` MUST be used for commenting-out code, and MAY be used for short
  end-of-line comments that decode or explain a value assigned or returned
  by the statement.

* `/* … */` MUST be used for multi-line comments.

* `/** … */` MUST be used for Javadocs.

See below for further information on formatting Javadocs.

== Javadoc

Javadoc comments are used to document the internal API of a Java program. They
are parsed by various tools, including those embedded in IDEs, to generate
developer documentation.

''''

== References

* {link-google-style-guide}[Google Java Style Guide]
* {link-oracle-style-guide}[Oracle: Code Conventions for the Java Programming Language]
