= TS-X Non-Functional Testing Standards

== Security testing

== Performance testing

Load and response time testing MUST be performed where there is a requirement
for the component to perform within agreed constraints, eg. API response time,
transactions per second, number of concurrent users, etc.

== Load testing

Also known as capacity testing, this form of testing MUST be undertake where a
specific capacity requirement is identified, eg batch record handling, supported
size of files for upload/download.

== Scalability testing

Applications SHOULD be developed for *horizontal scalability*, ie. the ability
to add more instances of the application to handle increased load.

Scalability testing is the practice of verifying how quickly new instances
can be provisioned when demand increases. If this process is automated
(known as *auto-scaling*), the outcome of this testing is a number that
represents the time lag between a spike in demand and the availability of
new instances.

== Accessibility testing
