= TS-X PHP Coding Standards
:toc: macro

:link-per-coding-2: https://www.php-fig.org/per/coding-style/

PHP code SHOULD follow PER Coding Style 2.0, which is summarized and extended
in this document.

It is RECOMMENDED to use automated linting tools, with automatic code fixing
enabled, to enforce consistent coding standards.

toc::[]

== Type hinting in PHP

PHP is a dynamically typed language, but it is possible to add type hints to
functions and methods. It is strongly RECOMMENDED to use type hints extensively.
Specifically:

* Class properties SHOULD be typed.
* Method parameters SHOULD be typed.
* Method return types SHOULD be declared.

Type safety – the practice of using strict typing – has multiple advantages. It
helps to catch bugs early, and static analysis tools can pick up on those
errors in an automated way. Type hints also serve as a form of inline
documentation, helping to make the code easier to understand.

Unfortunately, although PHP's type hinting capability has improved over time,
there remain some gaps in PHP's type system. Most notably is the inability to
declare the data types that can be held in arrays and iterables. Some static
analysis tools fill in the gaps. Some will allow you to use docblocks to extend
PHP's native type hints with additional metadata, which is understood by the
analysis tool. It is RECOMMENDED to use the these tools to implement stricter
type checking wherever practical.

[source,php]
----
/** return array<int, MyObject> */
public function toArray(): array {
    return $this->items;
}
----

Where extended type hints are provided, the docblocks MUST NOT repeat native
type declarations - this is redundant.
