= TS-X React Coding Standards

React is a popular JavaScript library for composing graphical web user
interfaces from reusable components.

== Wrapping native elements

It is RECOMMENDED to use the spread operator to pass all props from React
components to the underlying native elements they wrap.

```jsx
import React from "react"

export default function Button(props) {
  return (
    <button {...props}>
      {props.children}
    </button>
  )
}
```

This allows users of the component to set any number of native HTML attributes
as props.

```jsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import Button from "./Button"
import { FcGoogle } from "react-icons/fc"

function App() {
  return (
    <main>
      <Button style={{color: "green"}} onClick={() => console.log("Logging in...")}>
        <FcGoogle />
        Log in with Google
      </Button>
    </main>
  )
}

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
```

This pattern means that consumers could pass invalid props, which are not
supported by the abstracted native element. However, since HTML will just
ignore invalid attributes, this will not cause any runtime issues. It's a
good trade-off for the increased flexibility.

This pattern simplifies the code (components don't need to explicitly plan for
every possible attribute that a native HTML element supports) and increases
reusability (you can use the React components for every use case you would be
able to if you were writing pure HTML).

This pattern is restricted to wrappers for single native HTML elements. It is
NOT RECOMMENDED to use this pattern for custom components, composed of multiple
native elements and/or other components. In this case, the props are the
component's declarative API, and should be explicitly defined.
