= TS-X Release Management Guidelines

This technical standards document describes contentions and best practices for releasing software updates. These standards are applicable to both software-as-a-product, which tends to be intermittently released, and software-as-a-service, which tends to be more continuously released.

The primary aim of this document is to provide general advise to follow to minimize the risk of bugs and regressions making it through the delivery pipeline into production.

.Related technical standards
****
* Versioning standards
* Release testing
****

== Release automation

Application SHOULD be developed in such as way that new releases and maintenance
tasks can be performed without requiring downtime or other impacts on users.

== Release readiness

An application is said to be in a releasable state when changes have been merged into the main branch that satisfy the "definition of done".

== Release cadence

Release cadence is the frequency at which software updates are released to end users. This is one aspect of a product's release strategy, which includes wider considerations such as the scope of releases, quality controls, and testing strategies such as canary releases.

Release cadence is a user-facing feature of a software system, and therefore this should be agreed with the product owner and other relevant stakeholders.

== Continuous delivery

//Continuous delivery is defined as the practice of releasing software updates to end users as soon as they are ready. Continuous deployment is the practice of releasing software updates to end users as soon as they are ready, without human intervention.

//Continuous Delivery vs Continuous Deployment: Key Differences. Simply put, Continuous Delivery focuses on ensuring software is always release-ready with manual approval, while Continuous Deployment automates the release process, deploying changes to production automatically once tests pass.

== Continuous deployment
