= TS-X Security Standards

== Secrets

[NOTE]
======
A *secret* is defined here as any sensitive data required to run an application,
and which would create a security risk is not kept secret from the majority of
users inside, and all users outside, the organization.

Examples: encryption keys, database access credentials, API keys, service
credentials, etc.
======

Database connections MUST NOT be hard-coded in or stored alongside application
source code.

Secrets MUST NOT be sent to log output.

== Encryption

Personal data, or any business-sensitive information, MUST be encrypted at rest.

All data MUST be encrypted in transit (ie. TLS).

== Source code vulnerabilities

Source code MUST be scanned for vulnerabilities prior to release. It is
recommended to use a combination of Static Application Security Testing (SAST),
eg. Checkmarx, and Dynamic Application Security Testing (DAST), eg. OWASP ZAP.

High-level issues identified by SAST/DAST tools SHOULD be prioritized similarly
to incidents.

Low-level issues identified by SAST/DAST tools SHOULD be prioritized with
high priority.

== Third-party components

Third-party software components MUST be checked for security vulnerabilities
and license changes, using a software composition analysis (SCA) tool such as
Mend.
