= TS-X Guidelines for Version Control with Git

All code and configuration MUST be stored in a version control system.

For each repository, there MUST be a single centralized repository that is the
"source of truth" for the codebase.

== Coding standards

Code within the same repository SHOULD follow a consistent coding standard.
The only exception permitted is mono-repos, where different parts of a system
may be written in different languages and for different platforms.

== Code repositories

The boundaries of code repositories SHOULD NOT be arbitrary. Ideally scoped to
teams, but more critical that each repo is a discrete, and complete, system –
ie. you should be able to checkout the repository, run a build script, and
have a complete working system running without reliance on other components.

If the system calls external services, the system MUST function without errors
when those external services are unavailable. It SHOULD also be possible to
run the system in a "test mode" which mocks all external dependencies.

"Mono repos" MAY be used, and in fact they are RECOMMENDED in many contexts.

The main goal is that you MUST check-in everything you need to build, run, test,
and deploy (to all environments) the application under source control.

It is critical that applications can be deployed independently. It SHOULD NOT
be necessary to coordinate deployments across multiple repositories.

''''

Version control allows us to recreate prior versions of our software, but we
only get that benefit if the repository represents a boundary of a discrete
system that can be built, run, tested, and deployed on its own – without any
other external dependencies that are not configured via the same repo.

So mono-repos SHOULD be used where components are coupled enough that they
MUST always co-exist for either to work.

Within a repo, everything at the same revision is intended to work together.
Version control scope defined the relationship between highly coupled components.

For example, if v17 of Service A and v12 of Service B represent v2 of our
application, those two services SHOULD go in the same repository (ideally).
Unless the application can "fail gracefully" without one or the other component,
ie. it is not tightly coupled to either.

A repository represents the boundary of tightly coupled components that MUST
always be deployed together, even if some of those components run in separate
processes.

The key test is: can I deploy components independently of others, and even roll
it back, without breaking anything else. If yes: own repo!


