= TS-X Best Practices for Observability and Monitoring (aka. Visibility)

Uptime monitoring MUST be implemented for applications.

Application errors MUST be recorded, so that issues can be detected and
investigated.

Production alerting – notifications of errors or other issues – MUST be
implemented in production environments, and SHOULD be implemented in
pre-production environments.

Individual services used by the application – eg API integration – SHOULD be
monitored for uptime and error conditions, separately to the application as a
whole.

== Metrics

Metrics are used to inform and evaluate:

* Success criteria for changes made.
* Future development.
* OKRs.
* Stability and reliability monitoring.
* Customer usage / activity patterns.

Customer-facing applications MUST have front-end analytics, integrated, to
provide insights into how customers use the application.

Key metrics – eg. API response times, batch processing times, speed of
transactions etc. – MUST be tracked and monitored.
