= References

* Angular.
  {link-angular-commit-guidelines}[_Commit Message Guidelines_].

* Atlassian.
  {link-atlassian-comparing-workflows}[_Comparing Git Workflows_].

* Atlassian.
  {link-atlassian-simple-workflow}[_Simple Git Workflow_].

* Chacon, S (2011).
  {link-chacon-2011}[_GitHub Flow_].

* Chacon, S; Straub, B.
  {link-chacon-pro-git}[_Pro Git: Distributed Workflows_].

* Conventional Commits.
  {link-conventional-commits}[_Conventional Commits_].

* Driessen, V (2010).
  {link-driessen-2010}[_A Successful Git Branching Model_ (GitFlow)].

* Ellerby, B (2020).
  {link-ellerby-2020}[_Serverless Flow: A CI/CD Branching Workflow Optimized for Speed and Quality_].

* Git.
  {link-git-submitting-patches}[_Submitting Patches_].

* GitHub.
  {link-github-flow}[_GitHub Flow_].

* GitLab (2014).
  {link-gitlab-2014}[_GitLab Flow_].

* GitLab.
  {link-gitlab-flow}[_What is GitLab Flow?_].

* Hintjens, P (2016).
  {link-hintjens-2016}[_The Collective Code Construction Contract (C4)_].

* Li, J (2019).
  {link-li-2019}[_Successfully Merging the Work of 1000+ Developers_].

* Microsoft (2022).
  {link-microsoft-2022}[_How Microsoft Develops with DevOps_].

* Newman, G (2024).
  {link-newman-2024}[_The Pragmatic Engineer Test_].

* Precht, P.
  {link-precht-rebase}[_REBASE: The Complete Guide on Rebasing in Git_].

* Ruka, A (2017).
  {link-ruka-2017}[_OneFlow – a Git Branching Model and Workflow_].

* Siddiqi, Z.
  {link-siddiqi-habits}[_Good Software Development Habits_].

* Spiewak, D.
  {link-spiewak-dmz}[_Git DMZ Flow_].

* Trunk-Based Development.
  {link-trunk-based-development}[_Trunk-Based Development_].

* Wiggins, A (2017).
  {link-wiggins-2017}[_The Twelve-Factor App_].

* Wilsenach, R (2021).
  {link-wilsenach-2021}[_Ship / Show / Ask_].
