= Source files

.Summary
****
* One public class per file
* UTF-8 encoding
* Unix line endings
****

Each source file SHOULD contain exactly one class-like construct. However, in
special circumstances, a source file MAY have exactly one top-level public class
plus additional class-like constructs that are deliberately tightly coupled to
the main class and that are shared with no other classes. The top-level public
class MUST be the first construct within the file.

Source files are distinguished by the `.java` file extension, while Java
bytecode files have the `.class` extension. The file names MUST match exactly –
including the exact letter case – the name of the main class-like construct they
contain.

The contents of source files MUST be laid out in the following order, from top
to bottom:

1. License or copyright notice, if required.
2. Package statement.
3. Import statements for internal classes, listed alphabetically.
4. Import statement for third-party package dependencies, listed alphabetically.
5. The main top-level class-like construct, eg. a public class.
6. Other class-like constructs used by the main construct.

Each section MUST be separated by a single blank line. Class-like constructs,
block-like constructs, and members MUST also be separated by a single blank
line. Javadocs MUST be preceded by a single blank line, except the first
file-level Javadoc, which MAY start on line 1.

== Encoding

Source files MUST be encoded using UTF-8.

Source files MUST use Unix-style line endings, which means using the line feed
(LF) character, which is represented by the escape sequence `\n`. Source files
MUST NOT use Windows-style line endings, which is a carriage return and line
feed (CRLF) pair and represented by the escape sequence `\r\n`.

Whitespace characters included in source code MUST be limited to the line
termination sequence and the horizontal space character. Tab characters MUST NOT
be used for indentation.

Other whitespace characters MAY be included only in string and character
literals (they MUST NOT be included in any other parts of the code) and they
MUST be represented by escape sequences. Whitespace characters that have a
http://docs.oracle.com/javase/tutorial/java/data/characters.html[special escape
sequence] in Java MUST be encoded using that escape sequence.

.Available whitespace escape sequences in Java
[cols="1,2"]
|===
|Escape sequence |Description

|`\t`
|Insert a tab in the text at this point.

|`\b`
|Insert a backspace in the text at this point.

|`\n`
|	Insert a newline in the text at this point.

|`\r`
|Insert a carriage return in the text at this point.

|`\f`
|Insert a form feed in the text at this point.

|`\'`
|	Insert a single quote character in the text at this point.

|`\"`
|	Insert a double quote character in the text at this point.

|`\\`
|	Insert a backslash character in the text at this point.
|===

[source,java]
----
System.out.println("She said \"Hello!\" to me.");
----

For other whitespace characters, either their octal (eg. `\012`) or their
Unicode code point (eg. `\u000a`) SHOULD be preferred over including the literal
whitespace character. Optionally, you can describe encoded characters in an
end-of-line comment. The goal is to make it as easy as possible for others to
identify special whitespace characters in code.

[source,java]
----
System.out.println("\u2004"); // three-per-em space
----

Non-whitespace (ie. printable) characters outside of the ASCII range MAY be
encoded using either their actual Unicode character (eg. `∞`) or that
character's Unicode escape sequence (eg. `\u221e`). The choice of which encoding
to use is at the discretion of the developer, but the choice SHOULD be
determined by the readability and understandability of the code.

[source,java]
----
/*
This code is perfectly clear. The "μ" character can be printed
verbatim, rather than be represented by an escape sequence, and
no comments are necessary.
*/
String unitAbbrev = "μs";
----

For all characters that are encoded using escape sequences, except for those
that are widely recognized (`\t`, `\n`, etc.), a comment SHOULD be included to
explain the meaning of the escape sequence. End-of-line `//` comments SHOULD be
used for this purpose.

[source,java]
----
return "\ufeff" + content; // byte order mark
----
