= Naming conventions

.Summary
****
* *UpperCamelCase* for classes and interfaces
* *lowerCamelCase* for methods and variables
* *UPPER_SNAKE_CASE* for constants
****

== Spelling

All file names, code, comments, and Javadocs MUST be written in English, with American English preferred for spelling.

== Identifiers

All identifiers MUST be composed only of ASCII letters and digits and, in a small number of cases, underscores. Thus, each valid identifier is matched by the regular expression `\w+`.

Special prefixes or suffixes SHOULD NOT, generally, be used on identifiers. For example, do not prefix variables with `s_` to indicate that they are static, or suffix interfaces with `I` to indicate that they are interfaces.

== Package names

Package names MUST use all lower case letters and digits, and no underscores. Java does not allow hyphens in package names, so that's not even an option.

Consecutive words are simply concatenated together, with no special formatting for word delimitation.

* `com.example.formvalidator` ✓
* `com.example.form_validator` ✗
* `com.example.formValidator` ✗
* `com.example.form_validator` ✗
* `com.example.form-validator` ✗ (illegal package name)

The convention for writing package names in lower case has been established to avoid conflicts with the names of classes and interfaces (identifiers in Java are case-sensitive).

The convention of using a reverse domain name – eg. `com.example` – for the top-level namespace of a package is also long-established in the Java community. The purpose of this convention is to ensure that package names are unique across different organizations and projects – across the whole global Java ecosystem. Since a domain name is unique to the person or organization who owns it, this convention guarantees uniqueness of package names globally.

However, for application code that will not be shared with others, the reverse domain name convention is not necessary. Better in this case to choose a codename for each software project, which is unique internally within the organization. Using a codename rather than the application's brand name helps to decouple the code from the product marketing, allowing the latter to be changed without substantial code refactoring.

In choosing codenames for their software projects, organizations may choose a theme, such as the names of planets, cities, or characters from books or movies.

.Examples of internal/private package names
----
adelaide.webapi.io.controllers.cli
adelaide.webapi.io.controllers.http
adelaide.webapi.kernel.commands
adelaide.webapi.kernel.config
adelaide.webapi.kernel.jobs
adelaide.webapi.model.entities
adelaide.webapi.model.repositories
adelaide.webapi.system.dao
adelaide.webapi.system.services
----

Package names may be a mix of plural and singular forms. Use your judgment. The general principle is that the plural form should be used for packages with homogenous contents and the singular for packages with heterogeneous contents. Most packages will be containers for software components of the same type (homogenous collections), and therefore the plural form will be appropriate: "controllers", "documents", "entities", "services", "repositories", etc. An exception would be for collections of components that implement a design pattern identified by an abbreviation such as "dto" or "dao"; appending these with an "s", while more consistent, would only increase confusion.

Some packages will be containers for diverse components from which a discrete subsystem is composed, such as a GUI or library. For many of these packages the singular form will be more appropriate, eg. "gui", "lib", "util". Similarly, configurations should go in a "config" package.

== Class and interface names

Classes and interfaces MUST be named using UpperCamelCase.

Class names are typically nouns or noun phrases. They SHOULD be descriptive and unambiguous, and SHOULD NOT be overly long. Good examples of class names include `Character`, `ImmutableList`, `PriorityQueue`, and `UrlConnection`.

Interface names MAY also be nouns or noun phrases, eg. `List`, but MAY also be adjectives or adjective phrases, eg. `Readable`, `Closeable`, or `Runnable`.

Classes from which objects are created SHOULD be named using a singular noun or noun phrase, eg. `UserService`, `UserEntity`, `UserRepository`, etc. Where classes are merely containers for static methods and constants, they MAY be named using a plural noun or noun phrase, eg. `DataAccessUtilities`, `ValidationRules`, etc.

Interfaces SHOULD follow the same naming conventions as classes, but with a suffix that distinguishes them from instantiable classes. Within the Java standard library, interfaces are typically named with a suffix of "able" or "ible", eg. `Runnable`, `Closeable`, `Serializable`, `Comparable`, `Iterable`, etc. This convention MAY be carried over into userland libraries and applications.

Interfaces SHOULD NOT mirror exactly the names of the classes that implement them – this is a code smell, since it suggests the interface is too tightly coupled to a single implementation. But if there really is no better name for an interface, the interface name MAY take the class name plus the suffix "Contract".

Interfaces SHOULD NOT be prefixed or suffixed with "I" or "Interface". This convention is more common in other languages like C#, but is not widely used in Java.

Test classes MUST have a name that ends with `Test`. If the test covers a single class, the test class name SHOULD be the name of the class being tested, with `Test` appended.

== Method names

Methods MUST be named using lowerCamelCase.

Method names SHOULD, typically, be verbs or verb phrases, eg. `sendMessage`, `stop`, `computeTotal`.

Underscores MAY be used in JUnit test methods to separate logical components of the name, with each component written lowerCamelCase, eg. `transferMoney_deductsFromSource`.

== Field, variable, and parameter names

Fields, variables (including local variables), and parameters MUST use the same naming convention as methods: lowerCamelCase.

These SHOULD mostly be nouns or noun phrases, eg. `index`, `height`, `computedValues`.

One-character parameter names in public methods SHOULD be avoided.

== Constant names

A "constant" is defined here as a static final field whose contents are deeply immutable and whose methods have no detectable side effects (merely _intending_ to never mutate the object is not sufficient). Examples include primitives, strings, immutable value classes, and anything set to `null`.

Even when final and immutable, local variables are not considered to be constants, and SHOULD NOT therefore be styled as constants.

Constants MUST be named using UPPER_SNAKE_CASE: all uppercase letters, with words delimited by a single underscore.

Constant names are typically nouns or noun phrases.

[source,java]
----
/*
Constants.
*/

static final int NUMBER = 5;

static final ImmutableList<String> NAMES = ImmutableList.of("Ed", "Ann");

static final Map<String, Integer> AGES = ImmutableMap.of("Ed", 35, "Ann", 32);

/* Joiner is immutable. */
static final Joiner COMMA_JOINER = Joiner.on(',');

static final SomeMutableType[] EMPTY_ARRAY = {};

/*
Not constants.
*/

static String nonFinal = "non-final";

final String nonStatic = "non-static";

static final Set<String> mutableCollection = new HashSet<String>();

static final ImmutableSet<SomeMutableType> mutableElements = ImmutableSet.of(mutable);

static final ImmutableMap<String, SomeMutableType> mutableValues =
    ImmutableMap.of("Ed", mutableInstance, "Ann", mutableInstance2);

static final Logger logger = Logger.getLogger(MyClass.getName());

static final String[] nonEmptyArray = {"these", "can", "change"};
----

== Type variable names

Type variables SHOULD be named in one of two ways:

* A single capital letter, optionally followed by a single numeral, eg. `T`, `E`, `X`, `T2`, `T3`.

* The class or interface name from which the type variable is derived, with the capital letter `T` appended, eg. `RequestT`.

== Annotation names

Surprisingly, there are no well-established conventions for naming annotation types in Java. The prevailing convention seems to be UpperCamelCase, but this is far from universal.

This coding standard RECOMMENDS that annotation types be named using UpperCamelCase, eg. `@CheckReturnValue`, for consistency with the prevailing convention.

Annotation names MAY be verbs or nouns, depending on their purpose.
