= Comments

Java supports three comment notations:

* `//`
* `/* … */`
* `/** … */`

The code below represents this style guide's RECOMMENDATIONS for using Java's
single-line (`//`) and multi-line (`/* … \*/`) comment syntax. These are used
for _implementation_ comments, while Javadoc comments (`/** … */`) are used for
_API documentation_ comments.

The single-line implementation comment syntax is used in two use cases:

* To comment-out code.

* For short end-of-line comments that decode or explain a value assigned,
returned, or printed by the statement.

Java's multi-line implementation comment syntax, `/* … \*/`, SHOULD, in fact, be
used for both single-line and multi-line implementation comments. For short
comments that can fit between the indentation level and the soft line limit, the
opening `/*` and closing `\*/` SHOULD be written on the same line as the
comment. But as soon as the comment text needs to be wrapped to two or more
lines, the opening `/*` and the closing `*/` SHOULD be bumped to their own
lines.

[source,java]
----
int num1 = 7;
int num2 = 5;
// int num0 = 0;

/*
Modulus operator (%) returns the remainder after the first operand
is *evenly* divided by the second operand. In this case, 7 / 5 = 1,
with a remainder of 2.
*/

int modulus = num1 % num2;
System.out.println(modulus); // 2

/* 7 divides evenly into 3 twice (3x2=6) with a reminder of 1 (7-6=1). */
System.out.println(7 % 3); // 2

/*
The modulus operator is often used to determine whether a number is
even or odd. If x % 2 is 0, then x is even, otherwise it is odd.
*/

System.out.println(6 % 2); // 0
System.out.println(7 % 2); // 1
----

Where the multi-line comment syntax `/* … \*/` is used to encapsulate a
single-line comment, there MUST be exactly one space after the opening `/*` and
another before the closing `*/`. The single-line comment syntax `//` MUST be
followed by exactly one space and then the code or value.

Block-level comments MUST be indented to the same level as the code to which
they relate.

Multi-line block-level comments SHOULD have an empty line both before and after
the comment block. Single-line block-level comments SHOULD have an empty line
before them, and MAY have a blank line after.

Optionally, additional empty lines MAY be written within the text of block-level
comments, to break it up into paragraphs. This is particularly beneficial for
the readability of very long comments.

All text within `/* … */` comments MUST be written in full sentences, each
starting with a capitalized word and terminated by a period (full stop).

Implementation comments SHOULD only communicate information that is not readily
available from the code itself, but which is relevant to the understanding of
that code. For example, implementation comments SHOULD be used to document the
reasons behind a particular choice of design pattern that, without context, may
seem unusual or even counterintuitive to some developers who are looking at the
code for the first time.

Implementation comments SHOULD NOT be used to specify the API or behavior of the
code (that's the purpose of Javadocs), nor should they be used to explain things
like how to build or test the code (that sort of documentation is better placed
in READMEs or other out-of-band documentation).

== Javadoc

Javadoc comments are used to document the internal API of a Java program. They
are parsed by various tools, including those embedded in IDEs, to generate
developer documentation.

Javadoc is used to document the purpose, behavior, specification, and usage of
program elements. Javadoc is a developer tool, intended to help yourself and
other developers to understand, maintain, change, and extend the code.

Javadoc MUST NOT be used to document implementation details, such as the
algorithms used in a method. Standard comments MUST be used for that purpose.

Javadoc SHOULD be used to document all `public` classes and every `public` and
`protected` member of such classes. Javadoc MAY be skipped for methods that
override a supertype method that is already documented; the supertype method's
documentation is inherited.

Additional Javadoc content MAY be added to other block-level constructs, as
needed or desired. Javadoc content SHOULD NOT duplicate the information encoded
in method names or signatures, or other adjacent code.

The following is an example of redundant Javadoc. It would be better used to
explain the meaning of "canonical name" in this context.

[source,java]
----
/**
 * Returns the canonical name of this object.
 */
public string getCanonicalName() {
  // …
}
----

There are two notations for Javadocs: multi-line and single-line:

[source,java]
----
/**
 * Multiple lines of Javadoc text are written here,
 * wrapped normally...
 */

/** An especially short bit of Javadoc. */
----

The single-line form SHOULD be used for very short comments with no accompanying
block tags such as `@return`.

In the multi-line form, the Javadoc content MAY be formatted into multiple
paragraphs, with each paragraph separated by a blank line (that is, a line
containing only the aligned leading asterisk, `*`).

The first paragraph SHOULD be a brief summary fragment. This MUST be written as
a complete sentence, but it SHOULD NOT be a detailed description.

After the first summary paragraph, each subsequent paragraph MUST be prefixed
with `<p>`, immediately before the first word and with no space between it and
the first word. Alternatively, the `<p>` MAY be substituted for other
block-level tags such as `<ul>`.

The standard block tags are:

* `@param` for method parameters
* `@return` for the return value of a method
* `@throws` for exceptions thrown by a method
* `@deprecated` to indicate that a method is deprecated

The block tags MUST be each written on a separate line, in the order above. All
block tags MUST be followed by a space and then a text description. When the
description is long, it SHOULD be wrapped with continuation lines indented four
spaces from the position of the `@` symbol.

A common mistake is to use block tags in single-line Javadoc comments, eg.:

----
/** @return the customer ID */
----

This is invalid Javadoc syntax. This should be:

----
/** Returns the customer ID. */
----
