[#include-directive]
= Include directive

The {link-asciidoctor-include}[include directive] is used to include the content from another file in the current document. It helps to keep AsciiDoc files small and modular. Documentation sites and technical books are thus _composed_ from lots of files being included in one main file. Include directives also allow reusing of content — such as code examples — in multiple places.

An include directive is written in the following form, on a line of its own.

[source,asciidoc]
----
\include::<path>/file[<attrlist>]
----

The `attrlist` is OPTIONAL and can contain one or more comma-separated attributes that modify the behavior of the include directive. For example, `leveloffset=+1` will adjust the section levels of the included file. Heading level 1 (`=`) will become level 2 (`==`), level 2 will become level 3, and so on. The `lines` and `tag` attributes include only part of a file.

Include directives are resolved before the rest of the document is parsed, so they are processed everywhere, including inside code blocks. To show an include directive literally, as in the example above, prefix it with a backslash (`\`).

Antora imposes some additional constraints on how files can be included in AsciiDoc source files. See <<antora,Antora>>.
