= Include directive

The
https://asciidoctor.org/docs/user-manual/#include-directive[include directive]
is used to include the content from another file in the current document.

It is RECOMMENDED to use include directive extensively. This helps to keep
AsciiDoc files small and modular. Documentation sites and technical books are
thus _composed_ from lots of files being included in one main file. Includes
directives also allow reusing of content – such as code examples – in multiple
places.

An include directive is written in the following form:

```
\include::<path>/file[<attrlist>]
```

The `attrlist` is OPTIONAL and can contain one or more comma-separated
attributes that modify the behavior of the include directive. For exampke,
`leveloffset=+1` will adjust the section levels of the included file; heading
level 1 (`=`) will become level 2 (`==`), level 2 will become level 3, and so
on.

== Antora

https://antora.org/[Antora] is a documentation generation tool. It creates
documentation websites from structured hierarchies of AsciiDoc files and other
assets. Antora imposes some additional constraints on how files can be included
in AsciiDoc source files. The following conventions MUST be followed:

* All documents are saved in the `modules/<module-name>/pages/<path>` directory.
* All images are saved in `modules/<module-name>/assets/images/<path>`.
* All examples are saved in `modules/<module-name>/examples/<path>`.

When using paths to include something , you might need to use the
`<module-name>` component when linking to another module, but you MUST NOT use
`pages`, `assets/image`, or `examples` in the path component – only the `<path>`
bit.

If you include a standard page – a page that is stored in the `pages` directory
– into another page, you MUST set the `page-partial` AsciiDoc attribute in the
document header of the page being included.

```
= The Page Header
:page-partial:

Page contents.
```
