= Admonitions

AsciiDoc admonitions are callout boxes for rendering things like tips, important
information, warnings, and errors. There are actually five supported admonition
types:

* `NOTE`
* `TIP`
* `IMPORTANT`
* `CAUTION`
* `WARNING`

Simple admonitions can be written using the following syntax, where `<label>` is
one of the above admonition types (written full upper case).

```
<label>: Text...
```

But the complex admonition syntax is RECOMMENDED. This helps admonitions to
stand-out in the plain text AsciiDoc files themselves. Complex admonitions also
support nesting of other block-level markup such as tables, lists, and literal
text blocks.

```
[<label>]
====
Text...
====
```

Example:

```
[TIP]
====
We strongly encourage you to put your server in single user mode before setting up encryption.

To do so, run the following command:

....
sudo -u www-data occ maintenance:singleuser --on
....
====
```

For guidance on when to use each admonition type, and how sparingly, see
*link:../026/README.adoc[TS-26: Technical Writing Style Guide]*.
