= Links

In AsciiDoc, links can be either external or internal.

* External links reference content outside the documentation, such as a web page.
* Internal links reference content inside the documentation, such as another page or a section within a document.

== External links

An external link SHOULD be written using the following syntax:

```
http(s)://domain/path?query#anchor[Hyperlinked text]
```

The `[Hyperlinked text]` part is optional. If it is omitted, the URL itself will be used as the hyperlink text.

For external links, the `link:` prefix is required only when the target is not a URI. AsciiDoc recognizes `http:` and `https:` as URI protocols and handles them as implicit `link:` macros.

If you want to prevent a link from being automatically hyperlinked, prepend it with a backslash (`\`). The text will be rendered verbatim as normal (non-clickable) text.

```
\https://www.example.com/
```

A URL may not display correctly when it contains characters such as underscores (`_`), carets (`^`), or double quotes (`"`). The following is an example of a URL containing characters that need special treatment. See https://asciidoctor.org/docs/user-manual/#complex-urls[Troubleshooting URLs] for help solving this.

```
https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)
```

For long URLs, it is RECOMMENDED to use an attribute to define the URL and then reference the attribute in the link. This makes the AsciiDoc source more readable.

```
= The Page Header
:link-name: https://example.com/content/link_can_be_very_long

Text {link-name}[highlighted text] text.
```

For clarity, it is RECOMMENDED to prefix the names of link attributes with `link-`.

== Internal Links

Internal links are used to create cross-referenced to:

* an in-page reference;
* a documentation file;
* a section title or anchor name inside a documentation file.

In Antora, all referenced content MUST be inside the `modules` directory. Antora has particular conventions for referencing content in other modules – refer to Antora's documentation for more details.

[TIP]
======
Use a link checker to audit for broken links.
======
