= Lists

To create a list, prefix each item in the list with the `*` sign followed by a single space.

To created nested lists, use multiple `*` signs according to the nesting level.

```
* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1
```

AsciiDoctor also supports the hyphen (`-`) as a Markdown-style list marker. However, this syntax does not support nested lists. Markdown-style indentation-style nesting will produce a flat list in AsciiDoctor output. For this reason, Markdown-style syntax SHOULD NOT be used for lists in AsciiDoc.

When list items contain more than one line of text, indent the subsequent lines by at least one space to make it clear that they belong to the same list item. In addition, leave a blank line before the next item.

```
* This is the first line of the item.
  This is a continuation of the same item.

* This is a separate item.

* This is another item in the same list.
```

For guidance on when to use numbered versus bulleted lists, and on punctuation and parallelism within list items, see *link:../026/README.adoc[TS-26: Technical Writing Style Guide]*.
