= TS-28: AsciiDoc
:toc: macro
:toc-title: Contents

AsciiDoc is RECOMMENDED for technical documentation. AsciiDoc is preferred over
other lightweight human-editable markup languages such as Markdown as it is
specifically designed for technical writing, it supports embedded diagrams and
lots of other valuable features, and it has great tooling for publishing content
to different formats.

This technical standard offers tips and best practices for writing AsciiDoc, and
for using tools such as https://asciidoctor.org/[AsciiDoctor] and
https://antora.org/[Antora] to process AsciiDoc files.

For a complete language reference, see the [Asciidoctor
Documentation](https://asciidoctor.org/docs/). The AsciiDoctor website also has
a useful [AsciiDoc Syntax Quick
Reference](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/)
guide.

.AsciiDoc versus AsciiDoctor
****
AsciiDoc is the language specification. AsciiDoctor is a particular
implementation; it is a free and open source tool for the processing of AsciiDoc
files to HTML5, DocBook 5, PDF, and other formats.
****

toc::[]

include::./01-markdown-syntax.adoc[leveloffset=+1]
include::./02-file-extensions.adoc[leveloffset=+1]
include::./03-attributes.adoc[leveloffset=+1]
include::./04-include-directive.adoc[leveloffset=+1]
include::./05-table-of-contents.adoc[leveloffset=+1]
include::./06-code-blocks.adoc[leveloffset=+1]
include::./07-literal-text-and-blocks.adoc[leveloffset=+1]
include::./08-images.adoc[leveloffset=+1]
include::./09-admonitions.adoc[leveloffset=+1]
include::./10-air-quotes.adoc[leveloffset=+1]
include::./11-preserving-line-breaks.adoc[leveloffset=+1]
include::./12-unbreakable-blocks.adoc[leveloffset=+1]
include::./13-links.adoc[leveloffset=+1]
include::./14-sections-headers-and-titles.adoc[leveloffset=+1]
include::./15-level-1-section-title.adoc[leveloffset=+1]
include::./16-lists.adoc[leveloffset=+1]
include::./17-tables.adoc[leveloffset=+1]
include::./18-keyboard-shortcuts-and-ui-button-text.adoc[leveloffset=+1]
include::./19-menu-selections.adoc[leveloffset=+1]
include::./20-conditional-rendering.adoc[leveloffset=+1]
include::./21-comments.adoc[leveloffset=+1]
include::./22-asciidoctor-extensions.adoc[leveloffset=+1]
include::./23-line-length.adoc[leveloffset=+1]
