= TS-62: Make
:toc: macro
:toc-title: Contents

This technical standard covers best practices for writing `Makefile`s, using
https://www.gnu.org/software/make/[GNU Make] as the reference implementation.

Makefiles are commonly used as a language-agnostic task runner – a thin,
discoverable interface over project scripts, builds, and other repeated
commands.

It is RECOMMENDED that all code repositories that include scripts and run
commands for automating development and operations processes include a Makefile
to encapsulate all the available scripts centrally.

See also:

* *link:../031/README.adoc[TS-31: Unix Shells and POSIX Standards]* and
  *link:../032/README.adoc[TS-32: Bash]* for guidance on the shell scripts and
  recipes invoked from within Makefile targets.

* *link:../016/README.adoc[TS-16: Command Line Interfaces]* for
  general guidance on designing CLIs.

* *link:../058/README.adoc[TS-58: Docker]* for guidance on the container build
  and run commands that Makefile targets often wrap.

toc::[]

include::./01-self-documenting-makefiles.adoc[leveloffset=+1]

''''

== References

* https://www.gnu.org/software/make/manual/make.html[GNU Make manual]
  — Official documentation.

* https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html[Auto-Documented Makefile]
  by Marmelab — origin of the `##` self-documentation convention covered in
  this standard.
