= TS-2: Software design qualities
:toc: macro
:toc-title: Contents

:link-bite-size-tech:   https://web.archive.org/web/20250315132607/https://www.16elt.com/2024/09/25/first-book-of-byte-sized-tech/
:link-mckinley:         https://www.youtube.com/watch?v=SZOeV-S-2co
:link-moseley-marks:    https://moss.cs.iit.edu/cs100/papers/out-of-the-tar-pit.pdf
:link-no-complexity:    https://nocomplexity.com/documents/0complexity/0cxdesignprinciples.html
:link-no-silver-bullet: http://web.archive.org/web/20221209212653/http://www.cs.unc.edu/techreports/86-020.pdf
:link-wiegers:          https://stackoverflow.blog/2022/01/17/plan-for-tradeoffs-you-cant-optimize-all-software-quality-attributes/
:link-worse-is-better:  https://dreamsongs.com/RiseOfWorseIsBetter.html

This technical standard establishes nine core qualities for evaluating a software system's design. In no particular
order, these qualities are the following.

1.  *Completeness.* Whether a software system provides all the functions and behaviors its users need.
2.  *Correctness.* A system's ability to maintain valid, consistent state.
3.  *Performance.* How well a system operates within its specified constraints — latency, throughput, availability,
    security, and other dynamic quality attributes that are observed at runtime.
4.  *Reliability.* A system's ability to handle and recover from failures of all kinds.
5.  *Experience.* How a system is perceived by its users.
6.  *Habitability.* How easy a system is for developers to maintain and evolve.
7.  *Cohesiveness.* To what degree a system's design forms a unified, consistent whole.
8.  *Changeability.* The ease with which software can be adapted to changing requirements.
9.  *Simplicity.* How well a system minimizes unnecessary complexity in both its interface and implementation.

These software qualities are universal. They have an impact at every abstraction level within a system's architecture,
and they are relevant to all types of software – whatever the runtime environment, whatever the programming language,
and whether the system is distributed or single-node.

No priority should be assumed from the order in which these qualities are presented. Their relative importance will
differ between business domains and architectural styles. But _all_ these qualities are of importance in _every_
software system to some degree.

It's best not to view these qualities as being mutually exclusive. In fact, there's much overlap between them and they
reinforce one another. For example, the design constraints necessary to make a system fast and responsive tend also
to result in system designs that are simple, easy to change, and fault-tolerant. Taken as a whole, these quality
attributes form a cohesive software design philosophy.

Some trade-offs are involved where qualities compete with one another for priority in a design. This is the subject
of the final section of this technical standard.

This technical standard also touches upon the software design _process_ itself. Topics such as iterative and incremental
development, feedback loops, and domain modeling are mentioned. After all, these are important methods and tools to help
us achieve our design goals. But the focus of this technical standard is the end result – what good software
architecture looks like – not the means of getting there.

Related standards include xref:005.adoc[*TS-5: Application architecture*], which covers architectural patterns for
single-node applications, and xref:007.adoc[*TS-7: Code design*], which covers low-level concerns such as code
formatting and exception handling.

toc::[]

include::partial$002/01-completeness.adoc[leveloffset=+1]
include::partial$002/02-correctness.adoc[leveloffset=+1]
include::partial$002/03-performance.adoc[leveloffset=+1]
include::partial$002/04-reliability.adoc[leveloffset=+1]
include::partial$002/05-experience.adoc[leveloffset=+1]
include::partial$002/06-habitability.adoc[leveloffset=+1]
include::partial$002/07-cohesiveness.adoc[leveloffset=+1]
include::partial$002/08-changeability.adoc[leveloffset=+1]
include::partial$002/09-simplicity.adoc[leveloffset=+1]
include::partial$002/10-trade-offs.adoc[leveloffset=+1]

''''

== References

* Ousterhout, J (2018).
  _A Philosophy of Software Design_.

* Brooks, F (1986).
  {link-no-silver-bullet}[_No Silver Bullet: Essence and Accident in Software Engineering_].

* Moseley and Marks (2006).
  {link-moseley-marks}[_Out of the Tar Pit_]

* Gabriel, R P (1991).
  {link-worse-is-better}[_The Rise of Worse is Better_].

* Wiegers, K (2022).
  {link-wiegers}[_Plan for Tradeoffs: You Can't Optimize All Software Quality Attributes_].
  Stack Overflow.

* 16 Bit Terminal (2024).
  {link-bite-size-tech}[_The First Book of Byte-Sized Tech_].

* NoComplexity.
  {link-no-complexity}[_Complexity Design Principles_].

* McKinley, D (2015).
  {link-mckinley}[_Data-Driven Done Right_].
