= TS-16: Command line interfaces (CLIs)
:toc: macro
:toc-title: Contents

This technical standard covers the design of command line interfaces (CLIs). The
focus here is on designing CLI utilities for Unix-based environments, but the
guidelines are intended to be applicable to the CLIs of programs running in all
kinds of environments – Windows, Node.js, Python, Java, etc.

These technical standards build on the
https://clig.dev/[Command Line Interface Guidelines], an excellent open source
guide to writing better command line programs. Other references are listed at
the end of this document.

CLIs are a type of UI, and therefore this technical standard can be seen as an
extension of *xref:015.adoc[TS-15: User interfaces]*. Terminal user
interfaces (TUIs), which are full-screen terminal programs like Vim and Emacs,
are not addressed by this standard. This standard is all about designing
interactive command-oriented CLI utilities.

See also *xref:062.adoc[TS-62: Make]* for guidance on Makefiles,
which are commonly used to expose a project's scripts as a discoverable,
CLI-like set of targets.

toc::[]

include::partial$016/01-principles.adoc[leveloffset=+1]
include::partial$016/02-naming.adoc[leveloffset=+1]
include::partial$016/03-distribution.adoc[leveloffset=+1]
include::partial$016/04-options.adoc[leveloffset=+1]
include::partial$016/05-subcommands.adoc[leveloffset=+1]
include::partial$016/06-interactivity.adoc[leveloffset=+1]
include::partial$016/07-piping.adoc[leveloffset=+1]
include::partial$016/08-exit-codes.adoc[leveloffset=+1]
include::partial$016/09-output.adoc[leveloffset=+1]
include::partial$016/10-errors.adoc[leveloffset=+1]
include::partial$016/11-documentation.adoc[leveloffset=+1]

''''

== References

* https://clig.dev/[_Command Line Interface Guidelines_]. — A free, open source,
  online guide to writing better command line programs, taking traditional Unix
  principles and updating them for the modern day.

* Stallman, R et al.
  https://www.gnu.org/prep/standards/html_node/index.html[_GNU Coding Standards_].
  Free Software Foundation. — Coding guidelines for GNU projects. It focuses on
  writing programs in C, but much of this covers the command line interface and
  many of the core guidelines are applicable to all CLIs.

* Tashian, C.
  https://smallstep.com/blog/the-poetics-of-cli-command-names/[_The Poetics of CLI Command Names_].
  Smallstep. — Sound advice on naming CLI commands.

* Starich, J (2019).
  https://uxdesign.cc/user-experience-clis-and-breaking-the-world-baed8709244f[_User Experience, CLIs, and Breaking the World_].
  UX Collective. — Lessons learnt from revamping the CLI for the IBM Cloud
  Kubernetes Service.

* Heroku.
  https://devcenter.heroku.com/articles/cli-style-guide[_Heroku CLI Style Guide_].
  — Design guidelines for CLI plugins for the Heroku platform.

* Dickey, J (2018).
  https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46[_12 Factor CLI Apps_].
  Medium. — Adapts Heroku's https://12factor.net/[12 factor app] principles to
  CLI programs. These design principles were codified in
  https://oclif.io/[Oclif], a framework for CLI apps running in Node.

* The Open Group.
  https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html[_Utility Conventions_].
  POSIX. — Describes the argument syntax of standard UNIX utilities, and defines
  a notation for documenting utility arguments.
