= TS-16: Command line interfaces (CLIs)
:toc: macro
:toc-title: Contents

:link-clig: https://clig.dev/

This technical standard covers the design of command line interfaces (CLIs). The focus here is on designing CLI
utilities for Unix-based environments, but the guidelines are intended to be applicable to the CLIs of programs running
in all kinds of environments – Windows, Node.js, Python, Java, etc.

These technical standards build on the {link-clig}[Command Line Interface Guidelines], an excellent open source
guide to writing better command line programs. Other references are listed at the end of this document.

CLIs are a type of UI, and therefore this technical standard can be seen as an extension of
xref:015.adoc[*TS-15: User interfaces*]. Terminal user interfaces (TUIs), which are full-screen terminal programs like
Vim and Emacs, are not addressed by this standard. This standard is all about designing interactive command-oriented CLI
utilities.

See also xref:062.adoc[*TS-62: Make*] for guidance on Makefiles, which are commonly used to expose a project's scripts
as a discoverable, CLI-like set of targets.

toc::[]

include::partial$016/01-principles.adoc[leveloffset=+1]
include::partial$016/02-naming.adoc[leveloffset=+1]
include::partial$016/03-distribution.adoc[leveloffset=+1]
include::partial$016/04-options.adoc[leveloffset=+1]
include::partial$016/05-subcommands.adoc[leveloffset=+1]
include::partial$016/06-interactivity.adoc[leveloffset=+1]
include::partial$016/07-piping.adoc[leveloffset=+1]
include::partial$016/08-exit-codes.adoc[leveloffset=+1]
include::partial$016/09-output.adoc[leveloffset=+1]
include::partial$016/10-errors.adoc[leveloffset=+1]
include::partial$016/11-documentation.adoc[leveloffset=+1]

''''

include::partial$016/99-references.adoc[leveloffset=+1]
