= TS-22: Webhooks
:toc: macro
:toc-title: Contents

This technical standard extends *xref:021-http-apis.adoc[TS-21: HTTP APIs]* with
specific guidance on the design of webhooks.

There are alternative mechanisms for pushing data to clients in real-time, like
WebSockets and Server Sent Events, but these are outside the scope of this
standard.

toc::[]

include::partial$022/01-definitions.adoc[leveloffset=+1]
include::partial$022/02-consumers.adoc[leveloffset=+1]
include::partial$022/03-producers.adoc[leveloffset=+1]

''''

== References

* https://www.standardwebhooks.com/[_Standard Webhooks_]. — A well-designed
  standard for webhook implementations, drawing on industry best practices. This
  technical standard is based on Standard Webhooks and is fully compliant with
  it.

* IETF (2024).
  https://datatracker.ietf.org/doc/rfc9421/[_RFC 9421: HTTP Message Signatures_].
  — A standard solution to create, encode, and verify HTTP message signatures.
  https://httpsig.org/[httpsig.org] is an online sandbox to try these out
  interactively, plus links to implementations in multiple programming
  languages. This design is much more flexible than Standard Webhooks — for
  example, producers can specify which parts of their message are signed — but
  this flexibility will not be required for the majority of webhook use cases,
  and it comes at much-increased costs for consumers to integrate with.
  Nevertheless, RFC 9421 may be a better option for some niche use cases.

* https://cloudevents.io/[_CloudEvents_]. CNCF. — A specification for describing
  event data in a common way. It focuses on the event format (the payload)
  rather than other concerns such as the transport and authentication
  mechanisms. See also the
  https://github.com/cloudevents/spec/blob/main/cloudevents/http-webhook.md[Web Hooks for Event Delivery]
  specification.

* OpenID Foundation.
  https://openid.net/wg/sharedsignals/[_Shared Signals Framework (SSF)_]. —
  Effectively a standard for generalized webhooks, although the purpose of the
  standard is more targeted. SSF is intended to improve the interoperability and
  privacy of identity and access control systems. It enables the secure,
  real-time communication of security-related events, things like account
  compromise and session revocation. There are some useful security guidelines
  herein, but the standard is not widely adopted outside of the domain of
  identity and access management.

* Zapier.
  https://web.archive.org/web/20220914184737/http://resthooks.org/[_RestHooks_]
  (https://github.com/zapier/resthooks[repository]). — An earlier
  standardization effort, now inactive.

* https://webhooks.fyi/[_webhooks.fyi_]. — Not a standardization effort, but a
  useful community-maintained collection of resources about webhooks.

* Chatrbahr, A (2020).
  https://medium.com/prospa-technology/webhooks-done-right-676d4e74578a[_Webhooks Done Right_].
  Prospa Technology. — Sound guidance on building a webhook event publishing
  service.
