= TS-27: Markdown
:toc: macro
:toc-title: Contents

Markdown is a lightweight human-editable markup language. It is widely used for
simple documentation such as `README` files, contribution guides, changelogs,
pull request descriptions, and code comments, and it is supported by many source
code hosting platforms, issue trackers, and chat tools.

For technical documentation that requires tables of contents, cross-references,
included files, admonitions, or diagrams, AsciiDoc is RECOMMENDED instead. See
*xref:028-asciidoc.adoc[TS-28: AsciiDoc]*.

This technical standard offers tips and best practices for writing Markdown. It
recommends GitHub Flavored Markdown (GFM), a strict superset of the CommonMark
specification, as the baseline dialect.

For a complete language reference, see the
https://spec.commonmark.org/[CommonMark Specification] and the
https://github.github.com/gfm/[GitHub Flavored Markdown Specification].

.Markdown versus CommonMark versus GFM
****
Original Markdown, designed by John Gruber in 2004, is underspecified and has
many incompatible interpretations. CommonMark is an effort to provide an
unambiguous, standardized specification. GitHub Flavored Markdown (GFM) is a
strict superset of CommonMark that adds tables, strikethrough, task lists, and
autolinks.
****

toc::[]

include::partial$027/01-overview.adoc[leveloffset=+1]
include::partial$027/02-flavors.adoc[leveloffset=+1]
include::partial$027/03-file-extensions.adoc[leveloffset=+1]
include::partial$027/04-headings.adoc[leveloffset=+1]
include::partial$027/05-paragraphs-and-line-breaks.adoc[leveloffset=+1]
include::partial$027/06-emphasis.adoc[leveloffset=+1]
include::partial$027/07-lists.adoc[leveloffset=+1] include::partial$027/08-code.adoc[leveloffset=+1]
include::partial$027/09-links.adoc[leveloffset=+1]
include::partial$027/10-images.adoc[leveloffset=+1]
include::partial$027/11-blockquotes.adoc[leveloffset=+1]
include::partial$027/12-callouts.adoc[leveloffset=+1]
include::partial$027/13-tables.adoc[leveloffset=+1]
include::partial$027/14-horizontal-rules.adoc[leveloffset=+1]
include::partial$027/15-escaping-characters.adoc[leveloffset=+1]
include::partial$027/16-html.adoc[leveloffset=+1]
include::partial$027/17-footnotes.adoc[leveloffset=+1]
include::partial$027/18-line-length.adoc[leveloffset=+1]
include::partial$027/19-tooling.adoc[leveloffset=+1]
