= TS-36: ECMAScript (JavaScript/TypeScript)
:toc: macro
:toc-title: Contents

:link-airbnb-js: https://github.com/airbnb/javascript
:link-airbnb-css-in-js: https://github.com/airbnb/javascript/tree/master/css-in-javascript
:link-google-jsguide: https://google.github.io/styleguide/jsguide.html
:link-google-jsguide-pre-es6: https://google.github.io/styleguide/javascriptguide.xml
:link-waldron-idiomatic-js: https://github.com/rwaldron/idiomatic.js
:link-standardjs: https://standardjs.com
:link-geisendorfer-node-style: https://github.com/felixge/node-style-guide
:link-sta-cruz-rsjs: https://ricostacruz.com/rsjs/
:link-adobe-js-coding-standard: https://developer.adobe.com/commerce/php/coding-standards/js/
:link-platypi-typescript: https://github.com/Platypi/style_typescript
:link-mcdermott-clean-code-js: https://github.com/ryanmcdermott/clean-code-javascript
:link-clean-code-typescript: https://github.com/labs42io/clean-code-typescript
:link-goldberg-node-best-practices: https://github.com/goldbergyoni/nodebestpractices
:link-deslauriers-module-best-practices: https://github.com/mattdesl/module-best-practices
:link-elliott-fp-interview: https://medium.com/javascript-scene/master-the-javascript-interview-what-is-functional-programming-7f218c68b3a0
:link-elliott-two-pillars: https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4
:link-lonsdorf-professor-frisby-course: https://egghead.io/courses/professor-frisby-introduces-composable-functional-javascript
:link-lonsdorf-mostly-adequate-guide: https://mostly-adequate.gitbook.io/mostly-adequate-guide
:link-simpson-functional-light-js: https://github.com/getify/Functional-Light-JS/tree/master
:link-salcescu-discover-fp-js: https://www.amazon.co.uk/dp/B07PBQJYYG
:link-johansen-pure-js: https://vimeo.com/49384334
:link-7urtle-fp-advantages: https://www.7urtle.com/javascript-functional-programming-advantages
:link-hewlett-taylor-tacit: https://dev.to/tomht/a-light-introduction-to-tacit-programming-with-javascript-3jm2
:link-haverbeke-eloquent-js-fp: https://eloquentjavascript.net/1st_edition/chapter6.html
:link-gechev-2013: https://blog.mgechev.com/2013/01/21/functional-programming-with-javascript/
:link-oxley-functional-js-workshop: https://github.com/timoxley/functional-javascript-workshop
:link-rinaldi-frp-js: https://modernweb.com/functional-reactive-programming-in-javascript/
:link-iffland-2016: https://www.infoq.com/articles/virtual-panel-reactive-javascript-and-elm-in-2016
:link-podwysocki-2010: https://www.codebetter.com/matthewpodwysocki/2010/02/16/introduction-to-the-reactive-extensions-to-javascript/
:link-osmani-2012: https://www.smashingmagazine.com/2012/11/writing-fast-memory-efficient-javascript/
:link-osmani-startup-perf: https://medium.com/dev-channel/javascript-start-up-performance-69200f43b201
:link-baker-arvidsson-optimizing-js: https://developers.google.com/speed/articles/optimizing-javascript
:link-mythbusters-js: https://mythbusters.js.org/
:link-mythbusters-js-repo: https://github.com/Kikobeats/js-mythbusters
:link-husain-async-programming: https://egghead.io/courses/asynchronous-programming-the-end-of-the-loop
:link-severien-readable-code: https://www.sitepoint.com/importance-of-code-that-humans-can-read/
:link-ronacher-2022: https://lucumr.pocoo.org/2022/1/10/dependency-risk-and-funding/
:link-pragmatic-engineer-bluesky-2024: https://newsletter.pragmaticengineer.com/p/bluesky-engineering-culture

This technical standard covers coding conventions for ECMAScript-based languages – JavaScript and TypeScript.

[quote]
____
Java is to JavaScript +
as Car is to Carpet.
____

toc::[]

include::partial$036/01-language-fundamentals.adoc[leveloffset=+1]
include::partial$036/02-syntax-and-style.adoc[leveloffset=+1]
include::partial$036/03-functions.adoc[leveloffset=+1]
include::partial$036/04-objects-and-classes.adoc[leveloffset=+1]
include::partial$036/05-modules.adoc[leveloffset=+1]
include::partial$036/06-packages-and-tooling.adoc[leveloffset=+1]
include::partial$036/07-dependency-management.adoc[leveloffset=+1]
include::partial$036/08-typescript.adoc[leveloffset=+1]
include::partial$036/09-asynchronous-programming.adoc[leveloffset=+1]
include::partial$036/10-functional-programming.adoc[leveloffset=+1]
include::partial$036/11-runtimes.adoc[leveloffset=+1]
include::partial$036/12-architecture-and-design.adoc[leveloffset=+1]
include::partial$036/13-quality-assurance.adoc[leveloffset=+1]
include::partial$036/14-barrel-files.adoc[leveloffset=+1]

''''

[#references]
== References

* Airbnb (n.d.).
  {link-airbnb-js}[_Airbnb JavaScript Style Guide_].
  GitHub.
  — One of the most widely-cited JavaScript coding standards; see also
  the companion {link-airbnb-css-in-js}[CSS-in-JavaScript Style Guide].

* Google (n.d.).
  {link-google-jsguide}[_Google JavaScript Style Guide_].
  — Google's coding standards for JavaScript; see also the
  {link-google-jsguide-pre-es6}[pre-ES6 version].

* Waldron, R (n.d.).
  {link-waldron-idiomatic-js}[_Idiomatic.js_].
  GitHub.
  — A community set of best practices and coding conventions for JavaScript.

* Aboukhadijeh, F (n.d.).
  {link-standardjs}[_Standard JS_].
  — An opinionated, semicolon-free JavaScript style with a linter and automatic code fixer.

* Geisendörfer, F (n.d.).
  {link-geisendorfer-node-style}[_Felix's Node Style Guide_].
  GitHub.
  — A Node.js coding style guide by Felix Geisendörfer.

* Sta. Cruz, R (n.d.).
  {link-sta-cruz-rsjs}[_RSJS_].
  — A "reasonable system for JavaScript structure" for non-SPA web applications.

* Adobe (n.d.).
  {link-adobe-js-coding-standard}[_Adobe JavaScript Coding Standard_].
  — In-house standard for Adobe Commerce and Magento.

* Platypi (n.d.).
  {link-platypi-typescript}[_Platypi TypeScript Style Guide_].
  GitHub.
  — A corporate style guide for JavaScript and TypeScript.

* McDermott, R (n.d.).
  {link-mcdermott-clean-code-js}[_clean-code-javascript_].
  GitHub.
  — Clean-code concepts adapted for JavaScript; see the
  {link-clean-code-typescript}[TypeScript adaptation].

* Goldberg, Y (n.d.).
  {link-goldberg-node-best-practices}[_Node.js Best Practices_].
  GitHub.
  — A popular, maintained community best-practices compendium for Node.js.

* DesLauriers, M (n.d.).
  {link-deslauriers-module-best-practices}[_Module Best Practices_].
  GitHub.
  — Best practices for writing Node-style modules.

* Elliott, E (n.d.).
  {link-elliott-fp-interview}[_Master the JavaScript Interview: What is Functional Programming?_].
  Medium.
  — An overview of functional programming applied to JavaScript.

* Elliott, E (n.d.).
  {link-elliott-two-pillars}[_The Two Pillars of JavaScript, Pt 2: Functional Programming_].
  Medium.
  — On prototypal inheritance and functional programming as JavaScript's two defining features.

* Lonsdorf, B (n.d.).
  {link-lonsdorf-professor-frisby-course}[_Professor Frisby Introduces Composable Functional JavaScript_].
  egghead.
  — A free video course introducing functional programming in JavaScript.

* Lonsdorf, B (n.d.).
  {link-lonsdorf-mostly-adequate-guide}[_Professor Frisby's Mostly Adequate Guide to Functional Programming in JavaScript_].
  — A free online book on functional programming in JavaScript.

* Simpson, K (n.d.).
  {link-simpson-functional-light-js}[_Functional-Light JavaScript_].
  GitHub.
  — A free online book on applying functional programming pragmatically in JavaScript.

* Salcescu, C (n.d.).
  {link-salcescu-discover-fp-js}[_Discover Functional JavaScript_].
  Amazon.
  — A book on functional programming techniques in JavaScript.

* Johansen, C (n.d.).
  {link-johansen-pure-js}[_Pure JavaScript_].
  Vimeo.
  — A video talk on functional programming in JavaScript.

* 7urtle (n.d.).
  {link-7urtle-fp-advantages}[_JavaScript Functional Programming Advantages_].
  — An article on the benefits of functional programming in JavaScript.

* Hewlett-Taylor, T (n.d.).
  {link-hewlett-taylor-tacit}[_A Light Introduction to Tacit Programming with JavaScript_].
  dev.to.
  — An introduction to point-free style in JavaScript.

* Haverbeke, M (n.d.).
  {link-haverbeke-eloquent-js-fp}[_Eloquent JavaScript: Functional Programming_].
  — The functional programming chapter from the first edition of Eloquent JavaScript.

* Gechev, M (2013).
  {link-gechev-2013}[_Functional Programming with JavaScript_].
  — A practical introduction to functional programming techniques in JavaScript.

* Oxley, T (n.d.).
  {link-oxley-functional-js-workshop}[_Functional JavaScript Workshop_].
  GitHub.
  — A Node-based workshop for learning functional programming.

* Rinaldi, B (n.d.).
  {link-rinaldi-frp-js}[_Functional Reactive Programming in JavaScript_].
  — Implementing FRP with libraries such as Bacon.js and RxJS.

* Iffland, D (2016).
  {link-iffland-2016}[_Virtual Panel: State of Reactive in JavaScript and Elm_].
  InfoQ.
  — A panel discussion on the reactive landscape in JavaScript and Elm.

* Podwysocki, M (2010).
  {link-podwysocki-2010}[_Introduction to the Reactive Extensions to JavaScript (RxJS)_].
  — An early introduction to RxJS.

* Osmani, A (2012).
  {link-osmani-2012}[_How to Write Fast, Memory-Efficient JavaScript_].
  Smashing Magazine.
  — Techniques for writing performant, memory-efficient JavaScript.

* Osmani, A (n.d.).
  {link-osmani-startup-perf}[_JavaScript Start-Up Performance_].
  Medium.
  — On parsing and compilation bottlenecks that affect web application start-up.

* Baker, G and Arvidsson, E (n.d.).
  {link-baker-arvidsson-optimizing-js}[_Optimizing JavaScript Code_].
  Google PageSpeed Insights.
  — Performance guidance from engineers on GMail and Chrome.

* Kikobeats (n.d.).
  {link-mythbusters-js}[_MythBusters JS_].
  — A JavaScript performance & readability handbook covering Array, Date,
  Number, Function, RegExp, Object, V8, and Workflow optimization tips; see
  the {link-mythbusters-js-repo}[source repository].

* Husain, J (n.d.).
  {link-husain-async-programming}[_Asynchronous Programming: The End of The Loop_].
  egghead.
  — A free video course on asynchronous programming in JavaScript.

* Severien, T (n.d.).
  {link-severien-readable-code}[_The Importance of Writing Code That Humans Can Read_].
  SitePoint.
  — On writing human-readable code, with JavaScript examples.

* Ronacher, A (2022).
  {link-ronacher-2022}[_Dependency Risk and Funding_].
  — On the risks of third-party dependencies and the sustainability of the
  open-source ecosystem behind them.

* The Pragmatic Engineer (2024).
  {link-pragmatic-engineer-bluesky-2024}[_Inside Bluesky's Engineering Culture_].
  — On Bluesky's choice of TypeScript for its backend, web, and mobile
  clients alike; the source for <<One language across the stack>>.