= TS-62: Make
:toc: macro
:toc-title: Contents

:link-gnu-make: https://www.gnu.org/software/make/

This technical standard covers best practices for writing `Makefile`s, using
{link-gnu-make}[GNU Make] as the reference implementation.

Makefiles are commonly used as a language-agnostic task runner – a thin, discoverable interface over project scripts,
builds, and other repeated commands.

It is RECOMMENDED that all code repositories that include scripts and run commands for automating development and
operations processes include a Makefile to encapsulate all the available scripts centrally.

See also:

* xref:031.adoc[*TS-31: Unix shells and POSIX standards*] and xref:032.adoc[*TS-32: Bash*] for guidance on the shell
  scripts and recipes invoked from within Makefile targets.

* xref:016.adoc[*TS-16: Command line interfaces (CLIs)*] for general guidance on designing CLIs.

* xref:058.adoc[*TS-58: Docker*] for guidance on the container build and run commands that Makefile targets often wrap.

toc::[]

include::partial$062/01-self-documenting-makefiles.adoc[leveloffset=+1]
include::partial$062/02-passing-arguments-to-recipes.adoc[leveloffset=+1]

''''

include::partial$062/99-references.adoc[leveloffset=+1]
