= TS-63: URL Design
:toc: macro
:toc-title: Contents

A URL is an address that identifies a resource on the web. Well-designed URLs
are readable, predictable, durable, and shareable. They are part of the user
interface, because they appear in browser address bars, links, bookmarks,
printed material, and API client code. Poor URL design degrades usability,
maintainability, and search ranking.

This technical standard covers the design of URLs for all kinds of HTTP
services, including websites, web applications, and HTTP APIs. It is concerned
with the structure and semantics of URLs themselves, not with the resources
they identify or the protocols used to transfer them.

For general user interface design principles, see
*xref:015-user-interfaces.adoc[TS-15: User Interfaces]*. For web GUI implementation,
see *xref:018-web-guis.adoc[TS-18: Web GUIs]*. For search engine optimization,
see *xref:019-search-engine-optimization-seo.adoc[TS-19: Search Engine Optimization (SEO)]*. For
HTTP API resource modeling and versioning, see
*xref:021-http-apis.adoc[TS-21: HTTP APIs]*.

toc::[]

include::partial$063/01-anatomy-of-a-url.adoc[leveloffset=+1]
include::partial$063/02-path-design.adoc[leveloffset=+1]
include::partial$063/03-query-strings.adoc[leveloffset=+1]
include::partial$063/04-fragments.adoc[leveloffset=+1]
include::partial$063/05-permanence.adoc[leveloffset=+1]

''''

== References

* https://www.w3.org/Provider/Style/URI[Cool URIs don't change — Tim Berners-Lee]:
  The seminal essay on URL permanence, written by the inventor of the world-wide web.

* https://blog.jim-nielsen.com/2023/examples-of-great-urls/[Examples of Great URLs — Jim Nielsen]:
  A collection of real-world URLs that illustrate good design, with commentary.

* https://www.rfc-editor.org/rfc/rfc3986[RFC 3986 — Uniform Resource Identifier (URI): Generic Syntax]:
  The IETF specification that defines the syntax of URLs.

* https://url.spec.whatwg.org/[URL Standard — WHATWG]:
  The living standard that defines parsing, serialization, and conformance for
  URLs as implemented by web browsers.

* https://developers.google.com/search/docs/crawling-indexing/url-structure[URL structure — Google Search Central]:
  Guidance on URL design from the perspective of search engine optimization.
