= TS-63: URL design
:toc: macro
:toc-title: Contents

A URL is an address that identifies a resource on the web. Well-designed URLs are readable, predictable, durable, and
shareable. They are part of the user interface, because they appear in browser address bars, links, bookmarks, printed
material, and API client code. Poor URL design degrades usability, maintainability, and search ranking.

This technical standard covers the design of URLs for all kinds of HTTP services, including websites, web applications,
and HTTP APIs. It is concerned with the structure and semantics of URLs themselves, not with the resources they identify
or the protocols used to transfer them.

For general user interface design principles, see xref:015.adoc[*TS-15: User interfaces*]. For web GUI implementation,
see xref:018.adoc[*TS-18: Web GUIs*]. For search engine optimization, see
xref:019.adoc[*TS-19: Search engine optimization (SEO)*]. For HTTP API resource modeling and versioning, see
xref:021.adoc[*TS-21: HTTP APIs*].

toc::[]

include::partial$063/01-anatomy-of-a-url.adoc[leveloffset=+1]
include::partial$063/02-path-design.adoc[leveloffset=+1]
include::partial$063/03-query-strings.adoc[leveloffset=+1]
include::partial$063/04-fragments.adoc[leveloffset=+1]
include::partial$063/05-permanence.adoc[leveloffset=+1]

''''

include::partial$063/99-references.adoc[leveloffset=+1]
