= TS-63: URL design
:toc: macro
:toc-title: Contents

:link-berners-lee-cool-uris: https://www.w3.org/Provider/Style/URI
:link-nielsen-2023: https://blog.jim-nielsen.com/2023/examples-of-great-urls/
:link-rfc3986: https://www.rfc-editor.org/rfc/rfc3986
:link-whatwg-url-standard: https://url.spec.whatwg.org/
:link-google-url-structure: https://developers.google.com/search/docs/crawling-indexing/url-structure

A URL is an address that identifies a resource on the web. Well-designed URLs are readable, predictable, durable, and
shareable. They are part of the user interface, because they appear in browser address bars, links, bookmarks, printed
material, and API client code. Poor URL design degrades usability, maintainability, and search ranking.

This technical standard covers the design of URLs for all kinds of HTTP services, including websites, web applications,
and HTTP APIs. It is concerned with the structure and semantics of URLs themselves, not with the resources they identify
or the protocols used to transfer them.

For general user interface design principles, see xref:015.adoc[*TS-15: User interfaces*]. For web GUI implementation,
see xref:018.adoc[*TS-18: Web GUIs*]. For search engine optimization, see
xref:019.adoc[*TS-19: Search engine optimization (SEO)*]. For HTTP API resource modeling and versioning, see
xref:021.adoc[*TS-21: HTTP APIs*].

toc::[]

include::partial$063/01-anatomy-of-a-url.adoc[leveloffset=+1]
include::partial$063/02-path-design.adoc[leveloffset=+1]
include::partial$063/03-query-strings.adoc[leveloffset=+1]
include::partial$063/04-fragments.adoc[leveloffset=+1]
include::partial$063/05-permanence.adoc[leveloffset=+1]

''''

== References

* Berners-Lee, T.
  {link-berners-lee-cool-uris}[_Cool URIs Don't Change_].
  — The seminal essay on URL permanence, written by the inventor of the world-wide web.

* Nielsen, J (2023).
  {link-nielsen-2023}[_Examples of Great URLs_].
  — A collection of real-world URLs that illustrate good design, with commentary.

* IETF.
  {link-rfc3986}[_RFC 3986: Uniform Resource Identifier (URI): Generic Syntax_].
  — The IETF specification that defines the syntax of URLs.

* WHATWG.
  {link-whatwg-url-standard}[_URL Standard_].
  — The living standard that defines parsing, serialization, and conformance for URLs as implemented by web
  browsers.

* Google Search Central.
  {link-google-url-structure}[_URL Structure_].
  — Guidance on URL design from the perspective of search engine optimization.
