= General best practices

Threat modeling works best when it is iterative, baked into the regular
development process, rather than a one-time activity.

Threat modeling workshops SHOULD begin during the design phase of a new software
product. Thereafter, the threat assessments SHOULD be treated as living
documents that are regularly revised as the system evolves, new threats emerge,
or business requirements change.

Threat modeling workshops SHOULD NOT be postponed until the product/system is
nearly ready to ship to production. With iterative threat assessment you will
catch potential vulnerabilities earlier in the development cycle, when they will
be cheaper to remediate. Because security and privacy requirements are
cross-cutting architectural concerns, they tend to be expensive to retrofit into
an established architecture.

It is RECOMMENDED to schedule threat modeling workshops at the breakpoint
between each iterative development/release cycle. Threat modeling workshops
should be organized and facilitated by a security champion within each team.

Effective threat modeling benefits from a multi-disciplinary approach.
Participants in threat modeling workshops should be drawn from architecture and
security, product and business, and development, testing, and operations. The
purpose is to view the system from diverse perspectives.

Various types of models SHOULD be used as input to threat modeling workshops.
Different representations of a system will reveal different categories of
potential attack vectors. RECOMMENDED models include:

* Infrastructure.
* Data (in situ and in transit).
* Services and components.
* Component boundaries and interfaces.
* Business processes (or application logic).
* External dependencies.

See also the https://www.threatmodelingmanifesto.org/[Threat Modeling Manifesto]
for more information about the principles of threat modeling.
