= Acceptance criteria

Requirements SHOULD be written as *acceptance criteria (ACs)*.

Acceptance criteria — which are also known as *conditions of satisfaction* — are the set of conditions a software system
must satisfy to be accepted by the customer.

Acceptance criteria SHOULD be written from the perspective of the end users. They SHOULD specify user needs and wants,
and SHOULD NOT prescribe solutions. This means ACs SHOULD NOT include technical implementation details, or even make
reference to software, as much as reasonably practical.

Acceptance criteria MUST NOT be presented as a list of instructions for things the business would like implemented in
software. The place for this is a product requirements document.

Acceptance criteria SHOULD be written in a consistent style and set of conventions, and MUST be written in the language
of the business domain. Critically, acceptance criteria MUST be understandable to business stakeholders.

Acceptance criteria MUST cover both functional (behavior) and non-functional (quality) requirements. What the software
does (specified via functional requirements), combined with the constraints within which it must operate (specified via
non-functional requirements), is the whole of what the system is obliged to deliver. A solution is said to be
*functionally complete* if it meets both its functional and non-functional acceptance criteria.
