== Identifiers

Except for small-scale systems, every requirement MUST have a unique, unambiguous, durable identifier. This allows for
each requirement to be referenced consistently from proposals, tickets, tests, and code.

This technical standard RECOMMENDS the following identifier scheme for software requirements. The first part of the
identifier is a single letter that maps to a requirements category.

* *F* = Features
* *R* = Rules
* *A* = Access
* *I* = Interfaces
* *J* = Journeys
* *Q* = Qualities

The second part of the identifier is a incrementing whole number: `1`, `2`, `3` ... `10`, `11`, `12` ...

Where a single requirement holds several independently-verifiable scenarios, each scenarios is given a point number:
`.1`, `.2`, `.3` ... `.10`, `.11`, `.12` ...

.Examples
----
F3          One discrete feature, eg. "reserve a product".
F3.2        The second scenario defined within this requirement.

R5          A single business rule.
R5.3        A variation or example.

Q1          On discrete quality attribute, eg. "latency".
Q1.4        The fourth stated latency threshold.
----

Identifiers, once assigned, are permanent. So, once assigned, an identifier MUST NOT be reused for a different
requirement, even after the original is deprecated and removed. Gaps in a sequence represent requirements that once
existed but are no longer part of the current system specification.

As a rule of thumb, each unique identifier SHOULD represent a requirement that can be verified by a single discrete
test. For example, in quality requirements each stated threshold should have a unique identifier of its own. Even
a single quality such as latency may state different budgets for different operations and load conditions, and each
is a separate pass or fail — and therefore each should have its own unique identifier.

Identifiers are more stable than the requirements they reference. Requirements may be recategorized, renamed, reworded —
but their identifier will remain stable throughout.

Throughout a specification, related requirements SHOULD cross-reference each other using their identifiers. For example,
interfaces and journeys should cross-reference the features they expose, and vice versa.
