= Responsibility

The requirements are derived from the business domain and SHOULD be written in a way that is understandable to the business stakeholders.

Nevertheless, there are some blurry edges between the high-level business requirements and the low-level technical design choices. For example, a business requirement might be that "passwords must be strong". But this requirement necessitates some technical design choices that the business stakeholders might like to know about. For example, it might be of interest to the business stakeholders what validation algorithms the developers choose to implement to guarantee strong passwords. Although it is not the responsibility of the business stakeholders to specify the password validation algorithm, they might like to understand the high-level rules of the algorithm, such as:

* Minimum 8 characters.
* Mix of letters (any case) and numbers.
* At least one special character, eg. %^&*().
* No dictionary words.

For these reasons, requirements specifications SHOULD be written and maintained in collaboration between the customers (or a representative such as product owner) and the software development team.
