= Acceptance criteria

Most requirements specifications SHOULD be written as acceptance criteria. Acceptance criteria – also known as *conditions of satisfaction* – are a set of conditions that a software system must satisfy to be accepted by the customer. They are written in a way that is understandable to the business stakeholders, and are used to define the scope of the software system.

The acceptance criteria SHOULD be written from the perspective of the end users of the software. They should define user needs and wants, but not prescribe specific solutions. This means that acceptance criteria SHOULD NOT include technical implementation details. Indeed, ACs SHOULD NOT even make reference to software.

Acceptance criteria SHOULD be written in a consistent style, using a consistent set of conventions. They MUST be written in a language that is derived from the business domain, and is therefore understood by the business stakeholders.

Acceptance criteria SHOULD capture _requirements_, not convey _instructions_ for things that the business wants implemented in software. A nice analogy is to think of software development teams as like teams of doctors rather than, say, waiting staff in a restaurant. The role of a waiter is to try to give customers exactly what they ask for. The role of a doctor is to discover and learn about an underlying problem, and then prescribe a solution.

This is a critically important distinction. Sometimes, the work of a software development team involves having difficult conversations and giving bad news to the customer, or to other stakeholders in a project. For example, it might be necessary to tell a customer that the requested changes cannot be made within the allocated time and budget constraints. Success in delivery of software projects depends on software development teams being able to represent their rationale viewpoint, so the customer can make better, informed decisions.

Acceptance criteria MUST cover both the functional and non-functional (performance) requirements. The combination of software operations and functionality (specified via the functional requirements) and the constraints within which the software is expected to perform (specified via the non-functional requirements) make up the "features" of a system.

A solution is said to be "correct" if it meets both its functional and performance acceptance criteria. See also *link:../013/README.adoc[TS-13: Functional Testing]*, which covers best practices for the verification of a software system against its functional requirements, and *link:../014/README.adoc[TS-14: Performance Testing]*, which covers best practices for verifying that software meets its performance requirements.

Requirements SHOULD be specified using consistent acceptance criteria definition conventions. These conventions differ slightly between functional and non-functional requirements.
