= Definition of Ready

It is RECOMMENDED that software projects have a *Definition of Ready (DoR)*. This is a documentation artifact used in software development to define a set of criteria that must be met before a new feature, user story, or other development task is considered "ready" to be worked on.

The DoR SHOULD be formatted as a simple, short checklist. The purpose is to provide a quick point of reference for teams to check they've got everything they need to successfully complete a development task, before proceeding with it. The checklist SHOULD be generic enough to be applicable to all kinds of development tasks, and emphasis SHOULD be placed on the readiness of the requirements.

Example:

* Are the requirements clear and (sufficiently) unambiguous?
* Are the acceptance criteria defined in a testable format, and can the tests be automated?
* Is it clear who the stakeholders are?
* Does the team have the knowledge and resources required to complete the task?
* Can the work be done independently of other tasks running in parallel?
* Can the work be implemented in small increments?
* Can the design be iterated based on feedback?
