= Naming

When naming CLI commands, subcommands, and options, follow these guidelines:

* Make the name memorable and easy to type.
* Keep it short, but not too generic – to avoid conflicts.
* Reserve the shortest, most generic names for standard tools.
* Avoid superfluous words such as "tool", "util", and "kit".
* Don't name commands after any standard, protocol, or file format, such as "openssl" or "ffmpeg".

Follow the naming conventions of the target runtime system. For Unix-based systems, the convention is to use only lower case ASCII letters and delimit words with single dashes. The user SHOULD NOT need to press their `Shift` key to type your commands: `VirtualBox` and `easy_install` break this rule. Numbers MAY be included but they SHOULD NOT be the first character of a command name.

Don't pollute the global namespace with dozens of commands. If your package consists of a suite of utilities, consider implementing them as subcommands of a single program namespace. Git does this brilliantly: `git [subcmd]`.

Subcommands can be generic words like "update" and "status". But globally-scoped program names MUST NOT be – to avoid conflicts with other programs. Both ImageMagick and Windows used the command `convert` — oops!

The very shortest, most generic names should be reserved for standard system tools, or things people use all the time like `cd` and `ls`. The more niche the command, the longer its name should be.

****
`curl` is an example of a really great CLI command name. It's a verb, it is short and memorable and easy to type, it is pronounced similarly all over the world, and when you spell it out in English it sounds like "see URL".
****
