= TS-10: Releasing
:toc: macro
:toc-title: Contents

This technical standard covers best practices for releasing software updates. The focus of these guidelines is on release strategies that minimize the risk of bugs, regressions, and incidents occurring in production.

These guidelines are applicable to both software-as-a-product, which tends to be intermittently released, and software-as-a-service, which tends to be more continuously released.

This technical standard is concerned with production releases, rather than deployments to other environments such as test and staging environments.

See also link:../009/README.adoc[TS-9: Version Control] for the branching, integration, and release-trunk/release-branch mechanics that underpin these release strategies, and link:../011/README.adoc[TS-11: Versioning] for version numbering.

toc::[]

include::./01-release-cadence.adoc[leveloffset=+1]
include::./02-release-strategies.adoc[leveloffset=+1]
include::./03-release-approval-and-governance.adoc[leveloffset=+1]
include::./04-rollback.adoc[leveloffset=+1]
include::./05-change-freezes.adoc[leveloffset=+1]
include::./06-release-documentation.adoc[leveloffset=+1]
include::./07-related-links.adoc[leveloffset=+1]
