= Privacy by design

Applications MUST be designed with privacy and data protection embedded as core
design principles. This is known as *privacy by design* or *privacy by default*.
This concept emerged in the 1970s and it means, simply, "data protection through
technology design". It means that data processing procedures and data protection
controls are considered at the design stage of an IT system, or at the design
stage of any subsequent change made to that system, rather than these concerns
being treated as separate features that are added on later.

The principle of privacy by design has since been added to data protection
legislation such as the European Union's General Data Protection Regulation
(GDPR). GDPR explicitly requires that technical and organizational measures for
protecting data be _proactively_ designed into business processes and systems,
and that businesses anticipate and put in place prevention mechanisms for
privacy breaches before they happen.

The principles of privacy by design can be summarized by the following seven
statements:footnote:[Taken from the Information and Privacy Commissioner of
Ontario, Canada:
https://www.ipc.on.ca/en/resources-and-decisions/privacy-design]

1. Be proactive about privacy, not reactive. Anticipate and prevent privacy
breaches before they happen.

2. Build maximum privacy in to default settings. Users may explicitly opt-in to
reduce privacy settings, but maximum privacy safeguards must be the default.
Thus, if users do nothing, they are protected.

3. Embed privacy into the design of IT systems and business processes. Privacy
should be integral to a system, not an add-on.

4. Privacy may need to be balanced against other legitimate interests and
objectives, but the goal is to achieve a positive-sum (not zero-sum) outcome, in
which privacy is not traded off against other objectives.

5. End-to-end security: embed strong encryption and other security measures to
the complete lifecycle of data.

6. Be open and transparent about your privacy policies and standards. Inform
users about how their data is processed and stored. Allow for independent
verification of your privacy practices.

7. Give users control over their data, and make it easy for them to manage their
privacy settings.
