= Code style

== Indentation

Each time a new block or block-like construct is opened, the code MUST be indented by an additional *two spaces*. When the block ends, the indentation returns to the previous level.

Tab characters MUST NOT be used for indentation. Code editors SHOULD be configured to automatically replace tab characters with spaces.

Comments and Javadoc comments MUST be indented to the same level as the code to which they relate.

== One statement per line

There MUST be no more than one statement per line.

== Line length (column limits)

Lines SHOULD be no longer than 80 characters, including the whitespace used for indentation, and SHOULD NOT exceed 120 characters. A line longer than 120 characters SHOULD be line-wrapped (see <<line-wrapping,Line-wrapping>>).

Package and import statements MAY exceed the column limits. They MUST NOT be line-wrapped.

Other code MAY exceed the column limits, but only where line-wrapping it would reduce its readability (eg. command lines written in comments) or where keeping within the limits is simply not possible (eg. long URLs in comments).

[#line-wrapping]
== Line-wrapping

The term *line-wrapping* refers to the practice of breaking a single statement across multiple lines. This is typically done to keep line lengths short, but authors MAY use line-wrapping at their discretion to improve the readability of code, even where the code does not exceed the column limits.

There are no deterministic rules for line-wrapping in Java, but the following guidelines SHOULD be followed.

* Look to refactor the code before line-wrapping is implemented. Can long statements be broken into multiple shorter ones? Can some of the code be extracted into methods?

* Otherwise, prefer to break at a higher syntactic level rather than on lower-level breaks. Examples:

** Break _before_ non-assignment operators, as well as operator-like symbols such as the dot separator (`.`) and double colons for method references (`::`).

** Break _after_ assignment operators.

** Break _after_ the arrow in a lambda expression, if the lambda body is a single un-braced statement.

Commas SHOULD stay attached to the token that precedes them. A method or constructor name SHOULD stay attached to the opening parenthesis that follows it.

[source,java]
----
MyLambda<String, Long, Object> lambda =
    (String label, Long value, Object obj) -> {
      // …
    };

Predicate<String> predicate = str ->
    longExpressionInvolving(str);
----

Continuation lines SHOULD be indented by an additional *four spaces* — double the normal indentation level, so that they stand out from the nested block that follows.

== Brace style

In Java code, the most common formatting options for braces are the following.

* Kernighan and Ritchie (K&R) style, also known as Egyptian brackets.
* Allman style.
* GNU style.

In the K&R style, the opening brace is placed at the end of the line that begins the compound statement, and the closing brace is placed on a line of its own at the same indentation level as that opening statement.

.K&R style
[source,java]
----
class Example {
  public void method() {
    if (condition) {
      // …
    } else {
      // …
    }
  }
}
----

The Allman style differs from K&R by moving the opening brace to a new line, aligned with the start of the compound statement. This style emphasizes vertical alignment and increases the use of whitespace, arguably improving readability.

.Allman style
[source,java]
----
class Example
{
  public void method()
  {
    if (condition)
    {
      // …
    }
    else
    {
      // …
    }
  }
}
----

The GNU style is similar to the Allman style, but each brace is indented halfway between the statement that opens the block and the code inside it.

.GNU style
[source,java]
----
class Example
  {
    public void method()
      {
        if (condition)
          {
            // …
          }
        else
          {
            // …
          }
      }
  }
----

Of these three, the K&R style is the most widely used, and the most widely recommended in Java coding style guides. For consistency with the prevailing industry standard, the K&R convention MUST be used to format braces. The following rules apply.

* No line break before the opening brace, in most cases. The opening brace is placed at the end of the line that begins the block-like construct.

* A line break after the opening brace.

* A line break before the closing brace.

* A line break after the closing brace, but only if that brace terminates a statement or the body of a method, constructor, or _named_ class. Thus, `else`, `catch`, `finally`, and `while` keywords go immediately after the closing brace of the preceding block, because these represent a continuation of the preceding block statement.

Authors MAY deviate from the K&R style where doing so improves readability. For example, opening braces MAY be placed on a new line after very long statements, or where blocks are used only to limit the scope of local variables.

Where a closing brace is followed by a comma, semicolon, or other punctuation, that punctuation is placed on the same line as the closing brace.

.Examples from the Google Java Style Guide
[source,java]
----
return () -> {
  while (condition()) {
    method();
  }
};

return new MyClass() {
  @Override
  public void method() {
    if (condition()) {
      try {
        something();
      } catch (ProblemException e) {
        recover();
      }
    } else if (otherCondition()) {
      somethingElse();
    } else {
      lastThing();
    }

    {
      int x = foo();
      frob(x);
    }
  }
};
----

Braces MUST be used with `if`, `else`, `for`, `do`, and `while` statements, even when the body of the statement is empty or contains only a single statement.

For empty block-like constructs, the block SHOULD be written as `{}` on the same line as the statement that opens the block.

[source,java]
----
void doNothing() {}
----

This style MAY also be used for empty blocks within multi-block statements. (This is a relaxation of the Google Java Style Guide, which forbids this.)

[source,java]
----
try {
  emptyStack.pop();
  fail();
} catch (NoSuchElementException expected) {}
----

Be wary of stray `;` turning conditionals into empty statements. In the following example, the trailing `;` on line 1 makes the `if` statement empty (it doesn't do anything), and the block from lines 2 to 4 always runs. The K&R brace style makes this mistake less likely, because the line ends with `{` rather than `)`. For better guards, enable compiler warnings or linter rules that flag empty statements.

[source,java]
----
if (isValid(input));
{
  process(input);
}
----

[#vertical-whitespace]
== Vertical whitespace

A single blank line MUST separate consecutive members and initializers of a class-like construct: fields, constructors, methods, nested classes, static initializers, and instance initializers.

The one exception is fields. Logical groupings of fields MAY be created by omitting the blank lines between two or more consecutive fields.

Single blank lines MAY be added wherever doing so improves the readability of the code (eg. using vertical whitespace to separate logical sections of a method) or makes the code's structure clearer (eg. organizing fields into logical groupings).

Multiple consecutive blank lines SHOULD NOT be included in any Java code.

== Horizontal whitespace

Besides what is required by the Java language, a single ASCII space character SHOULD appear in the following scenarios.

* To separate reserved words such as `if`, `for`, and `catch` from the opening parenthesis that follows them on the same line.

* To separate reserved words such as `else` and `catch` from the closing curly brace that precedes them on the same line.

* Before most opening curly braces, with a couple of exceptions: `@SomeAnnotation({a, b})`, and `String[][] x = {{"foo"}};`.

* Between the type and variable of a declaration: `List<String> list`.

* After `,`, `;`, and `:`.

* After the closing parenthesis of a cast.

* On both sides of binary and ternary operators.

* Around the following operator-like symbols.

** The ampersand in a conjunctive type bound: `<T extends Foo & Bar>`.

** The pipe for a catch block that handles multiple exceptions: `catch (FooException | BarException e)`.

** The colon (`:`) in an enhanced `for` statement.

** The arrow in a lambda expression: `(String str) -> str.length()`.

* Before and after a double slash (`//`) that begins an end-of-line comment, and between the double slash and commented-out code that follows.

A space MAY be included inside the curly braces of an array initializer. Both `new int[] {1, 2, 3}` and `new int[] { 1, 2, 3 }` are valid.

Authors MAY include additional spaces before end-of-line comments to achieve vertical alignment.

[source,java]
----
System.out.println(sorted);   // [15, 23, 51, 80]
System.out.println(unsorted); // [80, 51, 23, 15]
----

Horizontal alignment of related tokens on multiple consecutive lines MAY be applied where doing so improves readability. But use this cautiously. The trade-off is noisy diffs, because a single line change can trip realignment of tokens across multiple other lines.

There MUST NOT be any superfluous whitespace at the end of lines. It is strongly RECOMMENDED to configure both code editors and automation pipelines to remove trailing whitespace automatically.

== Grouping parentheses

Optional grouping parentheses SHOULD be kept unless the expression cannot reasonably be misread without them. Don't assume readers have Java's operator precedence memorized.
