= Implementation comments

Java supports three comment notations.

* `//`
* `/* … */`
* `/** … */`

Java's single-line (`//`) and multi-line (`/* … \*/`) comment syntax MUST be used only for _implementation_ comments, while Javadoc comments (`/** … */`) MUST be used only for parseable API documentation.

The single-line implementation comment syntax MUST be used in only two cases.

* To temporarily comment-out blocks of code. Block-level `//` comments SHOULD be removed from code running in production.

* For short end-of-line comments that decode or explain a value assigned, returned, or printed by the statement. EOL `//` comments MAY exist in production code.

Java's multi-line implementation comment syntax, `/* … \*/`, SHOULD be used for both single-line and multi-line implementation comments. For short comments that can fit between the indentation level and the soft line limit, the opening `/*` and closing `\*/` SHOULD be written on the same line as the comment. But as soon as the comment text needs to be wrapped to two or more lines, the opening `/*` and the closing `*/` SHOULD be bumped to their own lines, with the text lines sandwiched between them.

Where the multi-line comment syntax `/* … \*/` is used to encapsulate a single-line comment, there MUST be exactly one space after the opening `/*` and another before the closing `*/`. The single-line comment syntax `//` also MUST be followed by exactly one space and then the code or comment.

Block-level comments MUST be indented to the same level as the code to which they relate. Comments MUST NOT be enclosed in boxes drawn with asterisks or other characters.

Multi-line block-level comments SHOULD have an empty line both before and after the comment block. Single-line block-level comments SHOULD have an empty line before them, and MAY have a blank line after.

All text within `/* … */` comments MUST be written in full sentences, each starting with a capitalized word and terminated by a period (full stop). Optionally, empty lines MAY be written within the text of block-level comments, to break it up into paragraphs. This is particularly beneficial for the readability of very long comments.

.Examples of implementation comments
[source,java]
----
int num1 = 7;
int num2 = 5;
// int num0 = 0;

/*
Modulus operator (%) returns the remainder after the first operand
is evenly divided by the second operand. In this case, 7 / 5 = 1,
with a remainder of 2.
*/

int modulus = num1 % num2;
System.out.println(modulus); // 2

/* 7 divides evenly into 3 twice (3x2=6) with a reminder of 1 (7-6=1). */
System.out.println(7 % 3); // 2

/*
The modulus operator is often used to determine whether a number is
even or odd. If x % 2 is 0, then x is even, otherwise it is odd.
*/

System.out.println(6 % 2); // 0
System.out.println(7 % 2); // 1
----

Implementation comments SHOULD communicate only information that is not readily available from the code itself, but which is relevant to the understanding of that code. For example, implementation comments SHOULD be used to document the reasons behind a particular choice of design pattern that, without context, may seem unusual or even counterintuitive to some developers who are looking at the code for the first time. See xref:007.adoc[TS-7] for further general guidance on code-level implementation comments.
