= Java API specifications

This section covers best practices for using particular Java APIs.

== Jakarta Persistence (JPA)

Jakarta Persistence, formerly known as the Java Persistence API (JPA), is a specification for object-relational mapping (ORM) in Java applications. It defines a set of interfaces and annotations for managing relational data, allowing developers to interact with databases using abstractions in the form of Java classes and objects, rather than raw SQL queries.

JPA interfaces provide interoperability between ORM libraries that are compliant with the JPA specification, such as Hibernate and EclipseLink. This makes it easier to swap out data persistence implementations without changing — or at least while minimizing the changes required in — the application code.

JPA uses JPQL (Jakarta Persistence Query Language) to query data from relational databases. JPQL is similar to SQL, but it operates on the Java entity objects rather than directly on database tables.

.Example JPA entity class
[source,java]
----
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class User {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  private String name;
  private String email;

  // …
}
----

.Basic Spring Data JPA repository interface
[source,java]
----
import org.springframework.data.jpa.repository.JpaRepository;

public interface UserRepository extends JpaRepository<User, Long> {
  // …
}
----

JPA is widely used in enterprise applications and is a key part of the Jakarta EE ecosystem. It is therefore RECOMMENDED to use JPA in Java applications that implement simple interactions with relational databases.

For more complex interactions, such as queries that involve deep joins, or otherwise where performance optimization is a key design constraint, it may be more appropriate to use a lower-level abstraction, or no abstraction at all.
