= References

* Android Open Source Project. {link-aosp-code-style}[_Java Code Style for Contributors_].

* Google. {link-google-javaguide}[_Google Java Style Guide_].

* Marks, S (2018). {link-lvti-style-guide}[_Local Variable Type Inference: Style Guidelines_].

* OpenJDK. {link-jep-467}[_JEP 467: Markdown Documentation Comments_].

* OpenJDK. {link-jep-511}[_JEP 511: Module Import Declarations_].

* OpenJDK. {link-jep-512}[_JEP 512: Compact Source Files and Instance Main Methods_].

* Oracle. {link-oracle-code-conventions}[_Code Conventions for the Java Programming Language_].

* Oracle. {link-oracle-code-conventions-comments}[_Code Conventions for the Java Programming Language: Comments_].

* Oracle. {link-oracle-doc-comments}[_How to Write Doc Comments for the Javadoc Tool_].

* Oracle (2023). {link-executorservice-21}[_Interface ExecutorService, Java SE 21 API Specification_].

* Oracle (2023). {link-jls-21}[_The Java Language Specification, Java SE 21 Edition_].

* Oracle. {link-oracle-java-tutorials}[_The Java Tutorials_].

* QOS.ch. {link-slf4j-manual}[_SLF4J User Manual_].

* Twitter. {link-twitter-java-style-guide}[_Java Style Guide_].
