= References

* https://www.standardwebhooks.com/[Standard Webhooks] is an initiative to
document common conventions for message delivery. The guidelines target webhooks
– ie. event-oriented messages transmitted over the public internet between
organizations – though there are many good ideas here that are applicable to
internal communication design, too. Standard Webhooks is a catalog of the most
common patterns seen in the webhook implementations of major public web
services, and it specifies a standard based on those patterns and emerging best
practices. It captures conventions for event naming, payload structure, security
(signatures), and delivery patterns.

* https://cloudevents.io/[CloudEvents] is an effort by the
https://github.com/cncf[Cloud Native Computing Foundation] to standardize event
schemas. It's focus is on improving interoperability across different cloud
providers and platforms. It does this by specifying a generic specification for
event data and metadata that can be mapped to a wide variety of messaging and
transport protocols and message encoding formats. It's more opinionated than
Standard Webhooks, and its focused exclusively on message schema. As a
protocol-agnostic standard, it does not cover topics such as security and
authentication.

* https://openid.net/wg/sharedsignals/[Shared Signals and Events (SSE)] is an
OpenID Foundation initiative that is developing standards and best practices for
the secure, privacy-protected transmission of messages and events over the
public internet.
