= TS-23: Messages and Events
:toc: macro
:toc-title: Contents

This technical standard covers best practices for designing and implementing
messages and events in message-driven architectures (MDA).

The focus of this standard is asynchronous communication between services within
a single organization's internal network ("intra-organization communication").
See also *link:../022/README.adoc[TS-22: Webhooks]*. Webhooks are a subset of
message-driven communication patterns, in which event-oriented messages are
exchanged via HTTP between systems owned and operated by different parties
("inter-organization communication"). Intra-organization and inter-organization
messages serve different purposes and have different sets of constraints, and
therefore their designs can look very different. Nevertheless, there is some
overlap between the two, and so some aspects of both technical standards will
inevitably cross over each other, too.

toc::[]

include::./01-message-systems.adoc[leveloffset=+1]
include::./02-http-apis.adoc[leveloffset=+1]
include::./03-delivery-and-reliability.adoc[leveloffset=+1]
include::./04-documentation.adoc[leveloffset=+1]
include::./05-references.adoc[leveloffset=+1]
