= HTTP APIs

Besides the specialist message systems described above, internal HTTP APIs are
also commonly used for communication within internal networks. While
conventional HTTP endpoints support synchronous polling, push notifications can
be implemented using webhooks (aka. HTTP callbacks), Server-Sent Events (SSE),
or WebSockets – allowing for true asynchronous message communication patterns.

Internal HTTP APIs can be a good choice for simple integrations, where fast
real-time responses are not critical, and otherwise where the overhead of
setting up and maintaining a specialist messaging framework is not justified.

Typically, do-it-yourself HTTP-based messaging systems use HTTPS for transport
and message semantics, and JSON for data interchange. But you have full freedom
to design your own HTTP message conventions. Industry conventions such as
https://www.standardwebhooks.com/[Standard Webhooks] and
https://cloudevents.io/[CloudEvents] can provide some useful guidance, though
for internal communication you have flexibility to design a proprietary system
that best fits your own requirements.

The remainder of this section covers RECOMMENDATIONS for the design and
implementation of internal HTTP APIs and internal webhooks. Aspects of
*xref:021.adoc[TS-21: HTTP APIs]* and
*xref:022.adoc[TS-22: Webhooks]* are also relevant here; this section
is extended guidance that is specific to HTTP messaging within
_internal networks_, rather than over the public internet.

== Secure protocol

Internal networks are _not_ inherently secure. Therefore HTTPS is REQUIRED to
encrypt messages in transit, to protect against eavesdropping and
man-in-the-middle attacks.

== Data interchange formats

It is RECOMMENDED to use JSON as the data interchange format for HTTP messages,
due to its widespread adoption, human readability, and compatibility with all
mainstream programming languages and platforms.

Other formats, such as XML or Protocol Buffers, may be used in specific
scenarios where their features are desired. But JSON SHOULD be the default go-to
choice for asynchronous communication between most services.

== Message schema

Designing a robust, flexible, scalable, and maintainable message schema is a
crucial aspect of the design of distributed systems with asynchronous
message-based communication patterns. The message schema defines the structure
of data exchanged between different components and services within a distributed
system.

Some message systems will impose their own opinions on message schema design,
but when using internal HTTP APIs you have full freedom to design your own
message schema.

Ideally, all asynchronous communication between nodes within a distributed
system should use a consistent, versioned JSON schema for all types of messages.
Ideally, synchronous service-to-service communication should also use the same
message schema, to maximize consistency across all communications.
Standardization on the high-level design of all messages across an entire system
reduces overall complexity, encourages code reuse via shared libraries, and
improves interoperability between services.

Therefore, it is RECOMMENDED to model all types of messages using a unified
schema. This means defining an extensible structure that can scale to represent
all kinds of messages.

=== Message types

Broadly, there are three categories of messages: events, commands, and queries.

* *Events* represent things that have happened in the service emitting the event
  (eg., `user.created`, `order.placed`).

* *Commands* represent requests for operations to be performed by other services
  (eg. `sendEmail`, `refundOrder`).

* *Queries* are requests for data (eg., `getUserDetails`, `listOrders`).

All three message types are closely related. The difference is mostly in the
statement of intent that underpins their semantics: whether the message is
telling another component to do something (a command), whether it is requesting
data (a query), or whether it is informing other components that something has
happened (an event).

Queries can be thought of a sub-type of commands. They differ from commands in
that they are read-only; they are not expected to change state, whereas commands
may do so.

Commands and queries will typically spawn one or more new events that inform
other components of the results of executing the command, or the results of the
query. Thus, a cascade of events may be triggered by a single initial command or
query.

In most cases, it will be expected that producers of queries will also be
consumers of subsequent events that return the requested data asynchronously.

All three types of message are used in message-driven architectures. A good
message schema will accommodate all three types of message in a consistent way.

=== Message body

There are two parts to a message schema: the message's main payload, and
metadata for the message container. These two parts SHOULD be clearly
differentiated in the schema.

The following high-level design achieves this separation by placing the payload
inside a `data` field, with other fields at the top-level of the data structure
capturing metadata.

[source,jsonc]
----
{
  "spec_version": "string",  // Message schema version number.

  // Metadata:
  "message_id": "string",    // Unique identifier for the message.
  "created_at": "string",    // Time of message creation, RFC 3339/ISO 8601 format
  "type": "string",          // One of: "event", "command", "query".
  "name": "string",          // Name of the event, command, or query.

  "data": {
    // Payload:
    "field1": <value>,       // Payload schema is specific to each
    "field2": <value>,       //   type of event, command, and query.
    "field3": <value>
  }
}
----

An alternative design would be to move the message metadata into the HTTP
headers, leaving just the payload in the message body. This approach has some
advantages, such as better separation of concerns and easier access to metadata
for routing and processing. However, the main disadvantage of this alternative
design is that the message payload becomes less portable. It is tied to the HTTP
protocol, making it harder to reuse the same message schema across different
transport protocols.

[TIP]
======
Messages SHOULD be designed to be transport-agnostic, to maximize their
reusability across different communication protocols. Therefore, it is
RECOMMENDED to include all message data within a single JSON object within the
HTTP message body, rather than relying on transport-specific features such as
HTTP headers.
======

It is RECOMMENDED that consumers implement validation of incoming messages
against a schema. The following JSON Schema can be used to validate messages
that conform to the high-level design shown above.

// TODO: Requires refinement, eg. datetime values.
[source,json]
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "spec_version": {
      "type": "string"
    },
    "message_id": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "patternProperties": {
        "[a-z][a-zA-Z0-9_.]*$": {
          "type": ["string", "number", "boolean", "object"]
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "spec_version",
    "message_id",
    "created_at",
    "type",
    "name",
    "data"
  ],
  "additionalProperties": true
}
----

=== Metadata

The metadata fields capture all the essential information needed to support the
tracking and processing of messages.

Besides the recommended fields shown in the example above, other metadata fields
MAY be included as needed, such as `source` and `correlation_id` (for tracing).
The metadata fields MUST be chosen carefully, to accommodate changing metadata
requirements over time.

=== Spec version

The `spec_version` field indicates the version of the message schema. Consumers
can use the `spec_version` field to differentiate their processing of messages
encoded to different schema versions.

Transitions to new schema versions SHOULD be done incrementally. This is done by
having producers emit duplicate messages in both the old and new schema versions
for a period of time, while consumers are migrated to the new schema. This
process allows breaking changes to be introduced to schema designs if required.
But better to evolve event schema in a non-breaking way wherever possible.

Message schema versioning SHOULD follow semantic versioning principles. See
*xref:011.adoc[TS-11: Versioning]*.

Message schema SHOULD evolve separately to the public API of the service
producing the events. Therefore message schema versioning SHOULD be independent
of API versioning. See also *xref:021.adoc[TS-21: HTTP APIs]*.

=== Message ID

The `message_id` value serves as an *idempotency key*, allowing consumers to
safely process duplicate messages. It SHOULD be a UUID. In turn, this supports
retries and other mechanisms that improve the reliability of message delivery.

=== Message type and name

The value of the `type` field indicates whether the message is an event,
command, or query. The value of the `name` field indicates the specific name of
the event, command, or query.

Events, commands, and queries MAY each have different naming conventions. For
example, events may use dot-noted event names like `user.created` and
`invoice.paid`, in which the first part identifies an entity type and the second
part identifies a type of mutation. Meanwhile, commands and queries may use
camelCase names like `sendEmail` and `getUserDetails`.

All the possible names of events, commands, and queries make up a catalog of
message types. The message catalog documents all the possible events, commands,
and queries that a system may communicate internally via messages.

Prefer to design a large catalog of granular message types. Each type of message
should align with a very specific use case. At the same time, don't fragment
unnecessarily, such that subscribers need to reconstruct discrete state changes
from multiple disparate messages.

=== Timestamp

The `created_at` field captures the time at which the message was created. The
timestamp SHOULD be in RFC 3339/ISO 8601 format, and in the UTC timezone – as
per *xref:047.adoc[TS-47: Dates and times]*.

This value MUST NOT change when messages are retried or redelivered. It captures
the original creation time of the message.

Including this field allows consumers to understand the timing of events,
commands, and queries. Since it is not possible to guarantee that messages are
delivered to consumers in the same order in which they were created, the
`created_at` timestamp allows consumers to make sure they don't process messages
out of order.

If it is important that consumers process messages, not only in the right order,
but also without skipping any messages in between, then additional mechanisms
are needed to enforce this. It is RECOMMENDED to include a `sequence` field in
the metadata, which captures an integer that increments by one for each new
message created in a sequence. This allows consumers to detect and handle any
gaps in the sequence of messages they receive.

Since messages may be dropped or delayed, for example due to network issues,
there are inherent limitations to the guarantees that can be made about message
ordering and delivery. See *Delivery and reliability*, below, for guidance on
managing this.

The `created_at` field can also be used by consumers to protect themselves from
replay attacks. See *Authentication and security*, below, for more information.

=== Payload

The `data` field contains the main payload of the message. The structure of the
payload is specific to each type of event, command, and query. Each message
`type`+`name` should have a well-defined payload schema.

Payloads MUST be composed from a global library of common data types and
structures, for maximum consistency and reusability. For example, if multiple
events include user information, then they SHOULD all use the same `User` data
structure.

The size of event payloads can impact delivery reliability and performance.
Therefore, try to keep payloads small – under 1MB – and focused on the essential
data needed by consumers. Consider opening new API endpoints from which event
consumers can fetch additional information about the events they receive, if
needed.

== Authentication

It is RECOMMENDED to use a message-level authentication system to verify the
authenticity and integrity of messages. The transport-level security provided by
HTTPS (TLS) is not sufficient on its own, since messages may be intercepted and
modified by malicious actors within the internal network.

The most common authentication pattern in message-based communication is HMAC
(Hash-based Message Authentication Code) with SHA-256 hashing – a symmetric key
algorithm. Other options include asymmetric signatures generated and verified by
public/private key pairs, and bearer token authentication (eg., JWT). Bearer
tokens can be a good choice where it is desirable to encode claims and scopes
(ie. permissions) in messages. Basic authentication is not recommended, since
its security depends entirely on end-to-end transport encryption (TLS/HTTPS).
More advanced options such as OAuth and mutual TLS are generally not appropriate
for internal message communication, due to their complexity and operational
overhead.

See *xref:022.adoc[TS-22: Webhooks]* for an overview of all the
options for authenticating HTTP messages, and the trade-offs of each approach.
The default option RECOMMENDED by this technical standard is HMAC signatures
with SHA-256 hashing. A scheme similar to that described in TS-22, and based on
https://www.standardwebhooks.com/[Standard Webhooks], is RECOMMENDED to protect
messages from tampering, reducing susceptibility to replay attacks and other
threats.

Signatures SHOULD be base64-encoded for compactness in transit.

[source,http]
----
POST /message HTTP/1.1
Host: 172.22.104.11
Content-Type: application/json
X-Message-ID: 550e8400-e29b-41d4-a716-446655440000
X-Message-DateTime: 2024-10-01T12:34:56Z
X-Message-Signature: sha256=a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3

{
  // ...
}
----

IP allow-listing MUST NOT be depended upon for authentication, but it MAY be
used in addition to authentication, to provide an extra layer of security. See
*xref:022.adoc[TS-22: Webhooks]* for more information.

// == Message distribution patterns

// TODO: See Digital Garden (fan-out, etc.)
