= Technical Standards

These technical standards are a set of general guidelines for software development that I have curated over time to support the creation of high-quality, high-value software products.

Technical standards define what "`good`" looks like from a technical perspective. The scope is broad, covering all aspects of the software development lifecycle: requirements specification, system design, coding conventions, testing strategies, deployment, and monitoring. But the focus of technical standards is on the desired end state, not the means of getting there. Methods and tools that help us to achieve our design goals – things like iterative and incremental development driven by feedback loops – are out-of-scope.

Technical standards are owned by the technical stakeholders in a software project. In an enterprise context, the act of including a technology in a technical standard signifies that it is approved for use in development, testing, and production. Organization-level standardization helps contain technical sprawl, particularly in large-scale distributed systems.

== Requirements levels

Throughout the technical standards documents, the capitalized keywords "REQUIRED", "MUST", "MUST NOT", "RECOMMENDED", "SHOULD", "SHOULD NOT", "OPTIONAL", and "MAY" are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[IETF RFC 2119].

== Index

* link:./001/[TS-1 *Requirements Specification*]
* link:./002/[TS-2 *Software Design Qualities*]
* link:./003/[TS-3 *Design Docs*]
* link:./004/[TS-4 *Modeling*]
* link:./005/[TS-5 *Application Architecture*]
* link:./006/[TS-6 *Distributed System Design*]
* link:./007/[TS-7 *Code Design*]
* link:./008/[TS-8 *Issue Tracking*]
* link:./009/[TS-9 *Version Control*]
* link:./010/[TS-10 *Releasing*]
* link:./011/[TS-11 *Versioning*]
* link:./012/[TS-12 *Quality Assurance*]
* link:./013/[TS-13 *Functional Testing*]
* link:./014/[TS-14 *Performance Testing*]
* link:./015/[TS-15 *User Interfaces*]
* link:./016/[TS-16 *Command Line Interfaces (CLIs)*]
* link:./017/[TS-17 *Graphical User Interfaces (GUIs)*]
* link:./018/[TS-18 *Web GUIs*]
* link:./019/[TS-19 *Search Engine Optimization (SEO)*]
* link:./020/[TS-20 *Network APIs*]
* link:./021/[TS-21 *HTTP APIs*]
* link:./022/[TS-22 *Webhooks*]
* link:./023/[TS-23 *Messages and Events*]
* link:./024/[TS-24 *User Manuals*]
* link:./025/[TS-25 *Technical Documentation*]
* link:./026/[TS-26 *Technical Writing Style Guide*]
* link:./027/[TS-27 *Markdown*]
* link:./028/[TS-28 *AsciiDoc*]
* link:./029/[TS-29 *JSON Schema*]
* link:./030/[TS-30 *YAML*]
* link:./031/[TS-31 *Unix Shells*]
* link:./032/[TS-32 *Bash*]
* link:./033/[TS-33 *Java*]
* link:./034/[TS-34 *PHP*]
* link:./035/[TS-35 *Python*]
* link:./036/[TS-36 *ECMAScript (JavaScript/TypeScript)*]
* link:./037/[TS-37 *Web Platform APIs*]
* link:./038/[TS-38 *Node.js Applications*]
* link:./039/[TS-39 *HTML*]
* link:./040/[TS-40 *CSS*]
