= Choosing models

When training coding-flavored LLMs, AI companies download millions of examples of software code from sources like GitHub and use them to train the models. Subsequently, the companies further optimize the models for coding tasks through a process known as fine-tuning.

No matter how good that fine-tuning process is, the resulting model will still be limited by the quality and breadth of its training data. If the training data is biased toward certain languages, frameworks, or programming styles, the model will reflect those biases in its outputs.

This limitation is true of all AI models – not only coding agents – that are based on the https://en.wikipedia.org/wiki/Transformer_(deep_learning)[transformer architecture]. It's because a model's knowledge of semantic associations is learnt from its training data. In neural networks, words act as addresses that unlock semantic relationships encoded in the model's parameters. Context shapes meaning. Thus, the word "bank" means something different when preceded by "river" or "central". Larger LLMs can potentially make deeper contextual connections than smaller ones, because they have more parameters linked in more multidimensional ways, producing a richer map of semantic relationships.

The effect is that today's AI coding agents are very good at generating code in modern programming languages like JavaScript and HTML, but they are generally poor at things like 6502 Assembly and niche domain-specific languages. They just don't have the deep knowledge of those languages – the depth of semantic associations encoded in their parameters – gleaned from their training data to produce good outputs.

This is a key consideration when choosing a model to use for a given task. You want to choose a model that has been trained on data relevant to the task at hand. General purpose models will be adequate for many tasks in modern programming languages, but for more specialized tasks you may get better results using more specialized models.
