= Secrets

== Secrets in configuration files

Secrets MUST NOT be hard-coded in Terraform configuration files – even if those
files are securely committed to private version control repositories.

[source,hcl]
----
provider "aws" {
  region = "eu-west-2"

  access_key = "AKIA..."
  secret_key = "yvDpm..."
}
----

Access credentials MUST be retrieved either from the environment or a secure
remote vault.

The AWS provider allows the importing of access credentials from the AWS CLI's
`~/.aws/credentials` file. In the following example, the credentials are loaded
from the "default" profile defined in that file.

[source,hcl]
----
provider "aws" {
  profile = "default"
  region = "eu-west-2"
}
----

.~/.aws/credentials
[source,ini]
----
[default]
aws_access_key_id = AKIA...
aws_secret_access_key = yvDpm...
----

For other secrets, the RECOMMENDED approach is to pass the secrets in from
environment variables. Environment variables with the `TF_VAR_` prefix will be
automatically picked up by Terraform and "auto-filled" into variables, as though
the variables had been set via the command line or in `terraform.tfvars`. The
following example shows how to set the `password` variable using an environment
variable:

----
export TF_VAR_password=abcdefghik
----

== Secrets in outputs

Secrets MUST NOT be exposed in output from `terraform apply` commands. To
achieve this, secret values are given the `sensitive = true` argument in output
blocks. This means the value will not be displayed in the console output when
running `terraform apply`.

[source,hcl]
----
output "rds_password" {
  value     = data.aws_ssm_parameter.rds_password.value
  sensitive = true
}
----

This is a good practice for sensitive information like passwords. It means
secrets will not leak into log files in, say, automation pipelines.

== Secrets in state files

Secrets such as passwords for databases _will_ be printed in the
`terraform.tfstate` file, whether or not those secrets are printed in output or
marked as sensitive. Therefore, it is important to ensure that the state file is
stored securely and access is restricted to only authorized personnel.

It is RECOMMENDED to use encryption at rest for the state file. State files MAY
be encrypted in private Git repositories using tools such as
https://git-secret.io/[git-secret],
https://github.com/elasticdog/transcrypt[transcript], or
https://github.com/mozilla/sops[SOPS]. But it is best practice to exclude state
files from version control entirely, and instead store them in a secure
back-end, such as an S3 bucket with server-side encryption. See the section on
*Remote state and back-ends*, below, for more guidance on this topic.
