= Claims

JWTs are composed of claims, which are pieces of information asserted about a
subject (usually a user). The design of these claims is critical for effective
authentication and authorization.

It is RECOMMENDED to repurpose standard claims and structures where possible.
Using standard JWT schema will mean higher interoperability with existing (and
future) libraries and services.

Standardized claims include:

* `iss` (issuer): Identifies the entity that issued the token.
* `sub` (subject): Typically the user ID or unique identifier for the subject of
the token.
* `aud` (audience): Specifies the intended recipients or services for which the
token is valid.
* `exp` (expiration): Sets the expiration time for the token, after which it is
no longer valid.
* `iat` (issued at): Indicates the time at which the token was issued.
* `nbf` (not before): Indicates the time before which the token must not be
accepted for processing.
* `jti` (JWT ID): A unique identifier for the token, useful for preventing
replay attacks and managing token revocation.
