= TS-4: Releasing
:toc: macro
:toc-title: Contents

This technical standard covers best practices for releasing software updates. The focus of these guidelines is on release strategies that minimize the risk of bugs, regressions, and incidents occurring in production.

These guidelines are applicable to both software-as-a-product, which tends to be intermittently released, and software-as-a-service, which tends to be more continuously released.

This technical standard is concerned with production releases, rather than deployments to other environments such as test and staging environments.

See also link:../005/README.adoc[TS-5: Versioning]. 

toc::[]

== Canary testing

"Canary rollout", "canary testing", or "canarying" comes from the early 20th century practice of using canaries in coal mines to detect carbon monoxide. Miners would take caged canary birds with them underground. The bird has a lower tolerance for toxic gases than humans do, so if the birds stopped chirping – or fainted – the miners knew gas was present and they needed to evacuate the mine.

In software, canary testing is a technique to reduce the risk of introducing a new version of a software service by initially rolling out the change to only a small subset of users. Common methodologies to implement canary rollouts include routing a small percentage of traffic to the new version using a load balancer, or to deploy the new version to a single node. Canary testing can also be done for software products.

An extension of canary testing is staged rollouts, in which the percentage of users receiving the new version continues to be gradually ramped up. Between each rollout stage, the health of the new version is monitored and criteria are set for the rollout to continue.

Canarying and staged rollouts are particularly useful for services that are difficult to test in isolation, or where the potential impact of a failure is high. Both were true of the link:https://newsletter.pragmaticengineer.com/p/the-biggest-ever-global-outage-lessons[July 2024 CrowdStrike update] that caused the biggest IT outage in history. CrowdStrike's software operates at the kernel level in Windows, which is inherently difficult to test in isolation and in an automated way. And such software is inherently high risk and high impact, as it has the highest level of privileges on the system. Yet the buggy update was rolled out globally at once.


''''

== Related links

* link:https://newsletter.pragmaticengineer.com/p/shipping-to-production[Shipping to production], Gergely Orosz, The Pragmatic Engineer (2022)
